Repository PaddlePaddle/docs, pull requests merged in 2018-10, with the labels that each got.

#169 Create LoD-Tensor.md
  doc/fluid/user_guides/design_idea/lod_tensor.md
Labels: 使用文档

#223 add index for lod_tensor
  doc/fluid/user_guides/howto/prepare_data/index.rst
  doc/fluid/user_guides/howto/prepare_data/lod_tensor.md
Labels: 使用文档

#213 Update optimizer_all.rst
  doc/fluid/api/api_guides/low_level/optimizer/optimizer_all.rst
Labels: API Guide

#230 Add conv guides
  doc/fluid/api/api_guides/low_level/layers/conv.rst
Labels: API Guide

#233 update install doc for 1.0.2
  doc/fluid/beginners_guide/install/compile/compile_CentOS.md
  doc/fluid/beginners_guide/install/compile/compile_MacOS.md
  doc/fluid/beginners_guide/install/compile/compile_Ubuntu.md
  doc/fluid/beginners_guide/install/install_CentOS.md
  doc/fluid/beginners_guide/install/install_MacOS.md
  doc/fluid/beginners_guide/install/install_Ubuntu.md
  doc/fluid/beginners_guide/install/install_Windows.md
Labels: 安装文档

#238 Add api guide for control flow
  doc/fluid/api/api_guides/low_level/layers/control_flow.rst
Labels: API Guide

#225 Add api guide for loss function
  doc/fluid/api/api_guides/low_level/layers/loss_function.rst
  doc/fluid/api/layers.rst
Labels: API Guide

#186 add paddle cpu version info on table
  doc/fluid/beginners_guide/install/Tables.md
Labels: 安装文档

#242 cherry-pick from 1.0 to add cpu install info in Tables.md
  doc/fluid/beginners_guide/install/Tables.md
Labels: 安装文档

#207 Add activation doc
  doc/fluid/api/api_guides/low_level/layers/activations.rst
Labels: API Guide

#215 update build_and_install_lib_cn
  doc/fluid/user_guides/howto/inference/build_and_install_lib_cn.rst
Labels: 使用文档

#210 Add models' saver and reader.
  doc/fluid/api/api_guides/low_level/layers/model_save_reader.rst
Labels: API Guide

#243 reorder the api
  doc/fluid/api/clip.rst
  doc/fluid/api/executor.rst
  doc/fluid/api/fluid.rst
  doc/fluid/api/gen_doc.py
  doc/fluid/api/gen_index.py
  doc/fluid/api/index_en.rst
  doc/fluid/api/initializer.rst
  doc/fluid/api/io.rst
  doc/fluid/api/layers.rst
  doc/fluid/api/metrics.rst
  doc/fluid/api/nets.rst
  doc/fluid/api/optimizer.rst
  doc/fluid/api/profiler.rst
  doc/fluid/api/regularizer.rst
  doc/fluid/api/transpiler.rst
Labels: API Reference

#250 add doc for distribute lookup table
  doc/fluid/user_guides/howto/training/cluster_howto.rst
Labels: 使用文档

#251 update install doc for 1.1
  doc/fluid/beginners_guide/install/compile/compile_CentOS.md
  doc/fluid/beginners_guide/install/compile/compile_MacOS.md
  doc/fluid/beginners_guide/install/compile/compile_Ubuntu.md
  doc/fluid/beginners_guide/install/install_CentOS.md
  doc/fluid/beginners_guide/install/install_MacOS.md
  doc/fluid/beginners_guide/install/install_Ubuntu.md
  doc/fluid/beginners_guide/install/install_Windows.md
Labels: 安装文档

#241 update overview
  doc/fluid/advanced_usage/index.rst
  doc/fluid/beginners_guide/index.rst
  doc/fluid/index_cn.rst
  doc/fluid/overview.md
  doc/fluid/user_guides/index.rst
Labels: 使用文档
