Repository PaddlePaddle/docs, pull requests merged in 2019-04, with the labels that each got.

#745 incorrect link and deadlink in lod_tensor_en.rst
  doc/fluid/user_guides/howto/basic_concept/lod_tensor_en.rst
Labels: user contribution

#741 fix metric example
  doc/fluid/user_guides/howto/evaluation_and_debugging/evaluation/metrics.rst
Labels: to be translated, user contribution

#742 Fix indent
  doc/fluid/beginners_guide/programming_guide/programming_guide.md
  doc/fluid/beginners_guide/programming_guide/programming_guide_en.md
Labels: user contribution

#740 English version lack of example
  doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst
Labels: user contribution

#761 Add CompiledProgram doc
  doc/fluid/api_guides/index_en.rst
  doc/fluid/api_guides/low_level/compiled_program_en.rst
  doc/fluid/api_guides/low_level/executor_en.rst
  doc/fluid/api_guides/low_level/parallel_executor_en.rst
  doc/fluid/user_guides/howto/training/single_node_en.rst
Labels: to be translated

#705 Update metrics.rst
  doc/fluid/user_guides/howto/evaluation_and_debugging/evaluation/metrics.rst
Labels: user contribution

#739 fix reader not match
  doc/fluid/user_guides/howto/prepare_data/use_py_reader.rst
Labels: user contribution

#777 Fix reader eng test=develop
  doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst
Labels: user contribution

#767 api_trans_0410
  doc/fluid/api_cn/fluid_cn.rst
  doc/fluid/api_cn/io_cn.rst
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation

#780 translate compiled_program
  doc/fluid/api_guides/low_level/compiled_program_cn.rst
Labels: Translation

#781 Update executor.rst
  doc/fluid/api_guides/low_level/executor.rst
Labels: Translation

#782 Update parallel_executor.rst
  doc/fluid/api_guides/low_level/parallel_executor.rst
Labels: Translation

#783 Update single_node.rst
  doc/fluid/user_guides/howto/training/single_node.rst
Labels: Translation

#713 update catalog name to match item name in windows source compilation
  doc/fluid/beginners_guide/install/compile/compile_Windows.md
Labels: user contribution

#712 update catalog name to match item name in ubuntu source compilation
  doc/fluid/beginners_guide/install/compile/compile_Ubuntu.md
Labels: user contribution

#710 update catalog name to match item name in CentOS source compilation
  doc/fluid/beginners_guide/install/compile/compile_CentOS.md
Labels: user contribution

#776 API Translation & Update 1.3 => develop (4.16)
  doc/fluid/api_cn/dataset_cn.rst
  doc/fluid/api_cn/fluid_cn.rst
  doc/fluid/api_cn/index_cn.rst
  doc/fluid/api_cn/layers_cn.rst
  doc/fluid/api_cn/optimizer_cn.rst
Labels: API Translation

#794 Fix fluid cn cpu_places,CPUPlace,cuda_pinned_places and alike
  doc/fluid/api_cn/fluid_cn.rst
Labels: API Translation

#769 api modification
  doc/fluid/api_cn/fluid_cn.rst
  doc/fluid/api_cn/io_cn.rst
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation

#796 update API_CN to 4.16 develop (refer to Paddle/#16882 #16864)
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation

#738 add init Program
  doc/fluid/user_guides/howto/prepare_data/feeding_data.rst
  doc/fluid/user_guides/howto/prepare_data/feeding_data_en.rst
Labels: user contribution

#737 Fix create lod tensor API
  doc/fluid/user_guides/howto/prepare_data/feeding_data.rst
  doc/fluid/user_guides/howto/prepare_data/feeding_data_en.rst
Labels: user contribution

#792 Update native_infer_en.md
  doc/fluid/advanced_usage/deploy/inference/native_infer_en.md
Labels: Translation

#809 add xmap_readers_doc
  doc/fluid/api_cn/data/data_reader_cn.rst
Labels: API Translation

#787 Update native_infer_en.md
  doc/fluid/advanced_usage/deploy/inference/native_infer_en.md
Labels: Translation

#790 Update install_Windows_en.md
  doc/fluid/beginners_guide/install/install_Windows_en.md
Labels: Translation

#791 Update cluster_howto_en.rst
  doc/fluid/user_guides/howto/training/cluster_howto_en.rst
Labels: Translation

#788 Update paddle_tensorrt_infer_en.md
  doc/fluid/advanced_usage/deploy/inference/paddle_tensorrt_infer_en.md
Labels: Translation

#793 Update use_py_reader_en.rst
  doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst
Labels: Translation

#804 Update learning_rate_scheduler_en.rst
  doc/fluid/api_guides/low_level/layers/learning_rate_scheduler_en.rst
Labels: Translation

#807 Update cluster_howto_en.rst
  doc/fluid/user_guides/howto/training/cluster_howto_en.rst
Labels: Translation

#817 fix dygraph load_persistables bug
  doc/fluid/user_guides/howto/dygraph/DyGraph.md
Labels: to be reviewed

#779 Update new_op doc
  doc/fluid/advanced_usage/development/new_op/new_op.md
Labels: to be reviewed

#778 Update op notes
  doc/fluid/advanced_usage/development/new_op/op_notes.md
Labels: to be reviewed

#822 Update metrics_en.rst
  doc/fluid/user_guides/howto/evaluation_and_debugging/evaluation/metrics_en.rst
Labels: Translation

#820 Update lod_tensor_en.rst
  doc/fluid/user_guides/howto/basic_concept/lod_tensor_en.rst
Labels: Translation
