Repository PaddlePaddle/docs, pull requests merged in 2019-02, with the labels that each got.

#611 FluidModel Fix
  doc/fluid/index_en.rst
  doc/fluid/user_guides/index_en.rst
  doc/fluid/user_guides/models/index_en.rst
  doc/fluid/user_guides/models/indexen.rst
Labels: Translation, 使用文档, 定稿

#615 Cherry-pick all user guides to 1.2
  doc/fluid/index_en.rst
  doc/fluid/user_guides/howto/basic_concept/index_en.rst
  doc/fluid/user_guides/howto/basic_concept/lod_tensor_en.rst
  doc/fluid/user_guides/howto/configure_simple_model/index_en.rst
  doc/fluid/user_guides/howto/evaluation_and_debugging/debug/visualdl.md
  doc/fluid/user_guides/howto/evaluation_and_debugging/debug/visualdl_en.md
  doc/fluid/user_guides/howto/evaluation_and_debugging/evaluation/metrics_en.rst
  doc/fluid/user_guides/howto/evaluation_and_debugging/index_en.rst
  doc/fluid/user_guides/howto/prepare_data/feeding_data_en.rst
  doc/fluid/user_guides/howto/prepare_data/index_en.rst
  doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst
  doc/fluid/user_guides/howto/training/cluster_howto_en.rst
  doc/fluid/user_guides/howto/training/cluster_quick_start_en.rst
  doc/fluid/user_guides/howto/training/index_en.rst
  doc/fluid/user_guides/howto/training/multi_node_en.rst
  doc/fluid/user_guides/howto/training/save_load_variables_en.rst
  doc/fluid/user_guides/howto/training/single_node_en.rst
  doc/fluid/user_guides/howto/training/test_while_training_en.rst
  doc/fluid/user_guides/howto/training/train_on_baidu_cloud_en.rst
  doc/fluid/user_guides/index_en.rst
  doc/fluid/user_guides/models/index_en.rst
Labels: Translation, 使用文档, 定稿

#567 upload fluid_design_ideaen.md
  doc/fluid/advanced_usage/design_idea/fluid_design_idea_en.md
Labels: Translation, 使用文档, 定稿

#616 fix pr 521 wrong file name and path
  doc/fluid/advanced_usage/development/contribute_to_paddle/local_dev_guide_en.md
  doc/fluid/advanced_usage/development/contribute_to_paddle/submit_pr_guide_en.md
Labels: Translation, 使用文档, 定稿

#581 update inference doc (analysis predictor and trt int8) for 1.3
  doc/fluid/advanced_usage/deploy/inference/native_infer.md
  doc/fluid/advanced_usage/deploy/inference/paddle_tensorrt_infer.md
Labels: 使用文档

#561 build_and_install_lib_en
  doc/fluid/advanced_usage/deploy/inference/build_and_install_lib_en.rst
Labels: Translation, 使用文档, 定稿

#569 native_infer_en
  doc/fluid/advanced_usage/deploy/inference/native_infer_en.md
Labels: Translation, 使用文档, 定稿

#573 paddle_tensorrt_infer_en
  doc/fluid/advanced_usage/deploy/inference/paddle_tensorrt_infer_en.md
Labels: Translation, 使用文档

#570 paddle_gpu_benchmark_en
  doc/fluid/advanced_usage/deploy/inference/paddle_gpu_benchmark_en.md
Labels: Translation, 使用文档, 定稿

#575 windows_cpp_inference_en
  doc/fluid/advanced_usage/deploy/inference/windows_cpp_inference_en.md
Labels: Translation, 使用文档, 定稿

#576 mobile_readme_en
  doc/fluid/advanced_usage/deploy/mobile/mobile_readme_en.md
Labels: Translation, 使用文档, 定稿

#594 mobile_build_en
  doc/fluid/advanced_usage/deploy/mobile/mobile_build_en.md
Labels: Translation, 使用文档, 定稿

#568 upload new_op_en.md
  doc/fluid/advanced_usage/development/new_op/new_op_en.md
  doc/fluid/dev/new_op_en.md
Labels: Translation, 使用文档, 定稿

#572 upload op_notesen
  doc/fluid/advanced_usage/development/new_op/op_notes_en.md
Labels: Translation, 使用文档

#578 upload write_docs_en.md
  doc/fluid/advanced_usage/development/write_docs_en.md
Labels: Translation, 使用文档, 定稿

#589 host_memo_profile
  doc/fluid/advanced_usage/development/profiling/host_memory_profiling_en.md
Labels: Translation, 使用文档, 定稿

#626 fix write new op index
  doc/fluid/advanced_usage/development/new_op/index_en.rst
Labels: Translation, 使用文档, 定稿

#633 Change api guides directory
  doc/fluid/api_cn/gen_index.py
  doc/fluid/api_cn/index_cn.rst
  doc/fluid/api_guides/high_low_level_api.md
  doc/fluid/api_guides/high_low_level_api_en.md
  doc/fluid/api_guides/index.rst
  doc/fluid/api_guides/index_en.rst
  doc/fluid/api_guides/low_level/backward.rst
  doc/fluid/api_guides/low_level/distributed/async_training.rst
  doc/fluid/api_guides/low_level/distributed/cluster_train_data_cn.rst
  doc/fluid/api_guides/low_level/distributed/cpu_train_best_practice.rst
  doc/fluid/api_guides/low_level/distributed/index.rst
  doc/fluid/api_guides/low_level/distributed/index_en.rst
  doc/fluid/api_guides/low_level/distributed/large_scale_sparse_feature_training.rst
  doc/fluid/api_guides/low_level/distributed/sync_training.rst
  doc/fluid/api_guides/low_level/executor.rst
  doc/fluid/api_guides/low_level/inference.rst
  doc/fluid/api_guides/low_level/layers/activations.rst
  doc/fluid/api_guides/low_level/layers/control_flow.rst
  doc/fluid/api_guides/low_level/layers/conv.rst
  doc/fluid/api_guides/low_level/layers/data_feeder.rst
  doc/fluid/api_guides/low_level/layers/data_in_out.rst
  doc/fluid/api_guides/low_level/layers/detection.rst
  doc/fluid/api_guides/low_level/layers/index.rst
  doc/fluid/api_guides/low_level/layers/index_en.rst
  doc/fluid/api_guides/low_level/layers/learning_rate_scheduler.rst
  doc/fluid/api_guides/low_level/layers/loss_function.rst
  doc/fluid/api_guides/low_level/layers/math.rst
  doc/fluid/api_guides/low_level/layers/pooling.rst
  doc/fluid/api_guides/low_level/layers/sequence.rst
  doc/fluid/api_guides/low_level/layers/sparse_update.rst
  doc/fluid/api_guides/low_level/layers/tensor.rst
  doc/fluid/api_guides/low_level/memory_optimize.rst
  doc/fluid/api_guides/low_level/metrics.rst
  doc/fluid/api_guides/low_level/model_save_reader.rst
  doc/fluid/api_guides/low_level/nets.rst
  doc/fluid/api_guides/low_level/optimizer.rst
  doc/fluid/api_guides/low_level/parallel_executor.rst
  doc/fluid/api_guides/low_level/parameter.rst
  doc/fluid/api_guides/low_level/program.rst
Labels: Translation, 使用文档, 定稿

#631 upload parallel_executor_en.rst
  doc/fluid/api_guides/low_level/parallel_executor_en.rst
Labels: Translation, 使用文档, 定稿

#628 upload memory_optimize_en.rst and nets_en.rst
  doc/fluid/api_guides/low_level/memory_optimize_en.rst
  doc/fluid/api_guides/low_level/nets_en.rst
Labels: Translation, 使用文档, 定稿

#630 Add control_flow_en.rst and loss_function_en.rst and metric_en.rst
  doc/fluid/api_guides/low_level/layers/control_flow_en.rst
  doc/fluid/api_guides/low_level/layers/loss_function_en.rst
  doc/fluid/api_guides/low_level/metrics_en.rst
Labels: Translation, 使用文档, 定稿

#617 upload cluster_train_data_en.rst
  doc/fluid/api_guides/low_level/distributed/cluster_train_data_en.rst
Labels: Translation, 使用文档, 定稿

#560 programming_guide_en
  doc/fluid/beginners_guide/programming_guide/programming_guide_en.md
Labels: Translation, 使用文档, 定稿

#610 data_in_out_en
  doc/fluid/api_guides/low_level/layers/data_in_out_en.rst
Labels: Translation, 使用文档, 定稿

#583 upload /sequenceen.rst
  doc/fluid/api_guides/low_level/layers/sequence_en.rst
Labels: Translation, 使用文档, 定稿

#585 upload mathen.rst
  doc/fluid/api_guides/low_level/layers/math_en.rst
Labels: Translation, 使用文档, 定稿

#586 upload sync_trainingen.rst
  doc/fluid/api_guides/low_level/distributed/sync_training_en.rst
Labels: Translation, 使用文档, 定稿

#599 inference_en
  doc/fluid/api_guides/low_level/inference_en.rst
Labels: Translation, 使用文档, 定稿

#600 model_save_reader_en
  doc/fluid/api_guides/low_level/model_save_reader_en.rst
Labels: Translation, 使用文档, 定稿

#601 executor_en
  doc/fluid/api_guides/low_level/layers/executor_en.rst
Labels: Translation, 使用文档, 定稿

#603 tensor_en
  doc/fluid/api_guides/low_level/layers/tensor_en.rst
Labels: Translation, 使用文档, 定稿

#602 optimizer_en
  doc/fluid/api_guides/low_level/optimizer_en.rst
Labels: Translation, 使用文档, 定稿

#604 conv_en
  doc/fluid/api_guides/low_level/layers/conv_en.rst
Labels: Translation, 使用文档, 定稿

#605 sparse_update_en
  doc/fluid/api_guides/low_level/layers/sparse_update_en.rst
Labels: Translation, 使用文档, 定稿

#593 upload large_scale_sparse_feature_training_en.rst
  doc/fluid/api_guides/low_level/distributed/large_scale_sparse_feature_training_en.rst
Labels: Translation, 使用文档, 定稿

#592 upload cpu_train_best_practice_en.rst
  doc/fluid/api_guides/low_level/distributed/cpu_train_best_practice_en.rst
Labels: Translation, 使用文档, 定稿

#591 upload async_training_en.rst
  doc/fluid/api_guides/low_level/distributed/async_training_en.rst
Labels: Translation, 使用文档, 定稿

#587 upload activationsen.rst
  doc/fluid/api_guides/low_level/layers/activations_en.rst
Labels: Translation, 使用文档, 定稿

#606 data_feeder_en
  doc/fluid/api_guides/low_level/layers/data_feeder_en.rst
Labels: Translation, 使用文档, 定稿

#609 detection_en
  doc/fluid/api_guides/low_level/layers/detection_en.rst
Labels: Translation, 使用文档, 定稿

#608 pooling_en
  doc/fluid/api_guides/low_level/layers/pooling_en.rst
Labels: Translation, 使用文档, 定稿

#607 learning_rate_scheduler_en
  doc/fluid/api_guides/low_level/layers/learning_rate_scheduler_en.rst
Labels: Translation, 使用文档, 定稿

#640 [Important] Add index for api_guides and fix some bugs
  doc/fluid/api/gen_index.py
  doc/fluid/api/index_en.rst
  doc/fluid/api_guides/low_level/executor_en.rst
  doc/fluid/api_guides/low_level/layers/tensor_en.rst
  doc/fluid/beginners_guide/index_en.rst
Labels: Translation, 使用文档, 定稿

#634 update inference c++ API doc
  doc/fluid/advanced_usage/deploy/inference/native_infer.md
Labels: 使用文档

#637 Modify py_reader doc
  doc/fluid/user_guides/howto/prepare_data/use_py_reader.rst
Labels: 使用文档

#646 add maxdepth for API Reference index page
  doc/fluid/api/gen_index.py
  doc/fluid/api/index_en.rst
  doc/fluid/api_cn/gen_index.py
  doc/fluid/api_cn/index_cn.rst
Labels: 使用文档

#651 Translation of 16 new apis and delete one removed fluid.Scope
  doc/fluid/api_cn/fluid_cn.rst
  doc/fluid/api_cn/initializer_cn.rst
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation

#655 [to 1.3] cn api debug
  doc/fluid/api_cn/io_cn.rst
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation, 中文API优化
