Repository PaddlePaddle/docs, pull requests merged in 2019-06, with the labels that each got.

#888 refine inference api
  doc/fluid/advanced_usage/deploy/inference/native_infer.md
  doc/fluid/advanced_usage/deploy/inference/paddle_tensorrt_infer.md
Labels: 使用文档

#693 Add benchmark document for fluid
  doc/fluid/advanced_usage/development/profiling/benchmark_cn.md
  doc/fluid/advanced_usage/development/profiling/index_cn.rst
Labels: pending

#819 Create quick_start.rst
  doc/fluid/beginners_guide/quick_start.rst
Labels: Translation

#969 6.29 API_cn update
  doc/fluid/api_cn/layers_cn.rst
Labels: API Translation

#970 break up layers and change index of layers
  doc/fluid/api_cn/layers-breakdown.py
  doc/fluid/api_cn/layers_cn.rst
  doc/fluid/api_cn/layers_cn/control_flow_cn.rst
  doc/fluid/api_cn/layers_cn/detection_cn.rst
  doc/fluid/api_cn/layers_cn/io_cn.rst
  doc/fluid/api_cn/layers_cn/learning_rate_scheduler_cn.rst
  doc/fluid/api_cn/layers_cn/metric_op_cn.rst
  doc/fluid/api_cn/layers_cn/nn_cn.rst
  doc/fluid/api_cn/layers_cn/ops_cn.rst
  doc/fluid/api_cn/layers_cn/tensor_cn.rst
Labels: 文档管理
