Repository PaddlePaddle/docs, pull requests merged in 2019-01, with the labels that each got.

#521 Submit pr guide
  doc/fluid/advanced_usage/development/local_dev_guide.md
  doc/fluid/advanced_usage/development/submit_pr_guide.md
Labels: Translation, tobe-toctreed

#529 recover_api_doc_v1.1
  doc/fluid/api_cn/CMakeLists.txt
  doc/fluid/api_cn/api_guides/high_low_level_api.md
  doc/fluid/api_cn/api_guides/index.rst
  doc/fluid/api_cn/api_guides/low_level/executor.rst
  doc/fluid/api_cn/api_guides/low_level/inference.rst
  doc/fluid/api_cn/api_guides/low_level/layers/activations.rst
  doc/fluid/api_cn/api_guides/low_level/layers/control_flow.rst
  doc/fluid/api_cn/api_guides/low_level/layers/conv.rst
  doc/fluid/api_cn/api_guides/low_level/layers/data_in_out.rst
  doc/fluid/api_cn/api_guides/low_level/layers/detection.rst
  doc/fluid/api_cn/api_guides/low_level/layers/index.rst
  doc/fluid/api_cn/api_guides/low_level/layers/loss_function.rst
  doc/fluid/api_cn/api_guides/low_level/layers/math.rst
  doc/fluid/api_cn/api_guides/low_level/layers/pooling.rst
  doc/fluid/api_cn/api_guides/low_level/layers/sequence.rst
  doc/fluid/api_cn/api_guides/low_level/metrics.rst
  doc/fluid/api_cn/api_guides/low_level/model_save_reader.rst
  doc/fluid/api_cn/api_guides/low_level/optimizer.rst
  doc/fluid/api_cn/average.rst
  doc/fluid/api_cn/backward.rst
  doc/fluid/api_cn/clip.rst
  doc/fluid/api_cn/data/data_reader.rst
  doc/fluid/api_cn/data/dataset.rst
  doc/fluid/api_cn/data/image.rst
  doc/fluid/api_cn/data_feeder.rst
  doc/fluid/api_cn/executor.rst
  doc/fluid/api_cn/fluid.rst
  doc/fluid/api_cn/gen_doc.py
  doc/fluid/api_cn/gen_doc.sh
  doc/fluid/api_cn/gen_index.py
  doc/fluid/api_cn/index_cn.rst
  doc/fluid/api_cn/initializer.rst
  doc/fluid/api_cn/io.rst
  doc/fluid/api_cn/layers.rst
  doc/fluid/api_cn/menu.json
  doc/fluid/api_cn/metrics.rst
  doc/fluid/api_cn/nets.rst
  doc/fluid/api_cn/optimizer.rst
  doc/fluid/api_cn/param_attr.rst
  doc/fluid/api_cn/profiler.rst
  doc/fluid/api_cn/regularizer.rst
  doc/fluid/api_cn/transpiler.rst
  doc/fluid/index_cn.rst
Labels: API Reference, bug

#522 Update lod_tensor.rst
  doc/fluid/user_guides/howto/basic_concept/lod_tensor.rst
Labels: Synchronize to develop

#523 cn api fix bugs
  doc/fluid/api_cn/fluid_cn.rst
  doc/fluid/api_cn/layers_cn.rst
Labels: API Reference

#512 python reader en-zh
  doc/fluid/user_guides/howto/prepare_data/reader.md
  doc/fluid/user_guides/howto/prepare_data/reader_cn.md
Labels: Translation

#535 0114-cnapi-bugfix
  doc/fluid/api_cn/initializer_cn.rst
  doc/fluid/api_cn/optimizer_cn.rst
Labels: API Translation

#540 update_inference_link
  doc/fluid/advanced_usage/deploy/inference/build_and_install_lib_cn.rst
Labels: 使用文档

#542 update_inference_link
  doc/fluid/advanced_usage/deploy/inference/build_and_install_lib_cn.rst
Labels: 使用文档

#548 1.18 planned cn doc fix
  doc/fluid/api_cn/layers_cn.rst
  doc/fluid/user_guides/howto/training/cluster_howto.rst
Labels: API Reference

#549 upload save_load_variables_en
  doc/fluid/user_guides/howto/training/save_load_variables_en.rst
Labels: Translation, 使用文档, 定稿

#551 upload indexen
  doc/fluid/user_guides/models/indexen.rst
Labels: Translation, 使用文档, 定稿

#554 lod_tensor_en
  doc/fluid/user_guides/howto/basic_concept/lod_tensor_en.rst
Labels: Translation, 使用文档, 定稿

#557 simple_model
  doc/fluid/user_guides/howto/configure_simple_model/index_en.rst
Labels: Translation, 使用文档, 定稿

#558 single_node
  doc/fluid/user_guides/howto/training/single_node_en.rst
Labels: Translation, 使用文档, 定稿

#559 test_while_training
  doc/fluid/user_guides/howto/training/test_while_training_en.rst
Labels: Translation, 使用文档, 定稿

#564 py_reader_en
  doc/fluid/user_guides/howto/prepare_data/use_py_reader_en.rst
Labels: Translation, 使用文档, 定稿

#595 user guides index of all
  doc/fluid/index_en.rst
  doc/fluid/user_guides/howto/basic_concept/index_en.rst
  doc/fluid/user_guides/howto/evaluation_and_debugging/index_en.rst
  doc/fluid/user_guides/howto/prepare_data/index_en.rst
  doc/fluid/user_guides/howto/training/index_en.rst
  doc/fluid/user_guides/howto/training/multi_node_en.rst
  doc/fluid/user_guides/index_en.rst
Labels: Translation, 使用文档, 定稿
