Repository PaddlePaddle/docs, pull requests merged in 2022-12, with the labels that each got.

#5460 [CodeStyle][py36] 修改部分关于 py36 的内容
  docs/install/FAQ.md
  docs/install/FAQ_en.md
  docs/install/Tables.md
  docs/install/Tables_en.md
  docs/install/compile/arm-compile.md
  docs/install/compile/linux-compile.md
  docs/install/compile/linux-compile_en.md
  docs/install/compile/macos-compile.md
  docs/install/compile/macos-compile_en.md
  docs/install/compile/mips-compile.md
  docs/install/compile/sw-compile.md
  docs/install/compile/windows-compile.md
  docs/install/compile/windows-compile_en.md
  docs/install/compile/zhaoxin-compile.md
  docs/install/conda/linux-conda_en.md
  docs/install/conda/macos-conda_en.md
  docs/install/conda/windows-conda_en.md
  docs/install/index_cn.rst
  docs/install/index_en.rst
  docs/install/pip/linux-pip.md
  docs/install/pip/linux-pip_en.md
  docs/install/pip/macos-pip.md
  docs/install/pip/macos-pip_en.md
  docs/install/pip/windows-pip.md
Labels: contributor, status: proposed

#5467 动态图静态图英文翻译统一
  docs/guides/jit/debugging_en.md
  docs/guides/jit/grammar_list_en.md
  docs/guides/jit/index_en.rst
  docs/guides/performance_improving/amp_en.md
Labels: contributor, status: proposed

#5480 修复重复张量
  docs/api/paddle/io/Overview_cn.rst
  docs/api/paddle/nn/Softmax2D_cn.rst
Labels: contributor, status: proposed

#5468 fix chinese typo errors
  docs/api/paddle/vision/ops/DeformConv2D_cn.rst
  docs/api/paddle/vision/ops/RoIAlign_cn.rst
  docs/api/paddle/vision/ops/RoIPool_cn.rst
  docs/api/paddle/vision/ops/decode_jpeg_cn.rst
  docs/api/paddle/vision/ops/deform_conv2d_cn.rst
  docs/api/paddle/vision/ops/read_file_cn.rst
  docs/api/paddle/vision/ops/roi_align_cn.rst
  docs/api/paddle/vision/ops/roi_pool_cn.rst
  docs/api/paddle/vision/ops/yolo_box_cn.rst
  docs/api/paddle/vision/ops/yolo_loss_cn.rst
  docs/api/paddle/vision/transforms/ContrastTransform_cn.rst
Labels: status: not progressed

#5448 fix typo errors in file tensor_cn.md
  docs/guides/beginner/tensor_cn.md
Labels: contributor, status: not progressed

#5453 对多个文档按照要求修改
  docs/api/paddle/nn/MultiLabelSoftMarginLoss_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/Unfold_cn.rst
  docs/api/paddle/nn/Upsample_cn.rst
  docs/api/paddle/nn/functional/mse_loss_cn.rst
  docs/api/paddle/nn/functional/unfold_cn.rst
Labels: contributor, status: proposed

#5424 [docs][ARBG]Tensor 介绍 章节中 部分三级标题使用规范错误的修正
  docs/guides/beginner/tensor_cn.md
Labels: contributor, status: proposed

#5495 fix chinese type errors (#5468)
  docs/api/paddle/nn/InstanceNorm1D_cn.rst
  docs/api/paddle/nn/InstanceNorm2D_cn.rst
  docs/api/paddle/nn/InstanceNorm3D_cn.rst
  docs/api/paddle/nn/KLDivLoss_cn.rst
  docs/api/paddle/nn/L1Loss_cn.rst
  docs/api/paddle/nn/functional/instance_norm_cn.rst
  docs/api/paddle/nn/functional/l1_loss_cn.rst
  docs/api/paddle/nn/functional/layer_norm_cn.rst
Labels: contributor, status: proposed

#5502 修复paddle.bincount等API的文档
  docs/api/paddle/amp/decorate_cn.rst
  docs/api/paddle/bincount_cn.rst
  docs/api/paddle/incubate/softmax_mask_fuse_cn.rst
  docs/api/paddle/incubate/softmax_mask_fuse_upper_triangle_cn.rst
  docs/api/paddle/linalg/eigvalsh_cn.rst
  docs/api/paddle/linalg/triangular_solve_cn.rst
  docs/api/paddle/randint_like_cn.rst
  docs/api/paddle/signal/istft_cn.rst
  docs/api/paddle/static/ExecutionStrategy_cn.rst
Labels: contributor, status: proposed

#5503 fix doc max_unpool1d等多个文件
  docs/api/paddle/nn/MaxUnPool1D_cn.rst
  docs/api/paddle/nn/MaxUnPool2D_cn.rst
  docs/api/paddle/nn/MaxUnPool3D_cn.rst
  docs/api/paddle/nn/functional/max_unpool1d_cn.rst
  docs/api/paddle/nn/functional/max_unpool2d_cn.rst
  docs/api/paddle/nn/functional/max_unpool3d_cn.rst
  docs/api/paddle/nn/functional/unfold_cn.rst
Labels: contributor, status: proposed

#5508 按在线文档需求 61 ~ 70 修订部分 rst 文档
  docs/api/paddle/cast_cn.rst
  docs/api/paddle/io/DataLoader_cn.rst
  docs/api/paddle/log_cn.rst
  docs/api/paddle/static/Print_cn.rst
  docs/api/paddle/static/nn/data_norm_cn.rst
  docs/api/paddle/static/nn/sequence_slice_cn.rst
  docs/api/paddle/static/nn/sequence_unpad_cn.rst
Labels: contributor, status: proposed

#5504 Fix docs(91-100)
  docs/api/paddle/linspace_cn.rst
  docs/api/paddle/shard_index_cn.rst
  docs/api/paddle/static/auc_cn.rst
  docs/api/paddle/static/nn/sequence_enumerate_cn.rst
  docs/api/paddle/static/py_func_cn.rst
Labels: contributor, status: proposed

#5465 修复paddle.nn.functinal包和paddle.nn包下API文档
  docs/api/paddle/nn/Conv1DTranspose_cn.rst
  docs/api/paddle/nn/Conv1D_cn.rst
  docs/api/paddle/nn/Conv2DTranspose_cn.rst
  docs/api/paddle/nn/Conv2D_cn.rst
  docs/api/paddle/nn/Conv3D_cn.rst
  docs/api/paddle/nn/functional/conv1d_cn.rst
  docs/api/paddle/nn/functional/conv1d_transpose_cn.rst
  docs/api/paddle/nn/functional/conv2d_cn.rst
  docs/api/paddle/nn/functional/conv2d_transpose_cn.rst
  docs/api/paddle/nn/functional/conv3d_cn.rst
Labels: contributor, status: proposed

#5514 fix docs (#5143)
  docs/api/paddle/nn/BCEWithLogitsLoss_cn.rst
  docs/api/paddle/nn/BatchNorm1D_cn.rst
  docs/api/paddle/nn/BatchNorm2D_cn.rst
  docs/api/paddle/nn/BatchNorm3D_cn.rst
  docs/api/paddle/nn/BatchNorm_cn.rst
  docs/api/paddle/nn/BeamSearchDecoder_cn.rst
  docs/api/paddle/nn/functional/batch_norm_cn.rst
  docs/api/paddle/nn/functional/binary_cross_entropy_with_logits_cn.rst
Labels: contributor, status: proposed

#5454 [Tutorials] 用DQN强化学习算法玩“合成大西瓜”！
  docs/practices/reinforcement_learning/dqn_fruit_merger.ipynb
  docs/practices/reinforcement_learning/resources/illustrations/dataflow.jpg
  docs/practices/reinforcement_learning/resources/illustrations/put_aux_line.png
  docs/practices/reinforcement_learning/resources/images/01.png
  docs/practices/reinforcement_learning/resources/images/02.png
  docs/practices/reinforcement_learning/resources/images/03.png
  docs/practices/reinforcement_learning/resources/images/04.png
  docs/practices/reinforcement_learning/resources/images/05.png
  docs/practices/reinforcement_learning/resources/images/06.png
  docs/practices/reinforcement_learning/resources/images/07.png
  docs/practices/reinforcement_learning/resources/images/08.png
  docs/practices/reinforcement_learning/resources/images/09.png
  docs/practices/reinforcement_learning/resources/images/10.png
  docs/practices/reinforcement_learning/resources/images/11.png
Labels: contributor, status: proposed

#5494 修改paddle.uncubate.segment_mean括号
  docs/api/paddle/incubate/segment_mean_cn.rst
Labels: contributor, status: proposed

#5525 在文档中统一静态图模式与动态图模式的英文翻译
  docs/design/phi/design_cn.md
  docs/design/phi/design_en.md
  docs/eval/【Hackathon No.111】PR.md
  docs/guides/jit/basic_usage_cn.md
  docs/guides/jit/grammar_list_en.md
  docs/guides/jit/index_en.rst
  docs/guides/model_convert/load_old_format_model_cn.rst
  docs/release_note_en.md
Labels: contributor, status: proposed

#5523 在中文API文档中统一 Tensor 的描述
  docs/api/paddle/fluid/dygraph/Conv3DTranspose_cn.rst
  docs/api/paddle/fluid/dygraph/Conv3D_cn.rst
  docs/api/paddle/fluid/layers/sampling_id_cn.rst
  docs/api/paddle/scatter_cn.rst
Labels: contributor, status: proposed

#5512 Fix Chinese API docs 121-131 bugs
  docs/api/paddle/static/data_cn.rst
  docs/api/paddle/static/load_inference_model_cn.rst
  docs/api/paddle/static/nn/deform_conv2d_cn.rst
  docs/api/paddle/static/nn/fc_cn.rst
  docs/api/paddle/static/save_inference_model_cn.rst
  docs/api/paddle/static/serialize_persistables_cn.rst
  docs/api/paddle/static/serialize_program_cn.rst
  docs/api/paddle/sysconfig/get_lib_cn.rst
Labels: contributor, status: proposed

#5484 Updated pytorch_api_mapping_cn.md
  docs/guides/model_convert/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5526 修复 paddle.nn.Conv3DTranspose 等 API 的文档
  docs/api/paddle/fluid/dygraph/Conv3DTranspose_cn.rst
  docs/api/paddle/nn/CTCLoss_cn.rst
  docs/api/paddle/nn/Conv1DTranspose_cn.rst
  docs/api/paddle/nn/Conv2DTranspose_cn.rst
  docs/api/paddle/nn/Conv3DTranspose_cn.rst
  docs/api/paddle/nn/Dropout2D_cn.rst
  docs/api/paddle/nn/Dropout3D_cn.rst
  docs/api/paddle/nn/Dropout_cn.rst
  docs/api/paddle/nn/functional/conv2d_transpose_cn.rst
  docs/api/paddle/nn/functional/conv3d_transpose_cn.rst
  docs/api/paddle/nn/functional/ctc_loss_cn.rst
  docs/api/paddle/nn/functional/dropout2d_cn.rst
  docs/api/paddle/nn/functional/dropout3d_cn.rst
  docs/api/paddle/nn/functional/dropout_cn.rst
Labels: contributor, status: proposed

#5456 add convert docs
  docs/guides/model_convert/convert_from_older_versions/index_cn.rst
  docs/guides/model_convert/convert_from_older_versions/load_old_format_model_cn.rst
  docs/guides/model_convert/convert_from_older_versions/migration_cn.rst
  docs/guides/model_convert/convert_from_older_versions/paddle_api_mapping_cn.rst
  docs/guides/model_convert/convert_from_older_versions/update_cn.md
  docs/guides/model_convert/convert_from_pytorch/convert_bert_weights_cn.md
  docs/guides/model_convert/convert_from_pytorch/convert_net_structure_cn.md
  docs/guides/model_convert/convert_from_pytorch/cv_experience_cn.md
  docs/guides/model_convert/convert_from_pytorch/cv_quick_start_cn.md
  docs/guides/model_convert/convert_from_pytorch/index_cn.rst
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_guide_cn.md
  docs/guides/model_convert/convert_train_code/convert_bert_weights_cn.md
  docs/guides/model_convert/convert_train_code/convert_net_structure_cn.md
  docs/guides/model_convert/convert_train_code/cv_experience_cn.md
  docs/guides/model_convert/convert_train_code/cv_quick_start_cn.md
  docs/guides/model_convert/convert_train_code/index_cn.rst
  docs/guides/model_convert/images/backward.png
  docs/guides/model_convert/images/inverted_residual.png
  docs/guides/model_convert/images/memory_leak.png
  docs/guides/model_convert/images/metric.png
  docs/guides/model_convert/images/mobilenetv3.png
  docs/guides/model_convert/images/procedure.png
  docs/guides/model_convert/images/scenario.png
  docs/guides/model_convert/images/squeeze_excitation.png
  docs/guides/model_convert/index_cn.rst
  docs/guides/model_convert/paddle_2_x_cn.md
Labels: contributor, status: proposed

#5486 [phi::DenseTensor] delete LoDTensor in Zh files
  docs/api/paddle/autograd/saved_tensors_hooks_cn.rst
  docs/api/paddle/fluid/evaluator/DetectionMAP_cn.rst
  docs/api/paddle/fluid/layers/center_loss_cn.rst
  docs/api/paddle/fluid/layers/prroi_pool_cn.rst
  docs/api/paddle/fluid/layers/roi_perspective_transform_cn.rst
  docs/api/paddle/io/DataLoader_cn.rst
  docs/api/paddle/static/Executor_cn.rst
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/accuracy_cn.rst
  docs/api/paddle/static/nn/crf_decoding_cn.rst
  docs/api/paddle/static/nn/embedding_cn.rst
  docs/api/paddle/static/nn/row_conv_cn.rst
  docs/api/paddle/static/nn/sequence_concat_cn.rst
  docs/api/paddle/static/nn/sequence_conv_cn.rst
  docs/api/paddle/static/nn/sequence_enumerate_cn.rst
  docs/api/paddle/static/nn/sequence_expand_as_cn.rst
  docs/api/paddle/static/nn/sequence_expand_cn.rst
  docs/api/paddle/static/nn/sequence_first_step_cn.rst
  docs/api/paddle/static/nn/sequence_last_step_cn.rst
  docs/api/paddle/static/nn/sequence_pad_cn.rst
  docs/api/paddle/static/nn/sequence_pool_cn.rst
  docs/api/paddle/static/nn/sequence_reshape_cn.rst
  docs/api/paddle/static/nn/sequence_reverse_cn.rst
  docs/api/paddle/static/nn/sequence_scatter_cn.rst
  docs/api/paddle/static/nn/sequence_slice_cn.rst
  docs/api/paddle/static/nn/sequence_softmax_cn.rst
  docs/api/paddle/static/nn/sequence_unpad_cn.rst
  docs/api/paddle/static/nn/sparse_embedding_cn.rst
  docs/api/paddle/vision/ops/distribute_fpn_proposals_cn.rst
Labels: contributor, status: proposed

#5493 Update LSTM examples
  docs/practices/time_series/index_cn.rst
  docs/practices/time_series/stock_forecast.ipynb
  docs/practices/time_series/temperature_forecast.ipynb
Labels: contributor, status: proposed
