Repository PaddlePaddle/docs, pull requests merged in 2022-03, with the labels that each got.

#4299 fix clip cn docs
  docs/api/paddle/clip_cn.rst
Labels: user contribution

#4298 fix densenet docs file names
  docs/api/paddle/vision/models/densenet121_cn.rst
  docs/api/paddle/vision/models/densenet161_cn.rst
  docs/api/paddle/vision/models/densenet169_cn.rst
  docs/api/paddle/vision/models/densenet201_cn.rst
  docs/api/paddle/vision/models/densenet264_cn.rst
Labels: user contribution

#4314 [IPU] update paddle.static.IpuStrategy
  docs/api/paddle/static/IpuStrategy_cn.rst
Labels: contributor, status: proposed

#4318 修正 paddle.vision.transforms.ToTensor 文档中存在的部分问题
  docs/api/paddle/vision/transforms/ToTensor_cn.rst
Labels: contributor, status: proposed

#4320 fix paddle.stack cn docs
  docs/api/paddle/stack_cn.rst
Labels: contributor, status: proposed

#4321 fix paddle.tile cn docs
  docs/api/paddle/tile_cn.rst
Labels: contributor, status: proposed

#4328 Fix paddle.max cn docs
  docs/api/paddle/max_cn.rst
Labels: contributor, status: proposed

#4319 fix paddle.vision.transforms.Resize cn docs
  docs/api/paddle/vision/transforms/Resize_cn.rst
  docs/api/paddle/vision/transforms/resize_cn.rst
Labels: contributor, status: proposed

#4342 [IPU] add ipu intro doc
  docs/guides/09_hardware_support/hardware_info_cn.md
  docs/guides/09_hardware_support/index_cn.rst
  docs/guides/09_hardware_support/ipu_docs/index_cn.rst
  docs/guides/09_hardware_support/ipu_docs/paddle_install_cn.md
Labels: contributor, status: not progressed
