Repository PaddlePaddle/docs, pull requests merged in 2022-11, with the labels that each got.

#4806 【Hackathon No.6】add nan_to_num docs
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/nan_to_num_cn.rst
Labels: contributor

#5365 fix paddle.dist,paddle.roll,paddle.nonzero
  docs/api/paddle/dist_cn.rst
  docs/api/paddle/matmul_cn.rst
  docs/api/paddle/meshgrid_cn.rst
  docs/api/paddle/nonzero_cn.rst
  docs/api/paddle/roll_cn.rst
Labels: contributor, status: proposed

#5352 [CodeStyle][py2] Clean up all usages of `six` package and `__future__` imports in docs
  ci_scripts/Dockerfile
  ci_scripts/check_api_parameters.py
  ci_scripts/check_pr_approval.py
  docs/api/paddle/static/Program_cn.rst
  docs/api/paddle/static/nn/multi_box_head_cn.rst
  docs/api/paddle/static/py_func_cn.rst
  docs/guides/06_distributed_training/cluster_quick_start_en.rst
  docs/guides/model_convert/update_cn.md
  docs/guides/model_convert/update_en.md
  docs/install/FAQ.md
  docs/practices/gan/dcgan_face/dcgan_face.ipynb
Labels: contributor, status: proposed

#5210 Update case_analysis_cn.md
  docs/guides/jit/case_analysis_cn.md
Labels: contributor, status: not progressed

#5383 fix some word errors
  docs/guides/beginner/tensor_cn.md
Labels: contributor, status: proposed

#5340 docker GPU Api Update
  docs/install/docker/linux-docker.md
Labels: contributor, status: proposed

#5409 fix The first round of evaluation #47256 中文文档问题
  docs/api/paddle/dist_cn.rst
  docs/api/paddle/load_cn.rst
  docs/api/paddle/save_cn.rst
Labels: contributor, status: proposed

#5380 更改了参数说明，增加了默认值的含义
  docs/api/paddle/io/BatchSampler_cn.rst
  docs/api/paddle/io/ChainDataset_cn.rst
  docs/api/paddle/io/DistributedBatchSampler_cn.rst
  docs/api/paddle/io/IterableDataset_cn.rst
  docs/api/paddle/io/RandomSampler_cn.rst
Labels: contributor, status: proposed

#5413 [docs] [install] [docker] update English Documents , Supplementary notes in Chinese
  docs/install/docker/linux-docker.md
  docs/install/docker/linux-docker_en.md
Labels: contributor, status: proposed

#5418 fix typo errors
  docs/guides/advanced/autograd_cn.rst
Labels: contributor, status: proposed

#5385 fix some typo errors in “模型开发入门-数据集定义与加载”
  docs/guides/beginner/data_load_cn.ipynb
Labels: contributor, status: proposed

#5387 fix some doc errors
  docs/guides/advanced/layer_and_model_cn.md
Labels: contributor, status: proposed

#5443 [docs]修改图片标题居中问题，修复超链接错误问题，更新“飞桨框架内置模型”输出
  docs/guides/beginner/model_cn.ipynb
Labels: contributor, status: proposed

#5447 [docs] Modify error sample code
  docs/guides/beginner/model_save_load_cn.ipynb
Labels: contributor, status: proposed

#5446 [docs] Modify invalid links and update output
  docs/guides/beginner/train_eval_predict_cn.ipynb
Labels: contributor, status: proposed

#5429 修复paddle.nn.UpsamplingBilinear2D等文档
  docs/api/paddle/cumprod_cn.rst
  docs/api/paddle/device/cuda/stream_guard_cn.rst
  docs/api/paddle/linalg/svd_cn.rst
  docs/api/paddle/nn/UpsamplingBilinear2D_cn.rst
  docs/api/paddle/nn/UpsamplingNearest2D_cn.rst
  docs/api/paddle/nn/dynamic_decode_cn.rst
  docs/api/paddle/nn/functional/diag_embed_cn.rst
  docs/api/paddle/nn/functional/dice_loss_cn.rst
Labels: contributor, status: proposed

#5457 [docs]Fix image centering issue
  docs/guides/beginner/data_load_cn.ipynb
Labels: contributor, status: proposed

#5434 fix typo erros
  docs/api/paddle/vision/image_load_cn.rst
  docs/api/paddle/vision/set_image_backend_cn.rst
  docs/api/paddle/vision/transforms/BaseTransform_cn.rst
  docs/api/paddle/vision/transforms/BrightnessTransform_cn.rst
  docs/api/paddle/vision/transforms/CenterCrop_cn.rst
  docs/api/paddle/vision/transforms/ColorJitter_cn.rst
  docs/api/paddle/vision/transforms/Compose_cn.rst
  docs/api/paddle/vision/transforms/HueTransform_cn.rst
  docs/api/paddle/vision/transforms/RandomCrop_cn.rst
  docs/api/paddle/vision/transforms/RandomHorizontalFlip_cn.rst
  docs/api/paddle/vision/transforms/RandomResizedCrop_cn.rst
  docs/api/paddle/vision/transforms/RandomRotation_cn.rst
  docs/api/paddle/vision/transforms/SaturationTransform_cn.rst
  docs/api/paddle/vision/transforms/ToTensor_cn.rst
  docs/api/paddle/vision/transforms/adjust_hue_cn.rst
  docs/api/paddle/vision/transforms/center_crop_cn.rst
  docs/api/paddle/vision/transforms/rotate_cn.rst
  docs/api/paddle/vision/transforms/to_grayscale_cn.rst
  docs/guides/advanced/customize_cn.ipynb
  docs/guides/advanced/gradient_clip_cn.rst
  docs/guides/advanced/model_to_onnx_cn.md
Labels: contributor, status: proposed

#5441 [Docs]飞桨 API 文档体验提升计划：修复broadcasting说明的超链接失效问题
  docs/api/paddle/add_cn.rst
  docs/api/paddle/bitwise_and_cn.rst
  docs/api/paddle/bitwise_not_cn.rst
  docs/api/paddle/bitwise_or_cn.rst
  docs/api/paddle/bitwise_xor_cn.rst
  docs/api/paddle/broadcast_shape_cn.rst
  docs/api/paddle/broadcast_tensors_cn.rst
  docs/api/paddle/complex_cn.rst
  docs/api/paddle/distribution/Uniform_cn.rst
  docs/api/paddle/divide_cn.rst
  docs/api/paddle/floor_divide_cn.rst
  docs/api/paddle/fmax_cn.rst
  docs/api/paddle/fmin_cn.rst
  docs/api/paddle/gcd_cn.rst
  docs/api/paddle/heaviside_cn.rst
  docs/api/paddle/lcm_cn.rst
  docs/api/paddle/logical_and_cn.rst
  docs/api/paddle/logical_or_cn.rst
  docs/api/paddle/logical_xor_cn.rst
  docs/api/paddle/matmul_cn.rst
  docs/api/paddle/maximum_cn.rst
  docs/api/paddle/minimum_cn.rst
  docs/api/paddle/mod_cn.rst
  docs/api/paddle/multiply_cn.rst
  docs/api/paddle/nn/functional/dropout_cn.rst
  docs/api/paddle/remainder_cn.rst
  docs/api/paddle/subtract_cn.rst
Labels: contributor, status: proposed
