Repository PaddlePaddle/docs, pull requests merged in 2023-02, with the labels that each got.

#5602 Add to_tensor convert rule CN docs
  docs/api/paddle/to_tensor_cn.rst
Labels: contributor, status: proposed

#5593 Fix expressions format in nms
  docs/api/paddle/vision/ops/nms_cn.rst
Labels: contributor, status: proposed

#5592 Fix incorrect Format in linalg/lu_cn
  docs/api/paddle/linalg/lu_cn.rst
Labels: contributor, status: proposed

#5579 [docs] 将中英文文档中参数部分同步
  docs/api/paddle/nn/functional/sigmoid_focal_loss_cn.rst
Labels: contributor, status: proposed

#5384 [Tutorials-4] —3D image classification from CT scans.ipynb
  docs/practices/cv/[Tutorials-4] —3D image classification from CT scans.ipynb
Labels: contributor, status: proposed

#5391 upload transformer in eng_spa
  docs/practices/nlp/transformer_in_English-to-Spanish.ipynb
Labels: contributor, status: proposed

#5528 add ViT classification
  docs/practices/cv/image_classification_ViT.ipynb
  docs/practices/cv/sample_img/image_classification_ViT_1.jpg
  docs/practices/cv/sample_img/image_classification_ViT_2.jpg
  docs/practices/cv/sample_img/image_classification_ViT_3.png
Labels: contributor, status: proposed

#5614 [install] fix macos make fixed number of cores
  docs/install/compile/macos-compile.md
  docs/install/compile/macos-compile_en.md
Labels: contributor, status: proposed

#5565 Repair document content
  docs/api/paddle/nn/functional/glu_cn.rst
Labels: contributor, status: proposed

#5566 Modify document specification issues
  docs/api/paddle/nn/functional/grid_sample_cn.rst
Labels: contributor, status: proposed

#5575 修改文章表述
  docs/api/paddle/nn/functional/normalize_cn.rst
Labels: contributor, status: proposed

#5552 fix cn_rst format for LocalResponseNorm,functional.local_response_nor…
  docs/api/paddle/nn/LocalResponseNorm_cn.rst
  docs/api/paddle/nn/MarginRankingLoss_cn.rst
  docs/api/paddle/nn/functional/local_response_norm_cn.rst
Labels: contributor, status: proposed

#5564 [note]三篇相关API描述部分缺少句号
  docs/api/paddle/nn/MSELoss_cn.rst
  docs/api/paddle/nn/functional/leaky_relu_cn.rst
  docs/api/paddle/nn/functional/log_sigmoid_cn.rst
Labels: contributor, status: proposed

#5488 Add an example with AlphaZero
  docs/practices/reinforcement_learning/AlphaZero.ipynb
Labels: contributor, status: proposed

#5533 修改中文文档符号格式。
  docs/api/paddle/nn/LocalResponseNorm_cn.rst
  docs/api/paddle/nn/LogSoftmax_cn.rst
  docs/api/paddle/nn/MarginRankingLoss_cn.rst
  docs/api/paddle/nn/MaxPool1D_cn.rst
  docs/api/paddle/nn/MaxPool2D_cn.rst
  docs/api/paddle/nn/MaxPool3D_cn.rst
  docs/api/paddle/nn/functional/local_response_norm_cn.rst
  docs/api/paddle/nn/functional/log_softmax_cn.rst
  docs/api/paddle/nn/functional/max_pool1d_cn.rst
  docs/api/paddle/nn/functional/max_pool2d_cn.rst
  docs/api/paddle/nn/functional/max_pool3d_cn.rst
Labels: contributor, status: proposed

#5490 【Tutorial 36】GAMMA比赛多模态眼底图像数据集下基于EfficientNet和resnet构造fundus_img和oct_img的分类模型
  docs/practices/cv/glaucoma_classification.ipynb
  docs/practices/cv/sample_img/glaucoma_classification_1.png
  docs/practices/cv/sample_img/glaucoma_classification_2.png
  docs/practices/cv/sample_img/glaucoma_classification_3.png
  docs/practices/cv/sample_img/glaucoma_classification_4.png
  docs/practices/cv/sample_img/glaucoma_classification_5.png
  docs/practices/cv/sample_img/glaucoma_classification_6.png
Labels: contributor, status: proposed

#5641 add fp16 support to diag test=document_fix
  docs/api/paddle/diag_cn.rst
Labels: contributor, status: proposed

#5638 support float16 for pairwise_distance
  docs/api/paddle/nn/PairwiseDistance_cn.rst
  docs/api/paddle/nn/functional/pairwise_distance_cn.rst
Labels: contributor, status: proposed

#5629 Update argmin_cn.rst
  docs/api/paddle/argmin_cn.rst
Labels: contributor, status: proposed

#4963 Add INT8 OneDNN documentation
  docs/design/mkldnn/int8/PTQ/README.md
  docs/design/mkldnn/int8/QAT/C++.md
  docs/design/mkldnn/int8/QAT/Python.md
  docs/design/mkldnn/int8/QAT/README.md
  docs/design/mkldnn/int8/README.md
Labels: Intel, contributor, status: proposed

#5656 [fp16] Add fp16 support on some cn docs
  docs/api/paddle/broadcast_to_cn.rst
  docs/api/paddle/flatten_cn.rst
  docs/api/paddle/gather_nd_cn.rst
  docs/api/paddle/nansum_cn.rst
  docs/api/paddle/nn/functional/alpha_dropout_cn.rst
  docs/api/paddle/nn/functional/avg_pool3d_cn.rst
  docs/api/paddle/nn/functional/dropout2d_cn.rst
  docs/api/paddle/nn/functional/dropout_cn.rst
  docs/api/paddle/nn/functional/local_response_norm_cn.rst
  docs/api/paddle/nn/functional/temporal_shift_cn.rst
  docs/api/paddle/unbind_cn.rst
Labels: contributor, status: proposed

#5643 Update tile_cn.rst
  docs/api/paddle/tile_cn.rst
Labels: contributor, status: proposed

#5657 add float16 to equal_cn
  docs/api/paddle/equal_cn.rst
Labels: contributor

#5664 Modify the load link in model_save_load_cn.html
  docs/guides/beginner/model_save_load_cn.ipynb
Labels: contributor, status: proposed
