Repository PaddlePaddle/docs, pull requests merged in 2023-09, with the labels that each got.

#6154 add complex dtype for isclose
  docs/api/paddle/isclose_cn.rst
Labels: contributor, HappyOpenSource

#6157 Fix CN docs: api/paddle/optimizer/Optimizer_cn.html
  docs/api/paddle/optimizer/Optimizer_cn.rst
Labels: contributor

#6116 映射文档 No. 370
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.dropout1d.md
Labels: contributor, HappyOpenSource

#6124 映射文档 No.77-78
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6161 映射文档 torch.nn.functional.dropout2d/dropout3d
  docs/api/paddle/nn/functional/dropout2d_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.dropout2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.dropout3d.md
Labels: contributor, HappyOpenSource

#6160 Fix lu_factor_ex
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu_factor_ex.md
Labels: contributor, HappyOpenSource

#6145 update pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6162 [Change] remove_doctest_directives
  ci_scripts/doc-build-config/en/conf.py
Labels: contributor

#6173 [complex] add complex support for silu
  docs/api/paddle/nn/functional/silu_cn.rst
Labels: contributor

#6172 [Typo] fix silu
  docs/api/paddle/nn/functional/silu_cn.rst
Labels: contributor

#6174 映射文档 添加部分 inplace Tensor method api PART.02
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lcm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ldexp_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.le_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.less_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.less_equal_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lgamma_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log10_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log1p_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log2_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_and_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_not_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_or_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_xor_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logit_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lt_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nan_to_num_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ne_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.neg_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.negative_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.not_equal_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.polygamma_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pow_.md
Labels: contributor

#6122 Update Embedding_cn.rst
  docs/api/paddle/nn/Embedding_cn.rst
Labels: contributor

#6091 Change trigonometric and hyperbolic functions doc
  docs/api/paddle/acos_cn.rst
  docs/api/paddle/acosh_cn.rst
  docs/api/paddle/asin_cn.rst
  docs/api/paddle/asinh_cn.rst
  docs/api/paddle/atan_cn.rst
  docs/api/paddle/atanh_cn.rst
  docs/api/paddle/cos_cn.rst
  docs/api/paddle/cosh_cn.rst
  docs/api/paddle/sin_cn.rst
  docs/api/paddle/sinh_cn.rst
  docs/api/paddle/tan_cn.rst
Labels: contributor, status: proposed

#6136 [Fix] Fix example codes
  docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md
  docs/dev_guides/api_contributing_guides/images/zeros_python_api_doctest.png
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
Labels: contributor, status: proposed

#6177 add complex for logsigmoid
  docs/api/paddle/nn/functional/log_sigmoid_cn.rst
Labels: contributor

#6180 [complex] add complex support for fold
  docs/api/paddle/nn/functional/fold_cn.rst
Labels: contributor, HappyOpenSource Pro

#6178 add label_smoothing docs into cross_entropy_loss & CrossEntropyLoss
  docs/api/paddle/nn/CrossEntropyLoss_cn.rst
  docs/api/paddle/nn/functional/cross_entropy_cn.rst
Labels: contributor, HappyOpenSource

#6184 add complex for exp/expm1
  docs/api/paddle/exp_cn.rst
  docs/api/paddle/expm1_cn.rst
Labels: contributor, HappyOpenSource Pro

#6179 添加 enable_to_static 的中文文档
  docs/api/paddle/jit/Overview_cn.rst
  docs/api/paddle/jit/enable_to_static_cn.rst
Labels: contributor

#6166 Fix CN docs: api/paddle/metric/accuracy_cn.html
  docs/api/paddle/metric/accuracy_cn.rst
Labels: contributor, HappyOpenSource

#6167 add static_pylayer api cn docs
  docs/api/paddle/static/nn/static_pylayer_cn.rst
Labels: contributor

#6188 [fix]fix doc ref for md in paddle.onnx
  docs/api/paddle/onnx/export_cn.rst
Labels: contributor

#6191 [fix] update api_label in `docs/docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md`
  docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md
Labels: contributor, HappyOpenSource

#6189 映射文档 更新部分 inplace api 的映射错误
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cumprod_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.divide_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_put_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pow_.md
Labels: contributor

#6159 修复 paddle.argmax 等 API 的文档
  docs/api/paddle/argmax_cn.rst
  docs/api/paddle/create_parameter_cn.rst
  docs/api/paddle/nn/Transformer_cn.rst
  docs/api/paddle/optimizer/lr/CosineAnnealingDecay_cn.rst
Labels: contributor, HappyOpenSource

#6190 映射文档 添加部分 inplace api PART.03
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addmm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.div_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.i0_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sigmoid_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sub_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.true_divide_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.trunc_.md
Labels: contributor

#6199 fix cross_entropy_cn.rst
  docs/api/paddle/nn/functional/cross_entropy_cn.rst
Labels: contributor

#6195 [Docathon] replace deprecated fluid unittest path with new path
  docs/dev_guides/amp_precision/amp_test_dev_guide_cn.md
  docs/dev_guides/api_contributing_guides/api_accpetance_criteria_cn.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_en.md
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
  docs/dev_guides/code_contributing_path_cn.md
  docs/dev_guides/git_guides/local_dev_guide_cn.md
  docs/dev_guides/git_guides/local_dev_guide_en.md
  docs/dev_guides/sugon/paddle_c86_fix_guides_cn.md
  docs/guides/06_distributed_training/cluster_quick_start_fl_ps_cn.rst
  docs/guides/flags/check_nan_inf_cn.md
  docs/guides/flags/check_nan_inf_en.md
Labels: contributor, HappyOpenSource

#6202 add complex for sigmoid
  docs/api/paddle/nn/Sigmoid_cn.rst
Labels: contributor, HappyOpenSource Pro

#6204 add release/llm2.5 install packages
  docs/install/Tables.md
  docs/install/Tables_en.md
Labels: contributor

#6197 修复 paddle\add 等 API 的文档
  docs/api/paddle/add_cn.rst
  docs/api/paddle/full_cn.rst
  docs/api/paddle/nn/Conv2DTranspose_cn.rst
  docs/api/paddle/nn/initializer/Constant_cn.rst
  docs/api/paddle/rand_cn.rst
  docs/api/paddle/shape_cn.rst
  docs/api/paddle/static/InputSpec_cn.rst
  docs/api/paddle/static/load_inference_model_cn.rst
  docs/api/paddle/vision/transforms/Normalize__upper_cn.rst
Labels: contributor, HappyOpenSource

#5753 [docs][get_world_size] add warning
  docs/api/paddle/distributed/get_world_size_cn.rst
Labels: contributor

#6211 [Docathon] Add No.60~No.61 API CN Doc
  docs/api/paddle/incubate/nn/functional/fused_layer_norm_cn.rst
  docs/api/paddle/incubate/nn/functional/fused_rms_norm_cn.rst
Labels: contributor, HappyOpenSource

#6216 Modify the name of the release/llm_2.5 installation package
  docs/install/Tables.md
  docs/install/Tables_en.md
Labels: contributor
