Repository PaddlePaddle/docs, pull requests merged in 2023-03, with the labels that each got.

#5668 [fp16] suppot fp16 in std,var,tensordot,diagflat
  docs/api/paddle/diagflat_cn.rst
  docs/api/paddle/std_cn.rst
  docs/api/paddle/tensordot_cn.rst
  docs/api/paddle/var_cn.rst
Labels: contributor, status: proposed

#5676 add float16 to pixel_shuffle_cn
  docs/api/paddle/nn/functional/pixel_shuffle_cn.rst
Labels: contributor, status: proposed

#5669 add float16 to less_than_cn
  docs/api/paddle/less_than_cn.rst
Labels: contributor, status: proposed

#5671 add float16 to greater_equal_cn
  docs/api/paddle/greater_equal_cn.rst
Labels: contributor, status: proposed

#5674 add float16 to less_equal_cn
  docs/api/paddle/less_equal_cn.rst
Labels: contributor, status: proposed

#5672 add float16 to greater_than
  docs/api/paddle/greater_than_cn.rst
Labels: contributor, status: proposed

#5678 fix all docs bugs
  docs/api/paddle/static/create_global_var_cn.rst
Labels: contributor, status: proposed

#5666 Update vector_to_parameters_cn.rst
  docs/api/paddle/nn/utils/vector_to_parameters_cn.rst
Labels: contributor, status: proposed

#5659 fix fp16 for log/log1p/logsumexp
  docs/api/paddle/log1p_cn.rst
  docs/api/paddle/log_cn.rst
  docs/api/paddle/logsumexp_cn.rst
Labels: contributor, status: proposed

#5658 support float16 for argsort
  docs/api/paddle/argsort_cn.rst
  docs/api/paddle/fluid/layers/argsort_cn.rst
Labels: contributor, status: proposed

#5660 PaddlePaddle Hackathon 第四期】No.1：为 Paddle 新增 finfo API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/finfo_cn.rst
Labels: contributor

#5683 修改greater_equal的支持fp16的文档
  docs/api/paddle/greater_equal_cn.rst
Labels: contributor, status: proposed

#5627 统一中英文档的参数数字展现形式
  docs/api/paddle/nn/RReLU_cn.rst
Labels: contributor

#5686 【使用指南】Delete redundant parentheses to patch PR#5664
  docs/guides/beginner/model_save_load_cn.ipynb
Labels: contributor, status: proposed

#5667 Text1
  docs/api/paddle/distributed/is_initialized_cn.rst
  docs/api/paddle/nn/utils/remove_weight_norm_cn.rst
  docs/api/paddle/nn/utils/weight_norm_cn.rst
Labels: contributor, status: not progressed

#5605 修复《使用指南》的“数据集定义与加载”1.2章节示例代码缺失的导入
  docs/guides/beginner/data_load_cn.ipynb
Labels: contributor, status: proposed

#5665 Update Callback_cn.rst
  docs/api/paddle/callbacks/Callback_cn.rst
Labels: contributor, status: not progressed

#5613 Update install_NGC_PaddlePaddle_en.rst
  docs/install/install_NGC_PaddlePaddle_en.rst
Labels: contributor, status: proposed

#5688 update allclose, isclose
  docs/api/paddle/allclose_cn.rst
  docs/api/paddle/isclose_cn.rst
Labels: contributor, status: proposed

#5694 Supplementary directory structure
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/init/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/.gitkeep
Labels: contributor, status: proposed

#5698 update class_center_sample_cn.rst
  docs/api/paddle/nn/functional/class_center_sample_cn.rst
Labels: contributor, status: proposed

#5721 fix transformer eng_to_spa
  docs/practices/nlp/transformer_in_English-to-Spanish.ipynb
Labels: contributor, status: proposed

#5642 PaddlePaddle Hackathon 4 No.53】：为 Paddle label_smooth 支持 float16 数据类型
  docs/api/paddle/fluid/layers/label_smooth_cn.rst
  docs/api/paddle/nn/functional/label_smooth_cn.rst
Labels: contributor, status: proposed

#5689 文档修复
  docs/api/paddle/nn/RNN_cn.rst
  docs/api/paddle/nn/SimpleRNNCell_cn.rst
  docs/api/paddle/nn/SimpleRNN_cn.rst
Labels: contributor, status: proposed

#5708 update cross_cn.rst
  docs/api/paddle/cross_cn.rst
Labels: contributor, status: proposed

#5695 fix docs 第七轮第一组
  docs/api/paddle/nn/ClipGradByGlobalNorm_cn.rst
  docs/api/paddle/nn/ClipGradByValue_cn.rst
  docs/api/paddle/nn/GRU_cn.rst
Labels: contributor, status: proposed

#5719 补充empty API 中文注释中的数据类型
  docs/api/paddle/empty_cn.rst
Labels: contributor, status: proposed

#5717 [Tutorials-05] —PASCAL 3D+数据集上使用 PointNet 实现5类点云的分割
  docs/practices/cv/pc_segmentation.ipynb
Labels: contributor, status: proposed

#5724 fix vit imgs
  docs/practices/cv/image_classification_ViT.ipynb
Labels: contributor, status: proposed

#5707 update gumbel_softmax_cn.rst
  docs/api/paddle/nn/functional/gumbel_softmax_cn.rst
Labels: contributor, status: proposed

#5693 add note for ClipGradGlobalNorm, ClipGradByNorm, ClipGradByValue
  docs/api/paddle/ParamAttr_cn.rst
  docs/api/paddle/nn/ClipGradByGlobalNorm_cn.rst
  docs/api/paddle/nn/ClipGradByNorm_cn.rst
  docs/api/paddle/nn/ClipGradByValue_cn.rst
Labels: contributor, status: proposed

#5726 【Tutorial 35】glaucoma_classification
  docs/practices/cv/glaucoma_classification.ipynb
Labels: contributor, status: proposed

#5731 Add pytorch_api_mapping_format_cn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/pytorch_api_mapping_format_cn.md
Labels: contributor, status: proposed

#5732 [docs][api] fix gradients copy code
  docs/api/paddle/static/gradients_cn.rst
Labels: contributor, status: proposed

#5639 added paddle.polar docs
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/polar_cn.rst
Labels: contributor, status: proposed

#5610 Update index_en.rst
  docs/install/index_en.rst
Labels: contributor, status: proposed

#5699 映射文档 No. 1
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.grid_sample.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.nll_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.pad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.pixel_shuffle.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.pixel_unshuffle.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.smooth_l1_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.soft_margin_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.triplet_margin_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.triplet_margin_with_distance_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.upsample.md
Labels: contributor, status: proposed

#5702 映射文档 No. 2
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/.gitkeep
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.T.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.device.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.imag.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_leaf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_sparse.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ndim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.real.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.shape.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.affine_grid.md
Labels: contributor, status: proposed

#5749 Update legacy links to latest repo
  docs/design/algorithm/parameter_average.md
  docs/design/concepts/block.md
  docs/design/concepts/executor.md
  docs/design/concepts/program.md
  docs/design/data_type/float16.md
  docs/design/dist_train/distributed_architecture.md
  docs/design/dist_train/distributed_lookup_table_design.md
  docs/design/dist_train/parameter_server.md
  docs/design/dynamic_rnn/rnn.md
  docs/design/modules/python_api.md
  docs/design/modules/regularization.md
  docs/design/motivation/fluid.md
  docs/design/motivation/fluid_compiler.md
  docs/design/motivation/refactorization.md
  docs/design/multi_devices/kernel_hint_design.md
  docs/design/network/sequence_decoder.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_notes_en.md
Labels: contributor

#5735 support float16 for diff
  docs/api/paddle/diff_cn.rst
Labels: contributor

#5690 [Feature] update GroupNorm\LayerNorm\backward\contiguous\copy_\expand\fill_\int\float\is_contiguous\masked_fill\sigmoid\unique\binary_cross_entropy_with_logits\interpolate\l1_loss\max_pool2d\meshgrid\sigmoid
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.copy_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.expand.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.float.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.int.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.requires_grad_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.barrier.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.init_process_group.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.binary_cross_entropy_with_logits.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.l1_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.maxpool_2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.GroupNorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LayerNorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.meshgrid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5739 update logical_xxx_cn.rst float16 supported.
  docs/api/paddle/logical_and_cn.rst
  docs/api/paddle/logical_not_cn.rst
  docs/api/paddle/logical_or_cn.rst
  docs/api/paddle/logical_xor_cn.rst
Labels: contributor

#5685 【Hackathon 4th 】新增 trapezoid 和 cumulative_trapezoid doc
  docs/api/api_label
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/cumulative_trapezoid_cn.rst
  docs/api/paddle/trapezoid_cn.rst
Labels: contributor, status: proposed

#5759 Update L2Decay_cn.rst
  docs/api/paddle/regularizer/L2Decay_cn.rst
Labels: contributor, status: proposed

#5681 【PaddlePaddle Hackathon 4 No.23】新增 API vander
  docs/api/api_label
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/vander_cn.rst
Labels: contributor, status: proposed
