Repository PaddlePaddle/docs, pull requests merged in 2023-04, with the labels that each got.

#5705 【Hackathon 4th No.24】为 Paddle 新增 paddle.sparse.is_nan 稀疏 API
  docs/api/paddle/sparse/isnan_cn.rst
Labels: contributor

#5756 映射文档 No.24
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.var.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.where.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.zero_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.Event.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.current_device.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.current_stream.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.device_count.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_capability.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_properties.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_device.md
Labels: contributor, status: proposed

#5751 映射文档 No. 22
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.atanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.take.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tan.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tanh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.to_sparse.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tolist.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.topk.md
Labels: contributor

#5727 映射文档 No 7~10
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arccosh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cpu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cross.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cumprod.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cumsum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.deg2rad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.det.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.detach.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diag.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagflat.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagonal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diff.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.digamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dist.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.element_size.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.eq.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.equal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.erf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.erfinv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.erfinv_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.exp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.exp_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.expand_as.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fill_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fill_diagonal_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fix.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.flatten.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.flip.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fliplr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.flipud.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fmin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.frac.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logcumsumexp.md
Labels: contributor, status: not progressed

#5781 update convert api list
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tile.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5675 Update PoissonNLLLoss document. ;test=docs_preview
  docs/api/api_label
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/PoissonNLLLoss_cn.rst
  docs/api/paddle/nn/functional/poisson_nll_loss_cn.rst
Labels: contributor, status: not progressed

#5733 映射文档 No 20
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arcsinh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.asinh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.rsqrt.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.rsqrt_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.select.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sinh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.slogdet.md
Labels: contributor, status: proposed

#5742 映射文档 No. 18
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanquantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.negative.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nelement.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nonzero.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.numel.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.numpy.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.outer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pin_memory.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pow.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.prod.md
Labels: contributor

#5794 【Hackathon 4th No.13】为 Paddle 新增 Bernoulli API -- Bernoulli doc
  docs/api/paddle/distribution/Bernoulli_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
Labels: contributor, status: proposed

#5623 补充GaussianNLLLoss中文文档。;test=docs_preview
  docs/api/api_label
  docs/api/paddle/nn/GaussianNLLLoss_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/gaussian_nll_loss_cn.rst
Labels: contributor

#5797 Update diag_cn.rst
  docs/api/paddle/diag_cn.rst
Labels: contributor, status: proposed

#5795 update convert list
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.det.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5778 映射文档 No.17
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mul.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mul_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multiply.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multiply_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nansum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ndimension.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ne.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.neg.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.not_equal.md
Labels: contributor, status: proposed

#5769 fix the usage of torch.Tensor.where
  docs/api/paddle/Tensor_cn.rst
Labels: contributor, status: proposed

#5704 PaddlePaddle Hackathon 4 No.49】：为 Paddle bce_loss 支持 float16 数据类型
  docs/api/paddle/nn/functional/binary_cross_entropy_cn.rst
Labels: contributor, status: proposed

#5802 Fix some cn docs
  docs/api/paddle/nn/HSigmoidLoss_cn.rst
  docs/api/paddle/nn/LSTMCell_cn.rst
  docs/api/paddle/nn/LSTM_cn.rst
  docs/api/paddle/nn/LayerDict_cn.rst
Labels: contributor, status: proposed

#5800 Five files changed.
  docs/api/paddle/is_floating_point_cn.rst
  docs/api/paddle/is_grad_enabled_cn.rst
  docs/api/paddle/logit_cn.rst
  docs/api/paddle/mode_cn.rst
  docs/api/paddle/nanmedian_cn.rst
Labels: contributor, status: proposed

#5747 映射文档 No. 14
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lgamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log10.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log1p.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logdet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_and.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_not.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logical_or.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.logsumexp.md
Labels: contributor

#5808 映射文档 No.25
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.empty_cache.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.manual_seed.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.max_memory_allocated.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.max_memory_reserved.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.memory_allocated.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.memory_reserved.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.synchronize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.ReduceOp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.kl.kl_divergence.md
Labels: contributor, status: proposed

#5799 映射文档 No. 26
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.kl.register_kl.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.fftshift.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.ifftshift.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/init/torch.nn.init.calculate_gain.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.svd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.random.manual_seed.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.addmm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.mm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.softmax.md
Labels: contributor, status: proposed

#5812 update api convert list
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.swapdims.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5798 映射文档 No. 23
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.trace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tril.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.true_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.trunc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unbind.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.uniform_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique_consecutive.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unsqueeze.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unsqueeze_.md
Labels: contributor, status: proposed

#5805 【Hackathon4】No5.nextafter add Chinese doc files
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/nextafter_cn.rst
Labels: contributor, status: proposed

#5821 映射文档 No. 27
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.take_along_dim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_power.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.dsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.expm1.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.CUDAExtension.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.CppExtension.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.load.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.random_split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.dlpack.from_dlpack.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.dlpack.to_dlpack.md
Labels: contributor, status: proposed
