Repository PaddlePaddle/docs, pull requests merged in 2023-07, with the labels that each got.

#5962 [Change]修改目前 Paddle docs 的代码检查方式
  ci_scripts/chinese_samplecode_processor.py
  docs/api/gen_doc.py
Labels: contributor, status: proposed

#5993 add the bfloat16 for lerp
  docs/api/paddle/lerp_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5998 fix doc for cummax/cummin
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/cummax_cn.rst
  docs/api/paddle/cummin_cn.rst
Labels: contributor, status: proposed

#5978 映射文档 No.234/236/237
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.ChainDataset.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.Subset.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.TensorDataset.md
Labels: contributor, status: proposed, HappyOpenSource

#5994 Fix doc bugs of api convert
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mul.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mul_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multiply.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multiply_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ne.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.not_equal.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5933 映射文档 No.50, 80
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_rng_state_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_rng_state_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.ComposeTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Hardswish.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Hardtanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.jit.load.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.onnx.export.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.profiler.profile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.profiler.schedule.md
Labels: contributor, status: proposed, HappyOpenSource

#5955 映射文档 No.16/17/18/19
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cummin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.searchsorted.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.vander.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#5951 映射文档 No.240
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.random_split.md
Labels: contributor, status: proposed, HappyOpenSource

#5965 修改COPY-FROM No. 19 distribution
  docs/api/paddle/distribution/Bernoulli_cn.rst
  docs/api/paddle/distribution/Categorical_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5964 修改COPY-FROM No. 18 static
  docs/api/paddle/static/InputSpec_cn.rst
  docs/api/paddle/static/Program_cn.rst
  docs/api/paddle/static/Variable_cn.rst
  docs/api/paddle/static/nn/cond_cn.rst
  docs/api/paddle/static/program_guard_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5961 修改COPY-FROM No.15 regularizer
  docs/api/paddle/regularizer/L1Decay_cn.rst
  docs/api/paddle/regularizer/L2Decay_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5966 映射文档 No.120
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.device.md
Labels: contributor, status: proposed, HappyOpenSource

#5971 修改 COPY-FROM No.6 metric
  docs/api/paddle/metric/Accuracy__upper_cn.rst
  docs/api/paddle/metric/Auc_cn.rst
  docs/api/paddle/metric/Metric_cn.rst
  docs/api/paddle/metric/Precision_cn.rst
  docs/api/paddle/metric/Recall_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5984 修改COPY-FROM No. 3 autograd
  docs/api/paddle/autograd/PyLayerContext_cn.rst
  docs/api/paddle/autograd/PyLayer_cn.rst
  docs/api/paddle/autograd/saved_tensors_hooks_cn.rst
Labels: contributor, HappyOpenSource

#5983 修改COPY-FROM No. 2 jit
  docs/api/paddle/jit/Overview_cn.rst
  docs/api/paddle/jit/ProgramTranslator_cn.rst
  docs/api/paddle/jit/TranslatedLayer_cn.rst
  docs/api/paddle/jit/load_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5973 映射文档 No.48 torch.nn.RNNBase mapping
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.RNNBase.md
Labels: contributor, status: proposed, HappyOpenSource

#6008 映射文档 No. 205/206
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6001 修改 COPY-FROM No.12 io
  docs/api/paddle/io/DataLoader_cn.rst
  docs/api/paddle/io/DistributedBatchSampler_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6018 Rename troch.nn.Mish.md to torch.nn.Mish.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Mish.md
Labels: contributor, status: proposed

#6019 Delete torxh.nn.Module.add_module.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torxh.nn.Module.add_module.md
Labels: contributor, status: proposed

#6013 Add qat_init API into fleet doc
  docs/api/paddle/distributed/fleet/Fleet_cn.rst
Labels: contributor, status: proposed

#6007 映射文档 No. 5/6/7/8/9/10
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.i0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.nextafter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.polygamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.quantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.stft.md
Labels: contributor, status: proposed, HappyOpenSource

#6022 Update torch.special.psi.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.psi.md
Labels: contributor, status: proposed

#6032 Fix strip ps
  ci_scripts/chinese_samplecode_processor.py
  docs/api/gen_doc.py
Labels: contributor, status: proposed

#5997 Repair Model COPY-FROM wrong link
  docs/api/paddle/Model_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6003 修改COPY-FROM No.14 incubate
  docs/api/paddle/incubate/LookAhead_cn.rst
  docs/api/paddle/incubate/optimizer/functional/minimize_bfgs_cn.rst
  docs/api/paddle/incubate/optimizer/functional/minimize_lbfgs_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6009 映射文档 No. 388-401
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.bfloat16.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.cpu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.cuda.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.double.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.float.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.half.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.to.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.type.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.xpu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.zero_grad.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#5960 修改COPY-FROM No. 1 others
  docs/api/paddle/LazyGuard_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/grad_cn.rst
  docs/api/paddle/scatter_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6014 映射文档 No. 352/353
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6017 映射文档 No. 380/381
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6020 映射文档 No. 271/273/280/283/297/298/301/325/337/339-348
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6025 映射文档 No. 193/194/195
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.SoftmaxTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.StackTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.StickBreakingTransform.md
Labels: contributor, status: proposed, HappyOpenSource

#6026 映射文档 No. 263/264
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.erfinv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.logit.md
Labels: contributor, status: proposed, HappyOpenSource

#6005 修改COPY-FROM No.4 optimizer
  docs/api/paddle/optimizer/Adadelta_cn.rst
  docs/api/paddle/optimizer/AdamW_cn.rst
  docs/api/paddle/optimizer/Adam_cn.rst
  docs/api/paddle/optimizer/Adamax_cn.rst
  docs/api/paddle/optimizer/Lamb_cn.rst
  docs/api/paddle/optimizer/Momentum_cn.rst
  docs/api/paddle/optimizer/Optimizer_cn.rst
  docs/api/paddle/optimizer/RMSProp_cn.rst
  docs/api/paddle/optimizer/SGD_cn.rst
  docs/api/paddle/optimizer/lr/LRScheduler_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6023 映射文档 No. 322/323/333
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.corrcoef.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.polygamma.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#5987 映射文档 No.76
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cholesky_solve.md
Labels: contributor, status: proposed, HappyOpenSource

#6021 映射文档 No. 299/305/316/317/319
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cumulative_trapezoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.histogram.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.i0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.i1.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.i1e.md
Labels: contributor, status: proposed, HappyOpenSource

#6004 修改COPY-FROM No.13 distributed
  docs/api/paddle/distributed/QueueDataset_cn.rst
  docs/api/paddle/distributed/fleet/PaddleCloudRoleMaker_cn.rst
  docs/api/paddle/distributed/fleet/UserDefinedRoleMaker_cn.rst
  docs/api/paddle/distributed/fleet/UtilBase_cn.rst
  docs/api/paddle/distributed/fleet/utils/HDFSClient_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5963 Bug fix
  docs/api/paddle/nn/functional/multi_label_soft_margin_loss_cn.rst
  docs/api/paddle/nn/functional/poisson_nll_loss_cn.rst
Labels: contributor, status: proposed

#6044 映射文档 No. 165-184
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.bernoulli.Bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.categorical.Categorical.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.cauchy.Cauchy.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.dirichlet.Dirichlet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.distribution.Distribution.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.exp_family.ExponentialFamily.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.geometric.Geometric.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.gumbel.Gumbel.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.independent.Independent.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.laplace.Laplace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.log_normal.LogNormal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.multinomial.Multinomial.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.normal.Normal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transformed_distribution.TransformedDistribution.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.Transform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.uniform.Uniform.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6048 映射文档 No. 338
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.asarray.md
Labels: contributor, HappyOpenSource

#6038 映射文档 No. 378
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.vander.md
Labels: contributor, status: proposed, HappyOpenSource

#6045 映射文档 No. 221-226
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.get_worker_info.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.rpc_async.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.rpc_sync.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.shutdown.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6047 映射文档 No. 253/261/279
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.gaussian_nll_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.profiler.profile.export_chrome_trace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.i0e.md
Labels: contributor, HappyOpenSource

#6050 映射文档 No. 227
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.random.initial_seed.md
Labels: contributor, HappyOpenSource

#6052 映射文档 No. 274
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6054 映射文档 No. 86/244
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_signed.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.testing.assert_close.md
Labels: contributor, HappyOpenSource

#6055 映射文档 No.53 `torch.nn.PoissonNLLLoss`
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.PoissonNLLLoss.md
Labels: contributor, HappyOpenSource

#6057 映射文档 No.62 `torch.nn.MultiMarginLoss`
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MultiMarginLoss.md
Labels: contributor, HappyOpenSource

#6060 映射文档 No. 159-163/196/197/232-233
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6061 映射文档 No. 309
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.trapezoid.md
Labels: contributor, HappyOpenSource

#6062 映射文档 No. 121/122/123/124
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.stream.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6046 映射文档 No. 154/156/157
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.gather_object.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.reduce_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.scatter_object_list.md
Labels: contributor, HappyOpenSource

#6065 fix link error in docs
  docs/dev_guides/op_optimization/op_optimization_method_introduction_cn.md
Labels: contributor

#6066 Fix doc
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.chunk.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#6072 [Change] remove doctest directives from sphinx conf
  ci_scripts/doc-build-config/en/conf.py
  docs/api/copy_codes_from_en_doc.py
Labels: contributor, status: proposed

#6074 Update group_norm_cn.rst
  docs/api/paddle/optimizer/lr/LinearWarmup_cn.rst
  docs/api/paddle/static/nn/group_norm_cn.rst
Labels: contributor, status: proposed

#6016 映射文档 No. 360
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6028 映射文档 No. 258/285
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.huber_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.HuberLoss.md
Labels: contributor, status: proposed, HappyOpenSource

#6056 映射文档 No.54 `torch.nn.GaussianNLLLoss`
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.GaussianNLLLoss.md
Labels: contributor, HappyOpenSource

#6070 PATCH 映射文档 No.53 `torch.nn.PoissonNLLLoss`
  docs/api/paddle/nn/PoissonNLLLoss_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.PoissonNLLLoss.md
Labels: contributor, status: proposed

#6077 Modify the documentation description of poisson
  docs/api/paddle/poisson_cn.rst
Labels: contributor, status: proposed

#6073 映射文档 No.80
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource
