Repository PaddlePaddle/docs, pull requests merged in 2023-10, with the labels that each got.

#6218 [Add] add solo directive
  docs/dev_guides/style_guide_and_references/code_example_writing_specification_cn.md
Labels: contributor

#6223 refine doc for Geometric distribution
  docs/api/paddle/distribution/Geometric_cn.rst
Labels: contributor

#6214 [Docathon] Fix zh api_label
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/guides/advanced/gradient_clip_cn.rst
Labels: contributor, HappyOpenSource

#6222 [Docathon] Add `paddle.incubate.ampdecorate` and `paddle.incubate.amp.prune_model` API CN Doc
  docs/api/paddle/incubate/asp/decorate_cn.rst
  docs/api/paddle/incubate/asp/prune_model_cn.rst
Labels: contributor, HappyOpenSource

#6227 add complex for softplus
  docs/api/paddle/nn/Softplus_cn.rst
Labels: contributor, HappyOpenSource

#6219 【Hackathon 5 No.21】 Add doc of paddle.optimizer.lr.LinearLR
  docs/api/paddle/optimizer/lr/LRScheduler_cn.rst
  docs/api/paddle/optimizer/lr/LinearLR_cn.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler_en.rst
Labels: contributor, PaddlePaddle Hackathon

#6224 [Docathon] Add NO.64-67 API CN Doc
  docs/api/paddle/incubate/asp/add_supported_layer_cn.rst
  docs/api/paddle/incubate/asp/calculate_density_cn.rst
  docs/api/paddle/incubate/asp/reset_excluded_layers_cn.rst
  docs/api/paddle/incubate/asp/set_excluded_layers_cn.rst
Labels: contributor, HappyOpenSource

#6221 [Docathon] fix cn api_label extra
  docs/api/paddle/distribution/Overview_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6229 修复docs\api\paddle\Tenso 等 API 的文档
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/bmm_cn.rst
  docs/api/paddle/distributed/fleet/Fleet_cn.rst
  docs/api/paddle/metric/Recall_cn.rst
  docs/api/paddle/nn/LSTM_cn.rst
  docs/api/paddle/nn/functional/grid_sample_cn.rst
Labels: contributor, HappyOpenSource

#6228 映射文档 添加部分 inplace api PART.04
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.abs_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.acos_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.acosh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arccos_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arccosh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arcsin_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arcsinh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctan_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctanh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.asin_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.asinh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.atan_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.atanh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cos_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cosh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.erf_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.expm1_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multiply_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.renorm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sin_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sinh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.square_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tan_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tanh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tril_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triu_.md
Labels: contributor

#6212 【Hackthon 5 No.42】 为Paddle代码转换工具新增API转换规则 (第1组 编号1-20)
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.as_strided.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cummax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cummin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.i0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_put.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unfold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.view.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.view_as.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.as_strided.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.clamp_max.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cummax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.is_pinned.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.nanquantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/pytorch_api_mapping_format_cn.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6230 【Hackathon No.8】add docs for api hypot & hypot_
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/hypot__cn.rst
  docs/api/paddle/hypot_cn.rst
Labels: contributor

#6226 [ci] 添加监测中文 apilabel 的 ci
  ci_scripts/check_api_cn.sh
  ci_scripts/check_api_label_cn.py
  ci_scripts/check_api_label_cn.sh
  ci_scripts/ci_start.sh
Labels: contributor

#6238 [CodeStyle] upgrade `black` in `.pre-commit-config.yaml`
  .pre-commit-config.yaml
  ci_scripts/CAPItools/utils_helper.py
  ci_scripts/check_api_label_cn.py
  docs/api/gen_alias_api.py
Labels: contributor

#6240 [CodeStyle] upgrade `Lucas-C/pre-commit-hooks` in `.pre-commit-config.yaml`
  .github/ISSUE_TEMPLATE/3_eval_distributed_DataParallel_docs-issue.yml
  .github/ISSUE_TEMPLATE/4_eval_distributed_PS_docs-issue.yml
  .pre-commit-config.yaml
  ci_scripts/gendoc.sh
  docs/design/mkldnn/acquire_api/scripts/acquire.dot
  docs/eval/【Hackathon No.111】PR.md
  docs/eval/【Hackathon No.69】PR.md
  docs/guides/cinn/basic_operator_cn.md
  docs/practices/reinforcement_learning/AlphaZero.ipynb
  docs/templates/layout.html
Labels: contributor, HappyOpenSource

#6237 [ci]修复中文 api_label 检查的若干问题
  ci_scripts/check_api_label_cn.py
Labels: contributor, HappyOpenSource

#6239 [CodeStyle] upgrade `pre-commit/pre-commit-hooks` in `.pre-commit-config.yaml`
  .github/ISSUE_TEMPLATE/1_documentation-issue.yml
  .github/ISSUE_TEMPLATE/2_eval-issue.yml
  .github/ISSUE_TEMPLATE/3_eval_distributed_DataParallel_docs-issue.yml
  .github/ISSUE_TEMPLATE/4_eval_distributed_PS_docs-issue.yml
  .gitignore
  .pre-commit-config.yaml
  .pre-commit-hooks/convert_markdown_into_ipynb.sh
  ci_scripts/CAPItools/requirements.txt
  ci_scripts/api_white_list.txt
  ci_scripts/check_api_cn.sh
  ci_scripts/check_api_docs_en.sh
  ci_scripts/check_api_label_cn.sh
  ci_scripts/check_api_parameters.sh
  ci_scripts/checkapproval.sh
  ci_scripts/ci_start.sh
  ci_scripts/ci_start_en.sh
  ci_scripts/gendoc.sh
  ci_scripts/hooks/post-doc-compile.sh
  ci_scripts/utils.sh
  docs-build.sh
  docs/api/api_aliases.ini
  docs/api/paddle/hypot_cn.rst
  docs/api/paddle/sparse/isnan_cn.rst
  docs/api_guides/low_level/layers/tensor.rst
  docs/api_guides/low_level/layers/tensor_en.rst
  docs/design/concepts/images/parallel_executor_overview.dot
  docs/design/dynamic_rnn/rnn.dot
  docs/design/mkldnn/acquire_api/scripts/acquire.dot
  docs/design/mkldnn/caching/scripts/cache.dot
  docs/design/mkldnn/caching/scripts/get_blob.dot
  docs/design/mkldnn/caching/scripts/set_blob.dot
  docs/design/mkldnn/data_transformation/scripts/data_transform.dot
  docs/design/mkldnn/gru/images/different_tensor_memory_arrangement.svg
  docs/design/mkldnn/gru/images/eq_origin_mode_false.svg
  docs/design/mkldnn/gru/images/eq_origin_mode_true.svg
  docs/design/mkldnn/gru/images/eq_proof.svg
  docs/design/mkldnn/gru/images/fc_gru_fuse_pass.svg
  docs/design/mkldnn/gru/images/input_difference.svg
  docs/design/mkldnn/gru/images/input_is_reverse.svg
  docs/design/mkldnn/inplace/scripts/inplace.dot
  docs/design/mkldnn/inplace/scripts/multi-output-inplace.dot
  docs/design/mkldnn/inplace/scripts/unwanted-inplace.dot
  docs/design/mkldnn/nhwc/scripts/nhwc-grad.dot
  docs/design/mkldnn/nhwc/scripts/nhwc.dot
  docs/eval/【Hackathon No.112】 PR.md
  docs/guides/beginner/quick_start_cn.ipynb
  docs/images/op.dot
  docs/images/op_op_with_kern_class_diagram.dot
  docs/images/op_with_kernel.dot
  docs/images/rnn.dot
  docs/practices/cv/image_ocr.ipynb
  docs/practices/quick_start/hello_paddle.ipynb
  docs/practices/recommendations/collaborative_filtering.ipynb
  docs/practices/reinforcement_learning/AlphaZero.ipynb
  docs/practices/time_series/autoencoder.ipynb
  docs/templates/common_docs.py
  docs/templates/layout.html
Labels: contributor, HappyOpenSource

#6246 [fix] fix argument bugs `check_api_label_cn.py`
  ci_scripts/check_api_label_cn.py
Labels: contributor

#6243 remove useless shell script
  docs/api/gen_doc.sh
Labels: contributor

#6244 [CodeStyle] add `pre-commit hook` for `ruff` and `isort`
  .pre-commit-config.yaml
  pyproject.toml
Labels: contributor

#6231 update .gitignore to ignore output files
  .gitignore
  docs/api/.gitignore
  docs/design/concepts/README.md
Labels: contributor

#6250 [Docathon][CodeStyle] refine pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: contributor

#6247 [CodeStyle][task 20] enable PLR1701 rule
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6253 [Docathon][CodeStyle] refine ci and pre-commit
  ci_scripts/check_api_cn.sh
  ci_scripts/check_api_label_cn.sh
  ci_scripts/check_api_parameters.sh
  ci_scripts/check_code.sh
  ci_scripts/ci_start.sh
Labels: contributor

#6255 [Docathon][CodeStyle Fix No.21] enable `UP031` rule
  docs/api/gen_alias_api.py
  pyproject.toml
Labels: contributor

#6258 [Docathon][CodeStyle Fix No.21] enable `UP008` rule
  ci_scripts/CAPItools/utils_helper.py
  pyproject.toml
Labels: contributor

#6259 [Docathon][CodeStyle Fix No.10] enable UP004 rule
  ci_scripts/CAPItools/utils_helper.py
  pyproject.toml
Labels: contributor

#6260 [Docathon][CodeStyle Fix No.5] enable UP025 rule
  ci_scripts/doc-build-config/en/conf.py
  ci_scripts/doc-build-config/zh/conf.py
  pyproject.toml
Labels: contributor

#6261 [Docathon][CodeStyle Fix No.3] enable UP032 rule
  docs/api/extract_api_from_docs.py
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6262 [Docathon][CodeStyle Fix No.14] enable C419 rule
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6265 [Docathon][CodeStyle Fix No.9] enable C405 rule
  docs/api/gen_alias_api.py
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6263 [Docathon][CodeStyle Fix No.13] enable C416 rule
  ci_scripts/check_api_docs_en.py
  pyproject.toml
Labels: contributor

#6264 [Docathon][CodeStyle Fix No.12] enable C414 rule
  pyproject.toml
Labels: contributor

#6266 [Docathon][CodeStyle Fix No.8] enable C403 rule
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6267 [Docathon][CodeStyle Fix No.17] enable E712 rule
  ci_scripts/CAPItools/utils_helper.py
  pyproject.toml
Labels: contributor

#6269 [Docathon][CodeStyle Fix No.19] enable F821 rule
  ci_scripts/check_copy_from_parsed_into_sample_code.py
  pyproject.toml
Labels: contributor

#6268 [Docathon][CodeStyle Fix No.15] enable E401 rule
  ci_scripts/doc-build-config/en/conf.py
  pyproject.toml
Labels: contributor

#6270 [Docathon][CodeStyle Fix No.4] enable F401 rule
  ci_scripts/check_api_parameters.py
  ci_scripts/check_copy_from_parsed_into_sample_code.py
  ci_scripts/doc-build-config/en/conf.py
  ci_scripts/doc-build-config/zh/conf.py
  docs/api/gen_alias_api.py
  pyproject.toml
Labels: contributor

#6271 [Docathon][CodeStyle Fix No.19] enable F811 rule
  ci_scripts/doc-build-config/en/conf.py
Labels: contributor

#6272 [Docathon][CodeStyle Fix No.16] enable E711 rule
  ci_scripts/CAPItools/main.py
Labels: contributor

#6273 [Docathon][CodeStyle Fix No.7] enable PLR1722 rule
  ci_scripts/check_api_parameters.py
  docs/api/gen_alias_api.py
Labels: contributor

#6275 [Docathon][CodeStyle Fix No.2] enable I001 rule
  ci_scripts/CAPItools/main.py
  ci_scripts/check_api_docs_en.py
  ci_scripts/check_api_label_cn.py
  ci_scripts/check_api_parameters.py
  ci_scripts/check_pr_approval.py
  ci_scripts/doc-build-config/en/conf.py
  ci_scripts/doc-build-config/zh/conf.py
  ci_scripts/hooks/post_filter_htmls.py
  docs/api/copy_codes_from_en_doc.py
  docs/api/extract_api_from_docs.py
  docs/api/gen_alias_api.py
  docs/api/gen_doc.py
  pyproject.toml
Labels: contributor

#6274 [Docathon][CodeStyle Fix No.1] enable F541 rule
  ci_scripts/CAPItools/utils_helper.py
Labels: contributor

#6276 [Docathon][CodeStyle Fix] update `pyproject.toml`
  pyproject.toml
Labels: contributor

#6156 修复 paddle.expand 等 API 的文档
  docs/api/paddle/expand_cn.rst
  docs/api/paddle/nn/Dropout_cn.rst
  docs/api/paddle/nn/functional/interpolate_cn.rst
  docs/api/paddle/sum_cn.rst
Labels: contributor, HappyOpenSource

#6252 映射文档 添加部分缺失的映射文档
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.requires_grad_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.slogdet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.set_printoptions.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.diag_embed.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.nansum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.no_grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.set_default_dtype.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.set_grad_enabled.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.t.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.where.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.BuildExtension.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.BuildExtension.with_options.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.cpp_extension.CUDA_HOME.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.Dataset.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.dataloader.default_collate.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.default_collate.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor
