Repository PaddlePaddle/docs, pull requests merged in 2023-11, with the labels that each got.

#6256 【映射文档自动化】 添加 PyTorch 与 Paddle 映射关系主目录的自动生成
  ci_scripts/hooks/pre-doc-compile.sh
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.register_forward_hook.md
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6280 【Hackathon 5th No.43】API转换21-41
  docs/api/paddle/nn/PoissonNLLLoss_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.PoissonNLLLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SmoothL1Loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.broadcast_tensors.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.finfo.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.iinfo.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#6235 【Hackathon 5th No.13】【关联 PR】Updated int support for sign doc -Part
  docs/api/paddle/sign_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6254 【Hackathon 5th No.3】为 Paddle 新增 masked_fill API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/masked_fill__cn.rst
  docs/api/paddle/masked_fill_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_fill_.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6282 docs(update): update softsign of complex type
  docs/api/paddle/nn/Softsign_cn.rst
Labels: contributor, HappyOpenSource

#6281 【Hackathon 5th No.46】API转换 84-102
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_reduce.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_to_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.barrier.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.broadcast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.get_backend.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.scatter.md
Labels: contributor, PaddlePaddle Hackathon

#6284 【Hackathon 5th No.2】为 Paddle 新增 index_fill API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/index_fill__cn.rst
  docs/api/paddle/index_fill_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_add.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_fill_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_put.md
Labels: contributor, PaddlePaddle Hackathon

#6286 【Hackathon 5th No.22】Add CosineAnnealingWarmRestarts API to Paddle
  docs/api/paddle/optimizer/lr/CosineAnnealingWarmRestarts_cn.rst
  docs/api/paddle/optimizer/lr/LRScheduler_cn.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler_en.rst
Labels: contributor, PaddlePaddle Hackathon

#6294 [Change] remove blank ps
  ci_scripts/doc-build-config/en/conf.py
Labels: contributor, HappyOpenSource

#6053 映射文档 No. 94/95/96
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanquantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.polygamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.qr.md
Labels: contributor, HappyOpenSource

#6296 修复 paddle.nn.GRU 的文档
  docs/api/paddle/nn/GRU_cn.rst
Labels: contributor, HappyOpenSource

#6298 [Change] reshape dtype
  docs/api/paddle/reshape_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6291 No.18 paddle.nn.GLU易用性提升 中文api文档
  docs/api/paddle/nn/GLU_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6307 修复 paddle.vision.transforms.ToTensor 的 API 文档
  docs/api/paddle/vision/transforms/ToTensor_cn.rst
Labels: contributor, HappyOpenSource

#6285 【Hackathon 5th No.24】Add SubsetRandomSampler
  docs/api/paddle/io/Overview_cn.rst
  docs/api/paddle/io/SubsetRandomSampler_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.SubsetRandomSampler.md
Labels: contributor, PaddlePaddle Hackathon

#6305 【Hackathon 5th No.15】 为 Paddle 新增 Tensor.to() 以及 Layer.astype() API
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/nn/Layer_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6288 【Hackathon 5th No.44】API转换 42-61
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cholesky_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.float_power.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.float_power_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.symeig.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triangular_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eig.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eigh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_norm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.pinv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.svd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.vector_norm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cholesky_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.pca_lowrank.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.symeig.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.enable_grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.set_grad_enabled.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.set_grad_enabled.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6283 Fix torch.utils.data.DataLoader doc
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TransformerEncoder.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.DataLoader.md
Labels: contributor

#6290 【Hackathon 5th No.23】Add ConcatDataset API to Paddle
  docs/api/paddle/io/ConcatDataset_cn.rst
  docs/api/paddle/io/Overview_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6313 update codestyle doc and update ruff
  .pre-commit-config.yaml
  docs/dev_guides/git_guides/codestyle_check_guide_cn.md
Labels: contributor, HappyOpenSource

#6321 update docs for unstack and add_n
  docs/api/paddle/add_n_cn.rst
  docs/api/paddle/unstack_cn.rst
Labels: contributor

#6289 【Hackathon 5th No.26】为 Paddle 新增 diagonal_scatter API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/diagonal_scatter_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagonal_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.diagonal_scatter.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6311 [Docathon][Fix COPY-FROM No.6-10]
  docs/api/paddle/distributed/InMemoryDataset_cn.rst
  docs/api/paddle/text/Movielens_cn.rst
  docs/api/paddle/text/UCIHousing_cn.rst
  docs/api/paddle/text/WMT14_cn.rst
  docs/api/paddle/text/WMT16_cn.rst
Labels: contributor, HappyOpenSource

#6309 [Docathon][Fix COPY-FROM No.4、5]
  docs/api/paddle/text/Imdb_cn.rst
  docs/api/paddle/text/Imikolov_cn.rst
Labels: contributor, HappyOpenSource

#6323 [CodeStyle][docs] remove pylint in codestyle docs
  ci_scripts/Dockerfile
  docs/dev_guides/git_guides/codestyle_check_guide_cn.md
Labels: contributor, HappyOpenSource

#6320 fix docs bugs：docs\api\paddle\nn\RNN_cn.rst
  docs/api/paddle/nn/RNN_cn.rst
Labels: contributor, HappyOpenSource

#6330 【Hackathon 5th No.13】【关联 PR】Added uint8&int8&int16 support for compare_kernel docs -part
  docs/api/paddle/equal_cn.rst
  docs/api/paddle/greater_equal_cn.rst
  docs/api/paddle/greater_than_cn.rst
  docs/api/paddle/less_equal_cn.rst
  docs/api/paddle/less_than_cn.rst
  docs/api/paddle/not_equal_cn.rst
Labels: contributor

#6329 修复API:grad的中文文档
  docs/api/paddle/grad_cn.rst
Labels: contributor, HappyOpenSource

#6331 update docs for broadcast,broadcast_tensors,multiplex,unbind
  docs/api/paddle/broadcast_tensors_cn.rst
  docs/api/paddle/distributed/broadcast_cn.rst
  docs/api/paddle/multiplex_cn.rst
  docs/api/paddle/unbind_cn.rst
Labels: contributor

#6315 修复paddle.ones API 的文档
  docs/api/paddle/ones_cn.rst
Labels: contributor, HappyOpenSource

#6332 【Doc】fix api/paddle/gather_cn.rst文档
  docs/api/paddle/gather_cn.rst
Labels: contributor, HappyOpenSource

#6335 修复 LinearWarmup 文档
  docs/api/paddle/optimizer/lr/LinearWarmup_cn.rst
Labels: contributor, HappyOpenSource

#6337 remove pylint in `docs\dev_guides\docs_contributing_guides_cn.md`
  docs/dev_guides/code_contributing_path_cn.md
  docs/dev_guides/docs_contributing_guides_cn.md
Labels: HappyOpenSource

#6324 docs: 修改 LRScheduler bug
  docs/api/paddle/optimizer/lr/LRScheduler_cn.rst
Labels: contributor, HappyOpenSource

#6317 【Hackathon 5th No.33】为 Paddle 新增 atleast_1d / atleast_2d / atleast_3d API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/atleast_1d_cn.rst
  docs/api/paddle/atleast_2d_cn.rst
  docs/api/paddle/atleast_3d_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.atleast_1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.atleast_2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.atleast_3d.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6339 【Hackathon 5th No.13】【关联 PR】Updated sign doc for uint8
  docs/api/paddle/sign_cn.rst
Labels: contributor, PaddlePaddle Hackathon
