Repository PaddlePaddle/docs, pull requests merged in 2023-12, with the labels that each got.

#6287 【Hackathon 5th No.14】Add combinations API to Paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/combinations_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6334 【Hackathon 5th No.37】为 Paddle 新增 householder_product API
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/householder_product_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6301 修复了mse_loss_cn.rst的一个bug
  docs/api/paddle/nn/functional/mse_loss_cn.rst
Labels: contributor, HappyOpenSource

#6345 docfix：#47，docs/zh/develop/api/paddle/nn/Conv1D_cn 属性部分的格式参照参数、形状的写法
  docs/api/paddle/nn/Conv1D_cn.rst
Labels: contributor, HappyOpenSource

#6233 [Docathon] add cn doc for `paddle.utils.require_version` and `paddle.Tensor.create_tensor`
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/utils/require_version_cn.rst
Labels: contributor, HappyOpenSource

#6352 【Hackathon 5th No.27】为 Paddle 新增 select_scatter API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/select_scatter_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6380 【Hackathon 5th No.47】API转换 103-124 -part
  docs/api/paddle/io/ConcatDataset_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.hypot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.hypot_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_select.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.to.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.householder_product.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.type.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.combinations.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.hypot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.index_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.masked_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.select_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.lr_scheduler.CosineAnnealingWarmRestarts.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.lr_scheduler.LinearLR.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.multigammaln.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.ConcatDataset.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.SubsetRandomSampler.md
Labels: contributor, PaddlePaddle Hackathon

#6385 [Docathon][Add CN Doc No.27]
  docs/api/paddle/utils/try_import_cn.rst
Labels: contributor, HappyOpenSource

#6350 【Hackathon 5th No.35】为 Paddle 新增 histogramdd API 中文文档
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/histogramdd_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6381 [Docathon][Fix COPY-FROM No.1、2、3]
  docs/api/paddle/device/cuda/Event_cn.rst
  docs/api/paddle/device/cuda/Stream_cn.rst
  docs/api/paddle/text/Conll05st_cn.rst
Labels: contributor, HappyOpenSource

#6379 [Docathon][Fix COPY-FROM No.16-19]
  docs/api/paddle/distributed/fleet/DistributedStrategy_cn.rst
  docs/api/paddle/optimizer/Lamb_cn.rst
  docs/api/paddle/optimizer/Optimizer_cn.rst
  docs/api/paddle/optimizer/RMSProp_cn.rst
Labels: contributor, HappyOpenSource

#6386 【Hackathon 5th No. 18】Add Binomial API -part
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/binomial_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6348 【Hackathon 5th No.6】 为 Paddle 增强put_along_axis API
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/put_along_axis__cn.rst
  docs/api/paddle/put_along_axis_cn.rst
  docs/api/paddle/take_along_axis_cn.rst
  docs/guides/custom_op/new_cpp_op_cn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_add.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_add_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.take_along_dim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.scatter_add.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.take_along_dim.md
Labels: contributor, PaddlePaddle Hackathon

#6391 【Hackathon 5th No.17】 为 Paddle 新增 pdist API 中文文档
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/pdist_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6392 【Hackathon 5th No.19】Add ContinuousBernoulli and MultivariateNormal API
  docs/api/paddle/distribution/ContinuousBernoulli_cn.rst
  docs/api/paddle/distribution/MultivariateNormal_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6340 【Hackathon 5th No.13】Added signbit doc
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/signbit_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6400 【Hackathon 5th No.47】API转换 torch.histogramdd -part
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.signbit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.pdist.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.histogramdd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.signbit.md
Labels: contributor, PaddlePaddle Hackathon

#6406 将paddle_utils_deprecated修正为deprecated
  docs/api/paddle/utils/deprecated_cn.rst
Labels: contributor, HappyOpenSource

#6388 【Hackathon 5th No.41】为 Paddle 新增 Rprop API 中文文档
  docs/api/paddle/optimizer/Overview_cn.rst
  docs/api/paddle/optimizer/Rprop_cn.rst
  docs/api_guides/low_level/optimizer.rst
  docs/api_guides/low_level/optimizer_en.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Rprop.md
Labels: contributor, PaddlePaddle Hackathon

#6384 [Docathon][Add CN Doc No.1]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/sin__cn.rst
Labels: contributor, HappyOpenSource

#6383 [Docathon][Add CN Doc No.1]
  docs/api/paddle/sin_cn.rst
Labels: contributor, HappyOpenSource

#6407 paddle_utils_require_version修改成require_version
  docs/api/paddle/utils/require_version_cn.rst
Labels: contributor, HappyOpenSource

#6404 [Auto Parallel] Add doc for visualize flow parallel timing diagram tool in static graph mode
  docs/guides/06_distributed_training/images/chrome_tracing_results.png
  docs/guides/06_distributed_training/images/perfetto_results-2.png
  docs/guides/06_distributed_training/images/perfetto_results.png
  docs/guides/06_distributed_training/images/profiler_helper_static_run_results.png
  docs/guides/06_distributed_training/index_cn.rst
  docs/guides/06_distributed_training/visual_pipeline_parallel_static_mode_cn.rst
Labels: contributor

#6362 [Docathon][Add CN Doc No.4-5]
  docs/api/paddle/incubate/nn/FusedLinear_cn.rst
  docs/api/paddle/incubate/nn/functional/fused_matmul_bias_cn.rst
Labels: contributor, HappyOpenSource

#6405 【Hackathon 5th No.4】为 Paddle 新增 masked_scatter API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/masked_scatter__cn.rst
  docs/api/paddle/masked_scatter_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_scatter_.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6368 [Docathon][Add CN Doc No.15-16]
  docs/api/paddle/version/Overview_cn.rst
  docs/api/paddle/version/xpu_cn.rst
  docs/api/paddle/version/xpu_xccl_cn.rst
Labels: contributor, HappyOpenSource

#6411 Fix Typo fused_matmul_bias
  docs/api/paddle/incubate/nn/functional/fused_matmul_bias_cn.rst
Labels: contributor, HappyOpenSource

#6325 【Hackathon 5th No. 18】Add Binomial and Poisson API
  docs/api/paddle/distribution/Binomial_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
  docs/api/paddle/distribution/Poisson_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6415 【易用性提升No.7】为transformerDecoderLayer新增layer_norm_eps参数
  docs/api/paddle/nn/TransformerDecoderLayer_cn.rst
Labels: contributor, HappyOpenSource

#6414 【Hackathon 5th No.36】 为 Paddle 新增 matrix_exp API
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/matrix_exp_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_exp.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6422 [fix] fix some typos and style
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
Labels: contributor

#6428 update compile documents python version to 3.8
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
  docs/dev_guides/sugon/complie_and_test_cn.md
  docs/guides/06_distributed_training/cluster_quick_start_fl_ps_cn.rst
  docs/guides/hardware_support/ipu_docs/infer_example_cn.md
  docs/guides/hardware_support/ipu_docs/paddle_install_cn.md
  docs/install/compile/arm-compile.md
  docs/install/compile/mips-compile.md
  docs/install/compile/sw-compile.md
  docs/install/compile/zhaoxin-compile.md
Labels: contributor, HappyOpenSource

#6423 [doc] fix api name in `*.rst`
  docs/api/paddle/ParamAttr_cn.rst
  docs/api/paddle/addmm_cn.rst
  docs/api/paddle/bucketize_cn.rst
  docs/api/paddle/device/cuda/get_device_properties_cn.rst
  docs/api/paddle/device/cuda/max_memory_allocated_cn.rst
  docs/api/paddle/device/cuda/max_memory_reserved_cn.rst
  docs/api/paddle/device/cuda/memory_allocated_cn.rst
  docs/api/paddle/device/cuda/memory_reserved_cn.rst
  docs/api/paddle/distributed/QueueDataset_cn.rst
  docs/api/paddle/incubate/nn/FusedEcMoe_cn.rst
  docs/api/paddle/nn/AdaptiveAvgPool1D_cn.rst
  docs/api/paddle/nn/AdaptiveMaxPool1D_cn.rst
  docs/api/paddle/nn/AdaptiveMaxPool2D_cn.rst
  docs/api/paddle/nn/AdaptiveMaxPool3D_cn.rst
  docs/api/paddle/nn/AvgPool1D_cn.rst
  docs/api/paddle/nn/MaxPool1D_cn.rst
  docs/api/paddle/nn/SoftMarginLoss_cn.rst
  docs/api/paddle/nn/functional/adaptive_avg_pool1d_cn.rst
  docs/api/paddle/nn/functional/adaptive_max_pool1d_cn.rst
  docs/api/paddle/nn/functional/avg_pool1d_cn.rst
  docs/api/paddle/nn/functional/avg_pool2d_cn.rst
  docs/api/paddle/nn/functional/avg_pool3d_cn.rst
  docs/api/paddle/nn/functional/channel_shuffle_cn.rst
  docs/api/paddle/nn/functional/max_pool1d_cn.rst
  docs/api/paddle/nn/functional/max_pool2d_cn.rst
  docs/api/paddle/nn/functional/max_pool3d_cn.rst
  docs/api/paddle/nn/functional/max_unpool1d_cn.rst
  docs/api/paddle/nn/functional/max_unpool2d_cn.rst
  docs/api/paddle/nn/functional/max_unpool3d_cn.rst
  docs/api/paddle/nn/functional/pixel_shuffle_cn.rst
  docs/api/paddle/nn/functional/pixel_unshuffle_cn.rst
  docs/api/paddle/nn/functional/sparse_attention_cn.rst
  docs/api/paddle/profiler/Overview_cn.rst
  docs/api/paddle/profiler/SummaryView_cn.rst
  docs/api/paddle/sparse/nn/functional/max_pool3d_cn.rst
  docs/api/paddle/static/default_startup_program_cn.rst
Labels: contributor, HappyOpenSource

#6409 【Hackathon 5th No.28】为 Paddle 新增 slice_scatter API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/slice_scatter_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.slice_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.slice_scatter.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6429 【Hackathon 5th No.7】为 Paddle 新增 apply API
  docs/api/paddle/Tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.apply_.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor
