Repository PaddlePaddle/docs, pull requests merged in 2023-05, with the labels that each got.

#5850 fix gather_cn.rst bugs
  docs/api/paddle/gather_cn.rst
Labels: contributor, status: proposed

#5807 【Hackathon 4th No.12】为 Paddle 新增 Cauchy API -- Cauchy doc
  docs/api/paddle/distribution/Cauchy_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
Labels: contributor, status: proposed

#5647 Update clip_cn.rst
  docs/api/paddle/clip_cn.rst
Labels: contributor, status: proposed

#5854 映射文档 No. 46
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.gcd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.histc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.kron.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.lcm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.logcumsumexp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.renorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.repeat_interleave.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.searchsorted.md
Labels: contributor, status: proposed

#5856 add DTK in docs
  docs/guides/hardware_support/rocm_docs/index_cn.rst
  docs/guides/hardware_support/rocm_docs/paddle_install_cn.md
Labels: contributor, status: proposed

#5848 update api convert list
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.deg2rad.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5846 【Hackathon 4th No.30】为 Paddle 新增 paddle.sparse.sum 稀疏 API
  docs/api/paddle/sparse/sum_cn.rst
Labels: contributor, status: proposed

#5857 映射文档 No. 59
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bfloat16.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bool.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.byte.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.char.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.clone.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.copy_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.div.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.double.md
Labels: contributor, status: proposed

#5852 映射文档 No. 54
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BCELoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BCEWithLogitsLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CTCLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CrossEntropyLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.HingeEmbeddingLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.KLDivLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MarginRankingLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.NLLLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SmoothL1Loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SoftMarginLoss.md
Labels: contributor, status: proposed

#5835 映射文档 No. 41
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sgn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.square.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sub.md
Labels: contributor, status: not progressed

#5861 【Hackathon 4th No.7】新增 unflatten doc
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/Unflatten_cn.rst
  docs/api/paddle/unflatten_cn.rst
Labels: contributor

#5858 映射文档 No.47
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.cholesky.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.addmm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.bmm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cholesky.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.tensordot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.tril.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.tril_indices.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.triu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.triu_indices.md
Labels: contributor, status: proposed

#5849 映射文档 No. 49
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.mm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.mv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.qr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.svd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.svd_lowrank.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.symeig.md
Labels: contributor, status: proposed

#5840 映射文档 No.48
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_rank.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.dot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.ger.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.inner.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.inverse.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.lu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.lu_unpack.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.matrix_power.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.outer.md
Labels: contributor, status: proposed

#5827 映射文档 No.44
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.fmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.fmin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.greater.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.le.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.less.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.less_equal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.lt.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.maximum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.minimum.md
Labels: contributor, status: proposed

#5876 Update api mapping list
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CTCLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CrossEntropyLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.HingeEmbeddingLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.NLLLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SoftMarginLoss.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5838 docs: added i0 and i0e docs for paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/i0_cn.rst
  docs/api/paddle/i0e_cn.rst
Labels: contributor, status: proposed

#5816 【Hackathon 4th No.11】为 Paddle 新增 Geometric API -- Geometric 中文API doc
  docs/api/paddle/distribution/Geometric_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
Labels: contributor, status: proposed

#5869 映射文档 No.72
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctan2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cdouble.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cfloat.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.hfft2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.hfftn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.ihfft2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.ihfftn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.cross.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.solve_triangular.md
Labels: contributor, status: proposed

#5839 Add doc for paddle.i1 and paddle.i1e document.;test=docs_preview
  docs/api/api_label
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/i1_cn.rst
  docs/api/paddle/i1e_cn.rst
Labels: contributor, status: proposed

#5878 add torch.bucketize etc.
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.count_nonzero.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.div.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.repeat_interleave.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sgn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sub.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.subtract.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lstsq.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.bucketize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.chain_matmul.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.count_nonzero.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sub.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.subtract.md
Labels: contributor, status: proposed

#5893 Update api convert mapping
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5860 映射文档 No.70
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanmean.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.mish.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eig.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eigvals.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.multi_dot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/troch.nn.Mish.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.frexp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.nanmean.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.take_along_dim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.erf.md
Labels: contributor, HappyOpenSource

#5834 映射文档 No.45
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.clone.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cross.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cumprod.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.cumsum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.ne.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.not_equal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.stft.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.topk.md
Labels: contributor, status: proposed, HappyOpenSource
