Repository PaddlePaddle/docs, pull requests merged in 2023-08, with the labels that each got.

#6064 [bug fix] fix paconvert doc bug
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tenosr.dtype.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.copy_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cpu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagflat.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.int.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.numpy.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.outer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pow.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.requires_grad_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tolist.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.where.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.zero_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.binary_cross_entropy_with_logits.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.kl_div.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.triplet_margin_with_distance_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LayerNorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.named_modules.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.flatten.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.numel.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Optimizer.step.md
Labels: contributor

#6080 Update torch.special.round.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.round.md
Labels: contributor, status: proposed

#6058 映射文档 No.57 `torch.nn.MultiLabelMarginLoss`
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MultiLabelMarginLoss.md
Labels: contributor, HappyOpenSource

#6083 Update torch.linalg.cond.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.cond.md
Labels: contributor, status: proposed

#6085 Update torch.Tensor.trace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.trace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Mish.md
Labels: contributor, status: proposed

#6089 [Docs]Add fp16 and bp16 support for argsort erfinv nanmedian
  docs/api/paddle/argsort_cn.rst
  docs/api/paddle/erfinv_cn.rst
  docs/api/paddle/nanmedian_cn.rst
Labels: contributor, status: proposed

#6075 映射文档 No.243-300 其他未领取项
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_stream.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.svdvals.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.Function.backward.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.Function.forward.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.Function.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.function.FunctionCtx.mark_non_differentiable.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.function.FunctionCtx.save_for_backward.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.function.FunctionCtx.set_materialize_grads.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.graph.saved_tensors_hooks.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.erfc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.exp2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.expit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.gammaln.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.nn.utils.parametrizations.spectral_norm.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6082 映射文档 No.4
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.copysign.md
Labels: contributor, status: proposed, HappyOpenSource

#5740 support fp16 fpr dist op
  docs/api/paddle/dist_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6103 add complex support for dot op
  docs/api/paddle/dot_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#6051 映射文档 No. 87
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lstsq.md
Labels: contributor, HappyOpenSource

#6104 Fix torch.special.erfcx
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.erfcx.md
Labels: contributor, status: proposed, HappyOpenSource

#6107 Update torch.Tensor.lstsq.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.lstsq.md
Labels: contributor, status: proposed

#6087 update docs/guides/model_convert/convert_from_pytorch/api_difference/cuda
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.Event.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.HalfTensor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.Stream__upper.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.amp.GradScaler.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.amp.autocast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.comm.broadcast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.current_stream.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.device_count.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.empty_cache.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_capability.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_name.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_properties.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_rng_state_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.is_available.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.manual_seed.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.max_memory_allocated.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.max_memory_reserved.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.memory_allocated.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.memory_reserved.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.nvtx.range_pop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.nvtx.range_push.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_device.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_rng_state_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.stream.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.synchronize.md
Labels: contributor, status: proposed

#6108 映射文档 No. 310-315/320/321/335
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6110 fix docs/guides/model_convert/convert_from_pytorch/api_difference/fun…
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.cross_entropy.md
Labels: contributor, status: proposed

#6096 [Change] 更新文档《开发 API Python 端》与《API 文档书写规范》
  docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md
  docs/dev_guides/api_contributing_guides/images/zeros_python_api.png
  docs/dev_guides/style_guide_and_references/code_example_writing_specification_cn.md
  docs/dev_guides/style_guide_and_references/index_cn.rst
Labels: contributor, status: proposed, HappyOpenSource Pro

#6098 remove redundant `:code-example8` in `paddle.profiler.Profiler.summary` COPY-FROM
  docs/api/paddle/profiler/Profiler_cn.rst
Labels: contributor, status: proposed, HappyOpenSource Pro

#6113 映射文档 No. 331
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.conj_physical.md
Labels: contributor, status: proposed, HappyOpenSource

#6114 映射文档 No. 362
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.softmax.md
Labels: contributor, status: proposed, HappyOpenSource

#6118 映射文档 No.373/375/376
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6105 Fixed a mismatch between Chinese and English documents for the CrossEntropyLoss PaddlePaddle/Paddle#50424
  docs/api/paddle/nn/CrossEntropyLoss_cn.rst
Labels: contributor, status: not progressed

#6126 Fix torch.sparse.addmm,torch.sparse.mm
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.addmm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.mm.md
Labels: contributor, HappyOpenSource

#6119 映射文档 No.384-387
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.get_buffer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.get_parameter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.get_submodule.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.register_parameter.md
Labels: contributor, HappyOpenSource

#6138 Update DataLoader_cn.rst
  docs/api/paddle/io/DataLoader_cn.rst
Labels: contributor

#6115 映射文档 No. 304/306/308/327-329/332/351/363/365/369/371
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.retain_grad.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed, HappyOpenSource

#6120 映射文档 No.307/372
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.amp.autocast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autocast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.cpu.amp.autocast.md
Labels: contributor, HappyOpenSource

#6137 映射文档 No.368/374/377
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Dropout1d.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6148 Modified the document of the paddle.diff() function.
  docs/api/paddle/diff_cn.rst
Labels: contributor, HappyOpenSource

#6147 Modify the docs of UpsamplingNearest2D and UpsamplingBilinear2D
  docs/api/paddle/nn/UpsamplingBilinear2D_cn.rst
  docs/api/paddle/nn/UpsamplingNearest2D_cn.rst
Labels: contributor, HappyOpenSource

#6139 映射文档 No.358/361
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu_factor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu_factor_ex.md
Labels: contributor, HappyOpenSource

#6141 Fix torch.linalg.solve_triangular
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.solve_triangular.md
Labels: contributor, HappyOpenSource

#6149 映射文档 No.97
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.resize_as_.md
Labels: contributor

#6125 fix torch.nn.BatchNorm
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm3d.md
Labels: contributor, HappyOpenSource

#6150 add complex dtype for logical op
  docs/api/paddle/logical_and_cn.rst
  docs/api/paddle/logical_not_cn.rst
  docs/api/paddle/logical_or_cn.rst
  docs/api/paddle/logical_xor_cn.rst
Labels: contributor, HappyOpenSource
