Repository PaddlePaddle/docs, pull requests merged in 2023-06, with the labels that each got.

#5911 Fix typos
  docs/advanced_guide/performance_improving/amp/amp.md
  docs/advanced_guide/performance_improving/inference_improving/paddle_xpu_infer_cn.md
  docs/api_guides/low_level/distributed/cluster_train_data_en.rst
  docs/api_guides/low_level/layers/detection.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler_en.rst
  docs/design/concepts/cpp_data_feeding.md
  docs/design/concepts/functions_operators_layers.md
  docs/design/concepts/index.html
  docs/design/concepts/parallel_executor.md
  docs/design/concepts/tensor_array.md
Labels: contributor, status: proposed

#5906 Update API Convert Mapping
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5899 修改API映射关系文档的bug
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.equal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.expand.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.masked_fill.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.cross_entropy.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BCELoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BCEWithLogitsLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.ConstantPad1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.ConstantPad2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.ConstantPad3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CrossEntropyLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.GroupNorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LSTM.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LayerNorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MSELoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.NLLLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SmoothL1Loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.chunk.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.kthvalue.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.unique_consecutive.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5895 【Hackathon 4th No.29】为 Paddle 新增 paddle.sparse.slice 稀疏 API
  docs/api/paddle/sparse/slice_cn.rst
Labels: contributor, status: proposed, PaddlePaddle Hackathon

#5913 【Hackathon 4 No.19】added polygamma doc
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/polygamma_cn.rst
Labels: contributor, status: proposed, PaddlePaddle Hackathon

#5925 【Hackathon4】No6. Add chinese doc files for ldexp
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/ldexp_cn.rst
Labels: contributor, status: proposed, PaddlePaddle Hackathon

#5900 Add Cpp Doc Generate tools
  ci_scripts/CAPItools/README.md
  ci_scripts/CAPItools/main.py
  ci_scripts/CAPItools/requirements.txt
  ci_scripts/CAPItools/utils.py
  ci_scripts/CAPItools/utils_helper.py
Labels: contributor, status: proposed

#5904 docs: add pca_lowrank docs
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/pca_lowrank.rst
  docs/api/paddle/sparse/pca_lowrank_cn.rst
Labels: contributor, status: proposed, PaddlePaddle Hackathon

#5912 映射文档 No.62，63
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.subtract_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.symeig.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.to.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triangular_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.type.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.Stream.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.amp.GradScaler.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.amp.autocast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.comm.broadcast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.get_rank.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.get_world_size.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.new_group.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.backward.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.functional.hessian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.functional.jacobian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.functional.jvp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.functional.vjp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.grad.md
Labels: contributor, status: proposed, HappyOpenSource

#5934 Update make_scheduler_cn.rst
  docs/api/paddle/profiler/make_scheduler_cn.rst
Labels: contributor, status: proposed

#5931 fix some docs typo errors
  docs/api/paddle/nn/TransformerEncoderLayer_cn.rst
  docs/api/paddle/nn/functional/sigmoid_focal_loss_cn.rst
  docs/api/paddle/static/Executor_cn.rst
  docs/api/paddle/static/Variable_cn.rst
  docs/api/paddle/unsqueeze_cn.rst
  docs/api/paddle/vision/transforms/Transpose_cn.rst
Labels: contributor, status: proposed

#5915 映射文档 No.64 - 78
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cuda.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fmod.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.histogram.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_reduce.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_to_all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.broadcast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.recv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.reduce.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.send.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.categorical.Categorical.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.dirichlet.Dirichlet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.distribution.Distribution.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.exp_family.ExponentialFamily.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.independent.Independent.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.multinomial.Multinomial.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.normal.Normal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.IndependentTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.ReshapeTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.uniform.Uniform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.gelu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.unfold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.cond.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eigh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.eigvalsh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.inv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matmul.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.pinv.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.qr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.GELU.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.InstanceNorm3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Sequential.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.broadcast_shapes.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.concat.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.einsum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.triangular_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.log_softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.round.md
Labels: contributor, status: proposed, HappyOpenSource

#5941 [Change]修改目前 Paddle docs 中 COPY-FROM 的逻辑
  .gitignore
  docs/api/copy_codes_from_en_doc.py
  docs/api/gen_doc.py
Labels: contributor, status: proposed

#5967 Fix api convert docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fmod.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ge.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.greater_equal.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5919 映射文档 No.51 - 60
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.add.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.add_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.exponential_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.half.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.long.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multinomial.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.norm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.celu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.cosine_embedding_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.ctc_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.elu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.gumbel_softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.hardswish.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.hardtanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.hinge_embedding_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.interpolate.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.leaky_relu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.log_softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_pool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_pool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_pool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.relu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.rrelu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.selu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.threshold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AlphaDropout.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Bilinear.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CELU.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CosineEmbeddingLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MultiLabelSoftMarginLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MultiheadAttention.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.RReLU.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.ReLU6.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SELU.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SiLU.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Threshold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Transformer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TransformerDecoderLayer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TransformerEncoder.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TransformerEncoderLayer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TripletMarginLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.parallel.DistributedDataParallel.md
Labels: contributor, status: proposed, HappyOpenSource

#5990 Update svd_cn.rst
  docs/api/paddle/linalg/svd_cn.rst
Labels: contributor, status: proposed

#5991 Update Tensor_cn.rst
  docs/api/paddle/Tensor_cn.rst
Labels: contributor, status: proposed

#5975 修改 COPY-FROM No.5 nn
  docs/api/paddle/nn/LayerDict_cn.rst
  docs/api/paddle/nn/Transformer_cn.rst
Labels: contributor, status: proposed, HappyOpenSource

#5945 映射文档 Fix convert api docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.bilinear.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.linear.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.one_hot.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5924 Fix bug of api convert docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lstsq.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.UpsamplingBilinear2D.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.floor_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.histc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.kthvalue.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.le.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.less_equal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.max.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.median.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.min.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.multiply.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed

#5992 Update torch.linalg.svd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.svd.md
Labels: contributor, status: proposed

#5956 Fix docs of torch.all and torch.any
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.any.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dot.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.any.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, status: proposed
