Repository PaddlePaddle/docs, pull requests merged in 2024-04, with the labels that each got.

#6558 Fix : F-then-B
  docs/guides/06_distributed_training/pipeline_parallel_cn.rst
Labels: contributor, HappyOpenSource

#6567 fix: stocastic --> stochastic
  docs/api/paddle/cummin_cn.rst
  docs/practices/quick_start/hello_paddle.ipynb
Labels: contributor, HappyOpenSource

#6564 fix: aixs --> axis.
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/gather_cn.rst
  docs/design/phi/design_cn.md
  docs/design/phi/design_en.md
Labels: contributor, HappyOpenSource

#6560 修复两处文档错误
  docs/guides/06_distributed_training/model_parallel_cn.rst
Labels: contributor, HappyOpenSource

#6574 fix docs: docs\install\compile\zhaoxin-compile.md
  docs/install/compile/zhaoxin-compile.md
Labels: contributor, HappyOpenSource

#6575 fix docs: docs\api\paddle\io\IterableDataset_cn.rst
  docs/api/paddle/io/IterableDataset_cn.rst
Labels: contributor, HappyOpenSource

#6573 Fix:bias->bias_info 签名信息对应
  docs/guides/jit/basic_usage_cn.md
Labels: contributor, HappyOpenSource

#6572 update paddle.summary Chinese document
  docs/api/paddle/summary_cn.rst
Labels: contributor, HappyOpenSource

#6565 fix: resoure error.
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
Labels: contributor, HappyOpenSource

#6580 clone PaConvert to get `api_alias_mapping.json` when building docs
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6577 API improvement for nn.initializer.XavierUniform and nn.initializer.XavierNormal 易用性提升
  docs/api/paddle/nn/initializer/XavierNormal_cn.rst
  docs/api/paddle/nn/initializer/XavierUniform_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/init/torch.nn.init.xavier_normal_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/init/torch.nn.init.xavier_uniform_.md
Labels: contributor

#6569 修改reshape API文档
  docs/api/paddle/reshape_cn.rst
  docs/images/reshape.png
Labels: contributor, HappyOpenSource

#6579 [映射文档] update `torch.quantile` and `torch.nanquantile` and tensor method
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanquantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.quantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.nanquantile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.quantile.md
Labels: contributor

#6555 fix: shimo MODOC 34 37 39 40 42
  docs/faq/save_cn.md
  docs/guides/06_distributed_training/pipeline_parallel_cn.rst
  docs/guides/beginner/model_save_load_cn.ipynb
  docs/guides/performance_improving/amp_cn.md
  docs/install/pip/macos-pip.md
Labels: contributor, HappyOpenSource

#6562 API improvement for paddle.svd_lowrank 易用性提升
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/pca_lowrank_cn.rst
  docs/api/paddle/linalg/svd_lowrank_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.svd_lowrank.md
Labels: contributor

#6571 [Docathon][Add Overview Doc No.2] add doc of docathon 2
  docs/api/paddle/amp/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6596 【Hackthon 6th No. 10】Upgrade isinf to support int8 int16 uint8 -part
  docs/api/paddle/isinf_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6578 [映射文档] update `torch.median` and `torch.nanmedian`
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.median.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.nanmedian.md
Labels: contributor

#6588 fix table format
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addmm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.topk.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.trace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tril.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tril_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triu_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.true_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.true_divide_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unbind.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unfold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.uniform_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique_consecutive.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unsqueeze.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unsqueeze_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.beta.Beta.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.functional.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.acos.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.arange.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.empty.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.empty_like.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.eye.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.full.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.linspace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.logspace.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.ones_like.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.range.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.zeros_like.md
Labels: contributor

#6589 update table headers in `pytorch_api_mapping_cn.md`
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6590 update diff url to relative page
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
Labels: contributor

#6602 add complex dtype for cross
  docs/api/paddle/cross_cn.rst
Labels: contributor

#6592 fix: resoure error. (#6565)
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
Labels: contributor, HappyOpenSource

#6607 [Fix] fix pytorch-paddle mapping index generate
  ci_scripts/gendoc.sh
  ci_scripts/hooks/pre-doc-compile.sh
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.apply_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tensor_split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.vsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_exp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LogSigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Softplus.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Softsign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Tanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Tanhshrink.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TripletMarginWithDistanceLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.slice_scatter.md
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/pytorch_api_mapping_cn.md
Labels: contributor

#6594 【Hackthon 6th No. 27】为 paddle.io.RandomSampler/random_split /Layer.clear_gradients 进行功能增强
  docs/api/paddle/io/RandomSampler_cn.rst
  docs/api/paddle/io/random_split_cn.rst
  docs/api/paddle/nn/Layer_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.zero_grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.RandomSampler.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.random_split.md
Labels: contributor, PaddlePaddle Hackathon

#6553 fix: shimo MODOC 16 18 21 22 24 26
  docs/api/paddle/nn/Conv2DTranspose_cn.rst
  docs/dev_guides/code_contributing_path_cn.md
  docs/guides/beginner/quick_start_cn.ipynb
  docs/guides/model_convert/convert_from_pytorch/nlp_fast_explore_cn.md
  docs/practices/cv/super_resolution_sub_pixel.ipynb
Labels: contributor, HappyOpenSource

#6523 [Docathon][Add Overview Doc No.1] add doc of docathon 1
  docs/api/paddle/amp/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6583 fix: fluid resource error
  docs/api/paddle/distributed/fleet/DistributedStrategy_cn.rst
  docs/dev_guides/op_optimization/op_optimization_method_introduction_cn.md
  docs/faq/params_cn.md
  docs/guides/model_convert/convert_from_older_versions/paddle_api_mapping_cn.rst
  docs/guides/model_convert/paddle_api_mapping_cn.rst
  docs/install/pip/linux-pip.md
  docs/install/pip/macos-pip.md
  docs/install/pip/macos-pip_en.md
Labels: contributor, HappyOpenSource

#6591 fix docs bugs
  docs/practices/nlp/n_gram_model.ipynb
Labels: contributor, HappyOpenSource

#6593 [Docathon][Add Overview Doc No.3、4、33-36] add doc of docathon 3、4、33-36
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/autograd/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6611 【Hackathon 6th No.24 】 为 paddle.nn.LSTM/RNNBase 功能增强
  docs/api/paddle/nn/LSTMCell_cn.rst
  docs/api/paddle/nn/LSTM_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LSTM.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LSTMCell.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.RNNBase.md
Labels: contributor, PaddlePaddle Hackathon

#6619 Fix Fleet docs bug
  docs/api/paddle/distributed/fleet/Fleet_cn.rst
Labels: contributor, HappyOpenSource

#6599 [Docathon][Add Overview Doc No.14] add doc of docathon 14
  docs/api/paddle/distributed/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6610 Update jupyter's default user and configuration file settings to be c…
  docs/install/docker/linux-docker.md
Labels: contributor, HappyOpenSource

#6622 【Hackathon 6th No.29】为 paddle.nn.functional.max_unpool1d / max_unpool2d / max_unpool3d 进行功能增强 -part
  docs/api/paddle/nn/MaxUnPool1D_cn.rst
  docs/api/paddle/nn/MaxUnPool2D_cn.rst
  docs/api/paddle/nn/MaxUnPool3D_cn.rst
  docs/api/paddle/nn/functional/max_unpool1d_cn.rst
  docs/api/paddle/nn/functional/max_unpool2d_cn.rst
  docs/api/paddle/nn/functional/max_unpool3d_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6616 [Docathon][Remove File No.1-3]
  docs/install/FAQ.md
  docs/install/FAQ_en.md
  docs/install/install_script.md
Labels: contributor, HappyOpenSource

#6620 [Docathon][Add Overview Doc No.5-13]补充 Overview
  docs/api/paddle/device/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6621 [Prim] 为 Paddle 新增 reduce_as API 中文文档
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/reduce_as_cn.rst
Labels: contributor

#6629 【Hackathon 6th No.29】为 paddle.nn.functional.kl_div 进行功能增强
  docs/api/paddle/nn/KLDivLoss_cn.rst
  docs/api/paddle/nn/functional/kl_div_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.kl_div.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.KLDivLoss.md
Labels: contributor
