Repository PaddlePaddle/docs, pull requests merged in 2024-10, with the labels that each got.

#6899 【Hackathon 7th No.18】为稀疏计算添加复数支持2 -part
  docs/api/paddle/sparse/divide_cn.rst
  docs/api/paddle/sparse/multiply_cn.rst
Labels: contributor

#6901 【Hackathon 7th No.36】第3组部分文档修改内容
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.blackman.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.cosine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.exponential.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.gaussian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.general_cosine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.general_hamming.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.hamming.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.hann.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.blackman_window.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.hamming_window.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.hann_window.md
Labels: contributor, PaddlePaddle Hackathon

#6885 【Hackathon 7th No.38】为Paddle代码转换工具新增API转换规则（第5组）
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.float_power.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.isneginf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.isposinf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.isreal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.positive.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_reduce.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.block_diag.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.can_cast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.cartesian_prod.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.float_power.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.isin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.isneginf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.isposinf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.isreal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.positive.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.scatter_reduce.md
Labels: contributor, PaddlePaddle Hackathon

#6884 【Hackathon 7th No.37】为 Paddle 代码转换工具新增 API 转换规则（第 4 组）
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.igamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.igamma_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.igammac.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.igammac_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.matrix_exp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mvlgamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mvlgamma_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.orgqr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ormqr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.cholesky_ex.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.inv_ex.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.ndtr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.testing.make_tensor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._assert.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.mvlgamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.ormqr.md
Labels: contributor, PaddlePaddle Hackathon

#6875 【Hackathon 7th No.22】NO.22 在 paddle.audio.functional.get_window 中支持 bartlett 、 kaiser 和 nuttall 窗函数
  docs/api/paddle/audio/features/LogMelSpectrogram_cn.rst
  docs/api/paddle/audio/features/MFCC_cn.rst
  docs/api/paddle/audio/features/MelSpectrogram_cn.rst
  docs/api/paddle/audio/features/Spectrogram_cn.rst
  docs/api/paddle/audio/functional/get_window_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6904 add more notice to contribution guide
  docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md
Labels: contributor, HappyOpenSource

#6874 【Hackathon 7th No.23】NO.23 为 Paddle 新增 ParameterDict API
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/ParameterDict_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.ParameterDict.md
Labels: contributor, PaddlePaddle Hackathon

#6893 【Hackathon 7th No.42】NO.42 为 Paddle 代码转换工具新增 API 转换规则（第 9 组）
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bitwise_left_shift.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bitwise_left_shift_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bitwise_right_shift.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bitwise_right_shift_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.col_indices.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.crow_indices.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.data_ptr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dim_order.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_sparse_csr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.itemsize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nbytes.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.stride.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.to_sparse_coo.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.bitwise_left_shift.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.bitwise_right_shift.md
Labels: contributor, PaddlePaddle Hackathon

#6896 [Docathon][Add API Legend No.9]modified flatten lenged
  docs/images/api_legend/flatten.png
Labels: contributor, HappyOpenSource Pro

#6912 [Docathon][Add API Legend No.56,57] + add new images and change api document
  docs/api/paddle/column_stack_cn.rst
  docs/api/paddle/row_stack_cn.rst
  docs/images/api_legend/column_stack.png
  docs/images/api_legend/row_stack.png
Labels: contributor, HappyOpenSource

#6898 新增 torchvision 和 paddle.vision 的对应关系
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.diagonal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.CIFAR10.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.ImageFolder.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.MNIST.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transform.RandomVerticalFlip.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transform.functional.normalize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transform.functional.pad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transform.functional.resize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.CenterCrop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.Compose.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.Grayscale.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.Normalize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.Pad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomAffine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomCrop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomErasing.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomHorizontalFlip.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomPerspective.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomResizedCrop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.RandomRotation.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.Resize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.ToTensor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.adjust_brightness.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.adjust_contrast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.adjust_hue.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.affine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.center_crop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.crop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.erase.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.hflip.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.perspective.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.to_grayscale.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.to_tensor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.vflip.md
  docs/guides/model_convert/convert_from_pytorch/tools/validate_mapping_files.py
Labels: contributor

#6913 [Docathon][Add API Legend No.42] as_complex
  docs/api/paddle/as_complex_cn.rst
  docs/images/api_legend/as_complex.png
Labels: contributor, HappyOpenSource

#6892 [NVIDIA] Refine API difference of `all_gather_object`
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.all_gather_object.md
Labels: contributor

#6887 【Hackathon 7th No.41】NO.41 为 Paddle 代码转换工具新增 API 转换规则（第 8 组）
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cauchy_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.geometric_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_inference.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.random_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.optim.DistributedOptimizer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.remote.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.chi2.Chi2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.constraints.Constraint.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.gamma.Gamma.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.lkj_cholesky.LKJCholesky.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.poisson.Poisson.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.studentT.StudentT.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.PositiveDefiniteTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.is_inference.md
Labels: contributor, PaddlePaddle Hackathon

#6917 SlogDeterminant kernel support complex 易用性提升
  docs/api/paddle/linalg/slogdet_cn.rst
Labels: contributor

#6914 [Docathon][Add API Legend No.43]为as_real增加图例
  docs/api/paddle/as_real_cn.rst
  docs/images/api_legend/as_real.png
Labels: contributor, HappyOpenSource

#6922 新增 torchvision 和 paddle.vision 的对应关系（第二批）
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.CIFAR10.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.CIFAR100.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.FashionMNIST.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.Flowers102.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.MNIST.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.VOCDetection.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.io.decode_jpeg.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.io.read_file.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.DeformConv2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.RoIAlign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.RoIPool.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.deform_conv2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.nms.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.ps_roi_pool.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.roi_align.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.roi_pool.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transform.functional.normalize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.ColorJitter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.rotate.md
Labels: contributor

#6916 更新 tensor 数学操作相关 API 中文文档 - 易用性提升
  docs/api/paddle/abs_cn.rst
  docs/api/paddle/add_cn.rst
  docs/api/paddle/add_n_cn.rst
  docs/api/paddle/addmm_cn.rst
  docs/api/paddle/clip_cn.rst
  docs/api/paddle/conj_cn.rst
  docs/api/paddle/cumprod_cn.rst
  docs/api/paddle/cumsum_cn.rst
  docs/api/paddle/diagonal_cn.rst
  docs/api/paddle/divide_cn.rst
  docs/api/paddle/exp_cn.rst
  docs/api/paddle/expm1_cn.rst
  docs/api/paddle/fmax_cn.rst
  docs/api/paddle/fmin_cn.rst
  docs/api/paddle/greater_equal_cn.rst
  docs/api/paddle/greater_than_cn.rst
  docs/api/paddle/heaviside_cn.rst
  docs/api/paddle/kron_cn.rst
  docs/api/paddle/less_equal_cn.rst
  docs/api/paddle/less_than_cn.rst
  docs/api/paddle/logaddexp_cn.rst
  docs/api/paddle/logical_and_cn.rst
  docs/api/paddle/logical_not_cn.rst
  docs/api/paddle/logical_or_cn.rst
  docs/api/paddle/logical_xor_cn.rst
  docs/api/paddle/max_cn.rst
  docs/api/paddle/maximum_cn.rst
  docs/api/paddle/median_cn.rst
  docs/api/paddle/min_cn.rst
  docs/api/paddle/minimum_cn.rst
  docs/api/paddle/multiply_cn.rst
  docs/api/paddle/nanmean_cn.rst
  docs/api/paddle/nanquantile_cn.rst
  docs/api/paddle/nansum_cn.rst
  docs/api/paddle/neg_cn.rst
  docs/api/paddle/not_equal_cn.rst
  docs/api/paddle/pow_cn.rst
  docs/api/paddle/prod_cn.rst
  docs/api/paddle/put_along_axis_cn.rst
  docs/api/paddle/quantile_cn.rst
  docs/api/paddle/remainder_cn.rst
  docs/api/paddle/round_cn.rst
  docs/api/paddle/scale_cn.rst
  docs/api/paddle/sign_cn.rst
  docs/api/paddle/signbit_cn.rst
  docs/api/paddle/square_cn.rst
  docs/api/paddle/subtract_cn.rst
  docs/api/paddle/sum_cn.rst
  docs/api/paddle/take_along_axis_cn.rst
  docs/api/paddle/trace_cn.rst
Labels: contributor
