Repository PaddlePaddle/docs, pull requests merged in 2024-12, with the labels that each got.

#6994 【SCU】【Add API Legend No.54】Add the legend of diagonal_scatter_cn -part
  docs/api/paddle/diagonal_scatter_cn.rst
  docs/images/api_legend/diagonal_scatter.png
Labels: contributor, HappyOpenSource Pro

#6951 [Docathon][Add API Legend No.40、51] add a figure of unfold method and update unfold_cn.rst -part
  docs/api/paddle/unfold_cn.rst
  docs/api/paddle/unsqueeze_cn.rst
  docs/images/api_legend/unfold.png
  docs/images/api_legend/unsqueeze.png
Labels: contributor, HappyOpenSource

#6941 [Docathon][Add API Legend No.2]
  docs/api/paddle/broadcast_tensors_cn.rst
  docs/images/api_legend/broadcast.png
Labels: contributor, HappyOpenSource

#7002 【Hackathon 7th No.25】为 Paddle 新增 sparse_dim/dense_dim
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dense_dim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sparse_dim.md
Labels: contributor, PaddlePaddle Hackathon

#7001 【Paddle Tensor No.26】add svdvals docs
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/svdvals_cn.rst
Labels: contributor, HappyOpenSource

#6859 Add docs for tensorrt and cuda_archs version
  docs/api/paddle/version/Overview_cn.rst
  docs/api/paddle/version/cuda_archs_cn.rst
  docs/api/paddle/version/show_cn.rst
  docs/api/paddle/version/tensorrt_cn.rst
Labels: contributor

#7008 Change LoDTensorBlockingQueue to DenseTensorBlockingQueue
  docs/design/concepts/python_data_feeding.md
Labels: contributor, PaddlePaddle Hackathon

#6886 【Hackathon 7th PPSCI No.12】Adam、AdamW 优化器支持 amsgrad -part
  docs/api/paddle/optimizer/AdamW_cn.rst
  docs/api/paddle/optimizer/Adam_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Adam.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.AdamW.md
Labels: contributor, PaddlePaddle Hackathon

#7007 Fix API docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.GRUCell.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LSTMCell.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.RNNCell.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.autograd.grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.frexp.md
Labels: contributor

#7010 Add convert rules related to `torch.nn.Lazy*`
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyBatchNorm1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyBatchNorm2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyBatchNorm3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConv1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConv2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConv3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConvTranspose1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConvTranspose2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyConvTranspose3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyInstanceNorm1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyInstanceNorm2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyInstanceNorm3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LazyLinear.md
Labels: contributor

#7009 `histogram/histogram_bin_edges` support float `min/max` 易用性提升
  docs/api/paddle/histogram_bin_edges_cn.rst
  docs/api/paddle/histogram_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.histogram.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.histogram.md
Labels: contributor

#6964 [SCU][Add API Legend No.21] Add the legend of scatter_nd_add_cn
  docs/api/paddle/scatter_nd_add_cn.rst
  docs/images/api_legend/scatter_nd_add.png
Labels: contributor, HappyOpenSource Pro

#6988 [SCU][Docathon][Add API Legend No.44] repeat_interleave -part
  docs/api/paddle/repeat_interleave_cn.rst
  docs/images/api_legend/repeat_interleave.png
Labels: contributor, HappyOpenSource Pro

#6967 [SCU][Docathon][Add API Legend No.39]add the picture of unique-consecutive -part
  docs/api/paddle/unique_consecutive_cn.rst
  docs/images/api_legend/unique_consecutive.png
Labels: contributor, HappyOpenSource Pro

#6978 [SCU][Docathon][Add API Legend No.7] expand
  docs/api/paddle/expand_cn.rst
  docs/images/api_legend/expand.png
Labels: contributor, HappyOpenSource Pro

#6974 [Docathon][BUPT][Add API Legend No.24]为slice_scatter添加图例 -part
  docs/api/paddle/slice_scatter_cn.rst
  docs/images/api_legend/slice_scatter.png
Labels: contributor, HappyOpenSource

#7023 文档格式修改
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.ormqr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.ContinuousBernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.inv_ex.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.RNN.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.ormqr.md
Labels: contributor

#6991 [Docathon][Add API Legend No.16] Add legend and update doc for atleast_2d
  docs/api/paddle/atleast_2d_cn.rst
  docs/images/api_legend/atleast_2d.png
Labels: contributor, HappyOpenSource

#7024 fix: redraw shard_index.png
  docs/images/api_legend/shard_index.png
Labels: contributor, HappyOpenSource

#7022 【Hackathon 7th No.19】NO.19为 Paddle 新增 load_state_dict_from_url API
  docs/api/paddle/hub/load_state_dict_from_url_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#7025 映射表更新/文档对齐
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.flash_attn_interface.flash_attn_unpadded_func.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.transforms.functional.normalize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.StoppingCriteriaList.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7027 `nn.Embedding/F.embedding` support `scale_grad_by_freq` 易用性提升
  docs/api/paddle/nn/Embedding_cn.rst
  docs/api/paddle/nn/functional/embedding_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.embedding.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Embedding.md
Labels: contributor

#7026 【Hackathon 7th No.20】为 Paddle 新增 Tensor.resize_
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.resize_.md
Labels: contributor, PaddlePaddle Hackathon

#7013 【Hackathon 7th No.21】为 Paddle 新增 reset_max_memory_reserved/reset_max_memory_allocated API
  docs/api/paddle/device/Overview_cn.rst
  docs/api/paddle/device/cuda/max_memory_allocated_cn.rst
  docs/api/paddle/device/cuda/max_memory_reserved_cn.rst
  docs/api/paddle/device/cuda/reset_max_memory_allocated_cn.rst
  docs/api/paddle/device/cuda/reset_max_memory_reserved_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.reset_max_memory_allocated.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.reset_max_memory_reserved.md
Labels: contributor, PaddlePaddle Hackathon

#6945 [Docathon][Add API Legend No.38]add the legend of unique
  docs/api/paddle/unique_cn.rst
  docs/images/api_legend/unique_1.png
  docs/images/api_legend/unique_2.png
  docs/images/api_legend/unique_3.png
Labels: contributor, HappyOpenSource Pro
