Repository PaddlePaddle/docs, pull requests merged in 2024-05, with the labels that each got.

#6623 API improvement for paddle.argsort and paddle.sort 易用性提升
  docs/api/paddle/argsort_cn.rst
  docs/api/paddle/sort_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.argsort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.argsort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.sort.md
Labels: contributor

#6636 API Improvement for paddle.nn.functional.group_norm and paddle.nn.GroupNorm 易用性提升
  docs/api/paddle/nn/GroupNorm_cn.rst
  docs/api/paddle/nn/functional/group_norm_cn.rst
Labels: contributor

#6595 [Docathon][Add Overview Doc No.15-17] add doc of docathon 15-17
  docs/api/paddle/distributed/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6640 Fix isinstance typos
  docs/guides/jit/limitations_cn.md
Labels: contributor, HappyOpenSource

#6631 remove execution_strategy
  docs/api/paddle/distributed/fleet/DistributedStrategy_cn.rst
Labels: contributor, HappyOpenSource

#6630 [Docathon][Remove File No.17-19、27-28]
  docs/guides/model_convert/load_old_format_model_cn.rst
  docs/guides/model_convert/migration_cn.rst
  docs/guides/model_convert/paddle_api_mapping_cn.rst
  docs/guides/model_convert/update_cn.md
Labels: contributor, HappyOpenSource

#6615 【Hackathon 6th No.10】Add isposinf / isneginf / isreal API to Paddle - part
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/isneginf_cn.rst
  docs/api/paddle/isposinf_cn.rst
  docs/api/paddle/isreal_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6625 [Docathon]Add a new API documentation (paddle.renorm)
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/renorm_cn.rst
Labels: contributor, HappyOpenSource

#6634 【Hackathon 6th No. 7】Add sinc / sinc_ API to Paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/sinc__cn.rst
  docs/api/paddle/sinc_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6642 API Improvement for paddle.nn.initializer.TruncatedNormal 易用性提升
  docs/api/paddle/nn/initializer/TruncatedNormal_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/init/torch.nn.init.trunc_normal_.md
Labels: contributor

#6587 【Hackathon 6th No.4】Add ormqr docs API to Paddle -part
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/ormqr_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6643 【Hackathon 6th No.13】为 Paddle 新增 RAdam / NAdam API
  docs/api/paddle/optimizer/NAdam_cn.rst
  docs/api/paddle/optimizer/Overview_cn.rst
  docs/api/paddle/optimizer/RAdam_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6645 【complex op No.33】abs_coo/abs_csr(sparse)
  docs/api/paddle/sparse/abs_cn.rst
Labels: contributor

#6613 [Docathon][Remove File No.10-16、29-32、56-58]清理未暴露在 sphinx toctree 下的文档
  docs/advanced_guide/index_cn.rst
  docs/advanced_guide/index_en.rst
  docs/advanced_guide/performance_improving/amp/amp.md
  docs/advanced_guide/performance_improving/index_cn.rst
  docs/advanced_guide/performance_improving/index_en.rst
  docs/advanced_guide/performance_improving/inference_improving/paddle_xpu_infer_cn.md
  docs/advanced_guide/performance_improving/multinode_training_improving/cpu_train_best_practice.rst
  docs/advanced_guide/performance_improving/multinode_training_improving/cpu_train_best_practice_en.rst
  docs/advanced_guide/performance_improving/multinode_training_improving/dist_training_gpu.rst
  docs/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_low_bandwidth_dgc.md
  docs/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_recompute.rst
  docs/advanced_guide/performance_improving/multinode_training_improving/gpu_training_with_recompute_en.rst
  docs/advanced_guide/performance_improving/multinode_training_improving/images/dgc_resnet50_acc1.png
  docs/advanced_guide/performance_improving/multinode_training_improving/images/dgc_with_momentum_correction.png
  docs/advanced_guide/performance_improving/multinode_training_improving/images/dgc_without_momentum_correction.png
  docs/advanced_guide/performance_improving/multinode_training_improving/images/recompute.png
  docs/dev_guides/api_contributing_guides/new_cpp_op_en.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_notes_en.md
  docs/faq/train_cn.md
  docs/guides/performance_improving/analysis_tools/benchmark_cn.md
  docs/guides/performance_improving/analysis_tools/cpu_profiling_cn.md
  docs/guides/performance_improving/analysis_tools/cpu_profiling_en.md
  docs/guides/performance_improving/analysis_tools/host_memory_profiling_en.md
  docs/guides/performance_improving/analysis_tools/index_cn.rst
  docs/guides/performance_improving/analysis_tools/index_en.rst
  docs/guides/performance_improving/analysis_tools/nvvp1.png
  docs/guides/performance_improving/analysis_tools/nvvp2.png
  docs/guides/performance_improving/analysis_tools/nvvp3.png
  docs/guides/performance_improving/analysis_tools/nvvp4.png
  docs/guides/performance_improving/analysis_tools/pprof_1.png
  docs/guides/performance_improving/analysis_tools/pprof_2.png
  docs/guides/performance_improving/analysis_tools/timeline.jpeg
  docs/guides/performance_improving/analysis_tools/timeline_cn.md
  docs/guides/performance_improving/analysis_tools/timeline_en.md
  docs/guides/performance_improving/device_switching.md
  docs/guides/performance_improving/memory_optimize.rst
  docs/guides/performance_improving/memory_optimize_en.rst
  docs/guides/performance_improving/paddle_tensorrt_infer.md
  docs/guides/performance_improving/paddle_tensorrt_infer_en.md
  docs/guides/performance_improving/quantization.md
Labels: contributor, HappyOpenSource

#6648 【Hackathon 6th No.11】为 Paddle 新增 bernoulli_ API - part
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/bernoulli__cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6649 [Fix] pre-build pytorch_api_mapping_cn.md to fix display bug
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#6653 【Hackathon 6th No.10】Update paddle.searchsorted -part
  docs/api/paddle/searchsorted_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6654 API Improvement for paddle.nn.layer.state_dict 易用性提升
  docs/api/paddle/nn/Layer_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.state_dict.md
Labels: contributor

#6656 【映射文档】在映射主目录中补全已有文档的条目
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.UpsamplingBilinear2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.functional.softmax.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6662 API Improvement: fix paddle.median 易用性提升
  docs/api/paddle/median_cn.rst
Labels: contributor
