Repository PaddlePaddle/docs, pull requests merged in 2024-09, with the labels that each got.

#6812 [Docathon][Add API Legend No.23]
  docs/api/paddle/slice_cn.rst
  docs/images/api_legend/slice.png
Labels: contributor, HappyOpenSource

#6771 [Docathon][Add API Legend No.8]
  docs/api/paddle/expand_as_cn.rst
  docs/images/api_legend/expand_as.png
Labels: contributor, HappyOpenSource

#6816 [Docathon][Add API Legend No.10 flip]
  docs/api/paddle/flip_cn.rst
  docs/images/api_legend/flip.png
Labels: contributor, HappyOpenSource

#6842 [Docathon][Add API Legend No.60 dstack]
  docs/api/paddle/dstack_cn.rst
  docs/images/api_legend/dstack.png
Labels: contributor, HappyOpenSource

#6844 Fix API docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.hsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tensor_split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.dsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.hsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.tensor_split.md
Labels: contributor

#6853 Fix padding_idx range limit in nn.Embedding
  docs/api/paddle/nn/Embedding_cn.rst
Labels: contributor, HappyOpenSource

#6855 【complex op No.50】tan_coo/tan_csr(sparse)
  docs/api/paddle/sparse/tan_cn.rst
Labels: contributor

#6852 易用性提升已修改的58个API核对 - part3
  docs/api/paddle/finfo_cn.rst
  docs/api/paddle/iinfo_cn.rst
  docs/api/paddle/set_default_dtype_cn.rst
Labels: contributor

#6833 F.pad add attribute `pad_from_left_axis` and improvement 易用性提升
  docs/api/paddle/nn/functional/pad_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.pad.md
Labels: contributor

#6840 [Docathon][Add API Legend No.41 unstack]
  docs/api/paddle/unstack_cn.rst
  docs/images/api_legend/unstack.png
Labels: contributor, HappyOpenSource

#6862 【complex op No.47】sinh_coo/sinh_csr(sparse)
  docs/api/paddle/sparse/sinh_cn.rst
Labels: contributor

#6849 易用性提升已修改的58个API核对 - part2
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/histogram_bin_edges_cn.rst
  docs/api/paddle/nn/Embedding_cn.rst
  docs/api/paddle/nn/ThresholdedReLU_cn.rst
  docs/api/paddle/nn/functional/embedding_cn.rst
  docs/api/paddle/nn/functional/thresholded_relu__cn.rst
  docs/api/paddle/nn/functional/thresholded_relu_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.histogram.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.embedding.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.threshold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Embedding.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Threshold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.histogram.md
Labels: contributor

#6860 paddle.linalg.matrix_rank add attributes `atol` and `rtol` and Fix `paddle.diff` 易用性提升
  docs/api/paddle/linalg/matrix_rank_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diff.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_rank.md
Labels: contributor

#6864 Fix ci parameter checking script
  ci_scripts/check_api_parameters.py
  ci_scripts/check_api_parameters.sh
  ci_scripts/ci_start.sh
  docs/api/paddle/atan2_cn.rst
  docs/api/paddle/bitwise_and_cn.rst
  docs/api/paddle/bitwise_not_cn.rst
  docs/api/paddle/bitwise_or_cn.rst
  docs/api/paddle/bitwise_xor_cn.rst
  docs/api/paddle/deg2rad_cn.rst
  docs/api/paddle/einsum_cn.rst
  docs/api/paddle/erfinv_cn.rst
  docs/api/paddle/expm1_cn.rst
  docs/api/paddle/gcd_cn.rst
  docs/api/paddle/get_cuda_rng_state_cn.rst
  docs/api/paddle/get_default_dtype_cn.rst
  docs/api/paddle/histogramdd_cn.rst
  docs/api/paddle/index_fill__cn.rst
  docs/api/paddle/index_fill_cn.rst
  docs/api/paddle/index_put__cn.rst
  docs/api/paddle/index_put_cn.rst
  docs/api/paddle/inner_cn.rst
  docs/api/paddle/is_floating_point_cn.rst
  docs/api/paddle/lcm_cn.rst
  docs/api/paddle/lerp_cn.rst
  docs/api/paddle/numel_cn.rst
  docs/api/paddle/pdist_cn.rst
  docs/api/paddle/put_along_axis_cn.rst
  docs/api/paddle/rad2deg_cn.rst
  docs/api/paddle/reduce_as_cn.rst
  docs/api/paddle/renorm_cn.rst
  docs/api/paddle/rot90_cn.rst
  docs/api/paddle/save_cn.rst
  docs/api/paddle/select_scatter_cn.rst
  docs/api/paddle/take_along_axis_cn.rst
  docs/api/paddle/take_cn.rst
  docs/api/paddle/unstack_cn.rst
Labels: contributor, HappyOpenSource

#6872 修复docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.nn.parameter.Parameter.md 表格错乱显示问题
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.nn.parameter.Parameter.md
Labels: contributor, HappyOpenSource

#6883 【complex op No.36-39,41,42,49,51】asin_coo/asin_csr(sparse),asinh_coo/asinh_csr(sparse),atan_coo/atan_csr(sparse),atanh_coo/atanh_csr(sparse),expm1_coo/expm1_csr(sparse),log1p_coo/log1p_csr(sparse),square_coo/square_csr(sparse),tanh_coo/tanh_csr(sparse)
  docs/api/paddle/sparse/asin_cn.rst
  docs/api/paddle/sparse/asinh_cn.rst
  docs/api/paddle/sparse/atan_cn.rst
  docs/api/paddle/sparse/atanh_cn.rst
  docs/api/paddle/sparse/expm1_cn.rst
  docs/api/paddle/sparse/log1p_cn.rst
  docs/api/paddle/sparse/square_cn.rst
  docs/api/paddle/sparse/tanh_cn.rst
Labels: contributor, HappyOpenSource

#6881 Unpool/Unpool3d kernel support input of int64 `indices` 易用性提升
  docs/api/paddle/nn/MaxUnPool1D_cn.rst
  docs/api/paddle/nn/MaxUnPool2D_cn.rst
  docs/api/paddle/nn/MaxUnPool3D_cn.rst
  docs/api/paddle/nn/functional/max_unpool1d_cn.rst
  docs/api/paddle/nn/functional/max_unpool2d_cn.rst
  docs/api/paddle/nn/functional/max_unpool3d_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.max_unpool3d.md
Labels: contributor

#6870 Fix docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.is_bf16_supported.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.Binomial.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.ContinuousBernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.Exponential.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.MultivariateNormal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.channel_shuffle.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.gammainc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.gammaincc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.__version__.split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.amp.autocast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.__version__.split.md
Labels: contributor

#6876 【Hackathon 7th No.31】NO.31 为 paddle.sparse.sparse_csr_tensor进行功能增强
  docs/api/paddle/sparse/sparse_csr_tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.sparse_csr_tensor.md
Labels: contributor, PaddlePaddle Hackathon

#6786 [Docathon][Add API Legend No.6]add the picture of crop
  docs/api/paddle/crop_cn.rst
  docs/images/api_legend/crop.png
Labels: contributor, HappyOpenSource

#6878 【Hackathon 7th No.39】为 Paddle 代码转换工具新增 API 转换规则（第 6 组）-part
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.lp_pool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.lp_pool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.scaled_dot_product_attention.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.threshold_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveLogSoftmaxWithLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CircularPad3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LPPool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LPPool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Softmin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.utils.parametrizations.weight_norm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.NAdam.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.RAdam.md
  docs/guides/model_convert/convert_from_pytorch/tools/validate_mapping_files.py
Labels: contributor, PaddlePaddle Hackathon

#6879 【Hackathon 7th No.36】为 Paddle 代码转换工具新增 API 转换规则（第 3 组） part 1
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.blackman.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.cosine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.exponential.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.gaussian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.general_cosine.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.general_hamming.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.hamming.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/audio/functional/torch.signal.windows.hann.md
Labels: contributor, PaddlePaddle Hackathon

#6880 【Hackathon 7th No.35】为 Paddle 代码转换工具新增 API 转换规则（第 2 组）-part
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addbmm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addcdiv_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addmv_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addr_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.baddbmm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.copysign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.copysign_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.erfc_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fix_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.fmod_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.int_repr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.mul_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sinc_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.t_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.transpose_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.xlogy_.md
Labels: contributor, PaddlePaddle Hackathon

#6890 【Hackathon 7th No.36】为 Paddle 代码转换工具新增 API 转换规则（第 3 组）- part2
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.blackman_window.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.frombuffer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.get_num_interop_threads.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.get_num_threads.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.hamming_window.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.hann_window.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.set_num_interop_threads.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.set_num_threads.md
Labels: contributor, PaddlePaddle Hackathon
