Repository PaddlePaddle/docs, pull requests merged in 2024-06, with the labels that each got.

#6670 【Hackathon 6th No.9】Update meshgrid to support complex dtype -part
  docs/api/paddle/meshgrid_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6672 【映射文档】添加 api 别名表格
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6668 Add files via upload
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.select_scatter.md
Labels: contributor

#6677 【Hackathon 6th No.31】normal api support complex -part
  docs/api/paddle/normal_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6661 【Hackathon 6th No.10】Add isin API to Paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/isin_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6664 【Hackathon 6th No.11】Add log_normal and log_normal_ API to Paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/log_normal__cn.rst
  docs/api/paddle/log_normal_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.log_normal_.md
Labels: contributor, PaddlePaddle Hackathon

#6676 【Type Hints】将 typehints 显示在描述中而不是函数签名中
  ci_scripts/doc-build-config/en/conf.py
  ci_scripts/doc-build-config/zh/conf.py
  docs/api/paddle/audio/save_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6657 【Hackathon 6th No.6】为 Paddle 新增 StudentT API
  docs/api/paddle/distribution/Overview_cn.rst
  docs/api/paddle/distribution/StudentT_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6674 【Hackathon 6th No.2】为 Paddle 新增 cholesky_inverse API
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/cholesky_inverse_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6663 【Hackathon 6th No.17】为 Paddle 新增 sparse.mask_as API
  docs/api/paddle/sparse/Overview_cn.rst
  docs/api/paddle/sparse/mask_as_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sparse_mask.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6680 [Typing] not render type ignore
  ci_scripts/doc-build-config/en/conf.py
  docs/api/copy_codes_from_en_doc.py
Labels: contributor

#6651 【Hackathon 6th No.3】为 Paddle 新增 ZeroPad1D / ZeroPad3D / block_diag API
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/block_diag_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/ZeroPad1D_cn.rst
  docs/api/paddle/nn/ZeroPad3D_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6606 【Hackathon 6th No.1】Add AdaptiveLogSoftmaxWithLoss docs API to Paddle
  docs/api/paddle/nn/AdaptiveLogSoftmaxWithLoss_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/adaptive_log_softmax_with_loss_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6678 [Typing] 增加文档《Paddle 中的类型提示与 Q&A》
  docs/dev_guides/api_contributing_guides/images/zeros_python_api.png
  docs/dev_guides/api_contributing_guides/images/zeros_python_api_doctest.png
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
  docs/dev_guides/style_guide_and_references/code_typing_writing_specification_cn.md
  docs/dev_guides/style_guide_and_references/index_cn.rst
Labels: contributor

#6684 [docs] 更新对昆仑芯的描述为正式名称的`昆仑芯`
  docs/eval/evaluation_of_docs_system.md
  docs/guides/06_distributed_training/deployment_cn.rst
  docs/guides/06_distributed_training/ps/cluster_overview_ps_cn.rst
  docs/guides/beginner/train_eval_predict_cn.ipynb
  docs/guides/hardware_support/hardware_info_cn.md
  docs/guides/hardware_support/index_cn.rst
  docs/guides/hardware_support/xpu/example_cn.md
  docs/guides/hardware_support/xpu/index_cn.rst
  docs/guides/hardware_support/xpu/install_cn.md
  docs/guides/hardware_support/xpu/support_cn.md
  docs/guides/infer/inference/inference_cn.md
  docs/hardware_support/hardware_info_cn.md
  docs/hardware_support/index_cn.rst
  docs/hardware_support/xpu/index_cn.rst
  docs/hardware_support/xpu/paddle_tutorial_cn.md
  docs/hardware_support/xpu/suite_tutorial_cn.md
  docs/install/install_xpu_cn.md
  docs/release_note_cn.md
Labels: contributor

#6691 【映射文档】更新别名表格的维护与生成方式
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6693 增加3.0.0b0版本使用conda环境import paddle报错问题的解决方案
  docs/faq/install_cn.md
Labels: contributor

#6694 【Hackathon 6th Fundable Projects 4 No.3、5】remove execution_strategy and parallel_executor
  docs/api_guides/index_cn.rst
  docs/api_guides/index_en.rst
  docs/api_guides/low_level/executor.rst
  docs/api_guides/low_level/executor_en.rst
  docs/api_guides/low_level/layers/data_in_out_en.rst
  docs/api_guides/low_level/parallel_executor.rst
  docs/api_guides/low_level/parallel_executor_en.rst
  docs/design/concepts/images/parallel_executor_overview.dot
  docs/design/concepts/images/parallel_executor_overview.png
  docs/design/concepts/index_cn.rst
  docs/design/concepts/index_en.rst
  docs/design/concepts/parallel_executor.md
  docs/faq/distributed_cn.md
  docs/guides/flags/executor_cn.rst
  docs/guides/flags/executor_en.rst
Labels: contributor, PaddlePaddle Hackathon

#6690 [docs] 修复 api 文档中函数声明的名称【Part5】
  docs/api/paddle/regularizer/L2Decay_cn.rst
  docs/api/paddle/sparse/nn/Conv2D_cn.rst
  docs/api/paddle/sparse/nn/MaxPool3D_cn.rst
  docs/api/paddle/vision/get_image_backend_cn.rst
  docs/api/paddle/vision/image_load_cn.rst
  docs/api/paddle/vision/models/AlexNet__upper_cn.rst
  docs/api/paddle/vision/models/GoogLeNet__upper_cn.rst
  docs/api/paddle/vision/models/SqueezeNet_cn.rst
  docs/api/paddle/vision/set_image_backend_cn.rst
Labels: contributor, HappyOpenSource

#6689 [docs] 修复 api 文档中函数声明的名称【Part4】
  docs/api/paddle/nn/MSELoss_cn.rst
  docs/api/paddle/nn/MaxPool3D_cn.rst
  docs/api/paddle/nn/PixelShuffle_cn.rst
  docs/api/paddle/nn/PixelUnshuffle_cn.rst
  docs/api/paddle/nn/RNNCellBase_cn.rst
  docs/api/paddle/nn/Unflatten_cn.rst
  docs/api/paddle/nn/UpsamplingBilinear2D_cn.rst
  docs/api/paddle/nn/UpsamplingNearest2D_cn.rst
  docs/api/paddle/optimizer/Optimizer_cn.rst
  docs/api/paddle/regularizer/L1Decay_cn.rst
Labels: contributor, HappyOpenSource

#6686 [docs] 修复 api 文档中函数声明的名称【Part1】
  docs/api/paddle/DataParallel_cn.rst
  docs/api/paddle/distributed/destroy_process_group_cn.rst
  docs/api/paddle/distributed/get_group_cn.rst
  docs/api/paddle/distributed/get_rank_cn.rst
  docs/api/paddle/distributed/new_group_cn.rst
  docs/api/paddle/distributed/to_static_cn.rst
  docs/api/paddle/distributed/unshard_dtensor_cn.rst
  docs/api/paddle/distributed/wait_cn.rst
  docs/api/paddle/incubate/LookAhead_cn.rst
  docs/api/paddle/incubate/xpu/resnet_block/ResNetBasicBlock_cn.rst
Labels: contributor, HappyOpenSource

#6688 [docs] 修复 api 文档中函数声明的名称【Part3】
  docs/api/paddle/nn/AdaptiveAvgPool2D_cn.rst
  docs/api/paddle/nn/AdaptiveAvgPool3D_cn.rst
  docs/api/paddle/nn/AdaptiveMaxPool1D_cn.rst
  docs/api/paddle/nn/Dropout3D_cn.rst
  docs/api/paddle/nn/Dropout_cn.rst
  docs/api/paddle/nn/Flatten_cn.rst
  docs/api/paddle/nn/Fold_cn.rst
  docs/api/paddle/nn/FractionalMaxPool3D_cn.rst
  docs/api/paddle/nn/Hardsigmoid_cn.rst
  docs/api/paddle/nn/Hardswish_cn.rst
  docs/api/paddle/nn/LocalResponseNorm_cn.rst
  docs/api/paddle/nn/MaxPool1D_cn.rst
  docs/api/paddle/nn/MaxPool2D_cn.rst
Labels: contributor, HappyOpenSource

#6700 [Typing] 修改 saved_tensors_hooks 示例代码格式
  docs/api/paddle/autograd/saved_tensors_hooks_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6679 【Hackathon 6th No.8】NO.8 为 Paddle 新增 FeatureAlphaDropout API
  docs/api/paddle/nn/FeatureAlphaDropout_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/feature_alpha_dropout_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.feature_alpha_dropout.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.FeatureAlphaDropout.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon
