Repository PaddlePaddle/docs, pull requests merged in 2024-07, with the labels that each got.

#6696 【映射文档】更新部分修复的 API 文档
  docs/api/paddle/nn/CrossEntropyLoss_cn.rst
  docs/api/paddle/nn/functional/cross_entropy_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.cross_entropy.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CrossEntropyLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LSTM.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Unfold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.all.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.any.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.diff.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.feature_alpha_dropout.md
Labels: contributor

#6735 【Hackathon 6th No.31】paddle.distribution.Normal/paddle.nn.initializer.Normal/paddle.randn/paddle.standard_normal support complex normal distribution
  docs/api/paddle/distribution/Normal_cn.rst
  docs/api/paddle/nn/initializer/Normal_cn.rst
  docs/api/paddle/randn_cn.rst
  docs/api/paddle/standard_normal_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6749 【Hackathon 6th No.28】为 paddle.round 进行功能增强-中文文档修改-part
  docs/api/paddle/round_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6632 [Docathon][Remove File No.47-55]清理未暴露在 sphinx toctree 下的文档
  docs/dev_guides/index_en.rst
Labels: contributor, HappyOpenSource

#6504 [Docathon][Add Overview Doc No.19-21] add doc of docathon 19-21
  docs/api/paddle/nn/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6751 【Hackathon 6th No.9】Add cartesian_prod API to Paddle
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/cartesian_prod_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6752 upgrade pytorch-paddle mapping table generating process
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6760 【Hackathon 6th No.25】[Typing] 为 paddle.histogram 进行功能对齐与功能增强
  docs/api/paddle/histogram_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6737 Update AvgPool3D_cn.rst
  docs/api/paddle/nn/AvgPool3D_cn.rst
Labels: contributor, HappyOpenSource

#6775 paddle.io.BatchSampler support iterable sampler 易用性提升
  docs/api/paddle/io/BatchSampler_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.BatchSampler.md
Labels: contributor

#6769 API improvement for Layer.named_sublayers\Layer.named_paramters\Layer.named_buffers 易用性提升
  docs/api/paddle/nn/Layer_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.named_buffers.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.named_modules.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.named_parameters.md
Labels: contributor

#6750 【映射文档】对齐与修复了部分映射文档 part 1
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/tril_cn.rst
  docs/api/paddle/triu_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.argsort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagonal_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.gather.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.median.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanmean.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanmedian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nonzero.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.permute.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.remainder_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.softmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.swapaxes.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.swapdims.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tile.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.true_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.broadcast_shapes.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.broadcast_tensors.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.broadcast_to.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.diff.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.triangular_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.tril.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.triu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.unbind.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.zeros.md
Labels: contributor

#6774 [Docathon][Add API Legend No.50 BUAA]
  docs/api/paddle/view_as_cn.rst
  docs/images/api_legend/view_as.png
Labels: contributor, HappyOpenSource Pro

#6782 【Hackathon 6th Fundable Projects 4 No.2】remove build_strategy useless attribution
  docs/api/paddle/static/BuildStrategy_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6785 [Docathon] Fix 亦或 -> 异或
  docs/guides/beginner/tensor_cn.md
Labels: contributor, HappyOpenSource

#6790 Modify pytorch write to paddle write and corrected a clerical error
  docs/api/paddle/vision/ops/roi_pool_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.max.md
Labels: contributor, HappyOpenSource

#6768 [Docathon][Add API Legend No.58 BUAA]
  docs/api/paddle/hstack_cn.rst
  docs/images/api_legend/hstack.png
Labels: contributor, HappyOpenSource Pro

#6792 fix docs bugs
  docs/guides/infer/inference/inference_cn.md
Labels: contributor, HappyOpenSource

#6794 Fix paddle.nn.Unfold docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Unfold.md
Labels: contributor, HappyOpenSource

#6765 [Docathon][Add API Legend No.4]
  docs/api/paddle/chunk_cn.rst
  docs/images/chunk.png
Labels: contributor, HappyOpenSource

#6799 【映射文档】清理未与 PaConvert 对齐的 13 篇映射文档
  docs/api/paddle/nn/functional/unfold_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.unfold.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.householder_product.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.BatchNorm3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.load_state_dict.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.register_forward_hook.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Adam.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.AdamW.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Adamax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.histogramdd.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.ones.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.randn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.slogdet.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6787 [Docathon][Add API Legend No.11 BUAA]
  docs/api/paddle/rot90_cn.rst
  docs/images/api_legend/rot90.png
Labels: contributor, HappyOpenSource Pro
