Repository PaddlePaddle/docs, pull requests merged in 2024-11, with the labels that each got.

#6925 【Hackathon 7th No.25】为 Paddle 新增 is_coalesced -part
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_coalesced.md
Labels: contributor, PaddlePaddle Hackathon

#6927 [SCU][Docathon][Add API Legend No.52]为masked_fill API添加图例
  docs/api/paddle/masked_fill_cn.rst
  docs/images/api_legend/masked_fill.png
Labels: contributor, HappyOpenSource Pro

#6926 映射文档修改
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sinc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.sinc_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.feature_alpha_dropout.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Conv2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.DataParallel.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.special.sinc.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.copysign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.subtract.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.vsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.nn.parameter.Parameter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/utils/torch.utils.data.DataLoader.md
Labels: contributor

#6936 Fix `Constraint` and `StudentT` model convert docs 易用性提升
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.constraints.Constraint.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.studentT.StudentT.md
Labels: contributor

#6932 【Paddle Tensor No.21】docs: Add docs for Tensor.bitwise_invert
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/bitwise_invert_cn.rst
Labels: contributor, HappyOpenSource

#6938 [Docathon][Add API Legend No.45] 给index_add添加图示
  docs/api/paddle/index_add_cn.rst
  docs/images/api_legend/index_add/index_add-1.png
  docs/images/api_legend/index_add/index_add-2.png
Labels: contributor, HappyOpenSource

#6946 Change LoDTensorArray to DenseTensorArray
  docs/api/paddle/static/nn/while_loop_cn.rst
  docs/design/concepts/python_data_feeding.md
  docs/design/concurrent/channel.md
  docs/guides/jit/case_analysis_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6947 Change LOD_TENSOR_ARRAY to DENSE_TENSOR_ARRAY
  docs/api_guides/low_level/layers/control_flow.rst
  docs/api_guides/low_level/layers/control_flow_en.rst
  docs/design/concepts/var_desc.md
Labels: contributor, PaddlePaddle Hackathon

#6961 更新表头和功能缺失备注
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#6935 【Hackathon 7th No.20】为 Paddle 新增 Tensor.set_ -part
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/Tensor_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_coalesced.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.set_.md
Labels: contributor, PaddlePaddle Hackathon

#6929 [SCU][Docathon][Add API Legend No.34]为transpose API添加图例 -part
  docs/api/paddle/transpose_cn.rst
  docs/images/api_legend/transpose.png
Labels: contributor, HappyOpenSource Pro

#6954 [Docathon][Add API Legend No.47] Add the legend of unflatten -part
  docs/api/paddle/unflatten_cn.rst
  docs/images/api_legend/unflatten.png
Labels: contributor, HappyOpenSource

#6933 [SCU][Docathon][Add API Legend No.31]为stack API添加图例
  docs/api/paddle/stack_cn.rst
  docs/images/api_legend/stack/stack-0.png
  docs/images/api_legend/stack/stack-1.png
Labels: contributor, HappyOpenSource Pro

#6976 Clean lod_tensor.md
  docs/design/concepts/index_cn.rst
  docs/design/concepts/index_en.rst
  docs/design/concepts/lod_tensor.md
  docs/design/motivation/refactorization.md
  docs/design/network/sequence_decoder.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6959 新增 torchvision 和 paddle.vision 的对应关系（第三批）
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.datasets.VOCDetection.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.alexnet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.densenet121.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.densenet161.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.densenet169.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.densenet201.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.googlenet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.inception_v3.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.mobilenet_v2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.mobilenet_v3_large.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.mobilenet_v3_small.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnet101.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnet152.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnet18.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnet34.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnet50.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnext101_64x4d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.resnext50_32x4d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.shufflenet_v2_x0_5.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.shufflenet_v2_x1_0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.shufflenet_v2_x1_5.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.shufflenet_v2_x2_0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.squeezenet1_0.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.squeezenet1_1.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg11.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg11_bn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg13.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg13_bn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg16.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg16_bn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg19.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.vgg19_bn.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.wide_resnet101_2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.models.wide_resnet50_2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/torchvision/torchvision.ops.DeformConv2d.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#6981 修复 `paddle.set_default_dtype` 文档
  docs/api/paddle/set_default_dtype_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.set_default_dtype.md
Labels: contributor

#6982 Fix distribution API with 0-D input parameters 易用性提升 -part2
  docs/api/paddle/distribution/Bernoulli_cn.rst
  docs/api/paddle/distribution/Beta_cn.rst
  docs/api/paddle/distribution/Binomial_cn.rst
  docs/api/paddle/distribution/Categorical_cn.rst
  docs/api/paddle/distribution/Cauchy_cn.rst
  docs/api/paddle/distribution/Chi2_cn.rst
  docs/api/paddle/distribution/ContinuousBernoulli_cn.rst
  docs/api/paddle/distribution/Dirichlet_cn.rst
  docs/api/paddle/distribution/Distribution_cn.rst
  docs/api/paddle/distribution/Exponential_cn.rst
  docs/api/paddle/distribution/Gamma_cn.rst
  docs/api/paddle/distribution/Geometric_cn.rst
  docs/api/paddle/distribution/Gumbel_cn.rst
  docs/api/paddle/distribution/Independent_cn.rst
  docs/api/paddle/distribution/LKJCholesky_cn.rst
  docs/api/paddle/distribution/Laplace_cn.rst
  docs/api/paddle/distribution/LogNormal_cn.rst
  docs/api/paddle/distribution/Multinomial_cn.rst
  docs/api/paddle/distribution/MultivariateNormal_cn.rst
  docs/api/paddle/distribution/Normal_cn.rst
  docs/api/paddle/distribution/Poisson_cn.rst
  docs/api/paddle/distribution/StudentT_cn.rst
  docs/api/paddle/distribution/TransformedDistribution_cn.rst
  docs/api/paddle/distribution/Uniform_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.lkj_cholesky.LKJCholesky.md
Labels: contributor

#6970 【SCU】【Paddle Tensor No.24】docs: Add docs for paddle.matrix_transpose, paddle.linalg.matrix_transpose
  docs/api/paddle/linalg/matrix_transpose_cn.rst
  docs/api/paddle/matrix_transpose_cn.rst
Labels: contributor, HappyOpenSource Pro

#6943 [Docathon][Add API Legend No.13] add a figure of gather_nd
  docs/api/paddle/broadcast_to_cn.rst
  docs/api/paddle/gather_nd_cn.rst
  docs/images/api_legend/gather_nd.png
Labels: contributor

#6989 【Paddle Tensor No.22】新增`paddle.less`,`Tensor.less`中文文档
  docs/api/paddle/Tensor_cn.rst
  docs/api/paddle/less_cn.rst
Labels: contributor, HappyOpenSource

#6972 【Paddle Tensor No.13】新增`paddle.positive` 中文文档.
  docs/api/paddle/positive_cn.rst
Labels: contributor, HappyOpenSource

#6952 [Docathon][Add API Legend No.46]add the legend of index_put -part
  docs/api/paddle/index_put_cn.rst
  docs/images/api_legend/index_put.png
Labels: contributor, HappyOpenSource

#6968 [SCU][Docathon][Add API Legend No.48]为as_strided API添加图例 -part
  docs/api/paddle/as_strided_cn.rst
  docs/images/api_legend/as_strided.png
Labels: contributor, HappyOpenSource Pro

#6973 [Docathon][Add API Legend No.19]+添加图例至paddle.scatter -part
  docs/api/paddle/scatter_cn.rst
  docs/images/api_legend/scatter.png
Labels: contributor, HappyOpenSource

#6950 [Docathon][Add API Legend No.1] Add the picture of broadcast_to
  docs/api/paddle/broadcast_to_cn.rst
  docs/images/api_legend/broadcast_to.png
Labels: contributor, HappyOpenSource

#6992 `paddle.bernoulli` add parameter `p` 易用性提升
  docs/api/paddle/bernoulli_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.bernoulli.md
Labels: contributor

#6995 【SCU】【Paddle Tensor No.24】docs: update docs for paddle.linalg.matrix_transpose
  docs/api/paddle/linalg/Overview_cn.rst
Labels: contributor, HappyOpenSource Pro

#7000 Change LoDTensor to DenseTensor
  docs/api/paddle/Model_cn.rst
  docs/api/paddle/jit/load_cn.rst
  docs/api/paddle/static/Variable_cn.rst
  docs/api/paddle/static/ctr_metric_bundle_cn.rst
  docs/api/paddle/static/data_cn.rst
  docs/api/paddle/static/nn/row_conv_cn.rst
  docs/api/paddle/static/nn/sequence_expand_cn.rst
  docs/api_guides/low_level/layers/data_feeder.rst
  docs/api_guides/low_level/layers/data_feeder_en.rst
  docs/api_guides/low_level/layers/data_in_out.rst
  docs/api_guides/low_level/layers/data_in_out_en.rst
  docs/api_guides/low_level/layers/pooling.rst
  docs/api_guides/low_level/layers/pooling_en.rst
  docs/api_guides/low_level/layers/sequence.rst
  docs/api_guides/low_level/layers/sequence_en.rst
  docs/design/concepts/cpp_data_feeding.md
  docs/design/concepts/python_data_feeding.md
  docs/design/concepts/tensor_array.md
  docs/design/concepts/var_desc.md
  docs/design/concurrent/channel.md
  docs/design/concurrent/csp.md
  docs/design/dynamic_rnn/rnn.md
  docs/design/dynamic_rnn/rnn_design_en.md
  docs/design/modules/infer_var_type.md
  docs/design/modules/selected_rows.md
  docs/design/motivation/refactorization.md
  docs/design/network/sequence_decoder.md
  docs/design/onnx/onnx_convertor.md
  docs/design/phi/design_cn.md
  docs/design/phi/design_en.md
  docs/design/phi/kernel_migrate_cn.md
  docs/design/phi/kernel_migrate_en.md
  docs/dev_guides/api_contributing_guides/api_docs_guidelines_cn.md
  docs/guides/jit/case_analysis_cn.md
Labels: contributor, PaddlePaddle Hackathon
