Repository PaddlePaddle/docs, pull requests merged in 2024-02, with the labels that each got.

#6292 update `model_convert/convert_from_pytorch/index_cn.rst` description
  docs/guides/model_convert/convert_from_pytorch/index_cn.rst
Labels: contributor

#6499 [Fix]: add '--gpu all' args to enable gpu in container
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
  docs/install/docker/linux-docker.md
  docs/install/docker/linux-docker_en.md
Labels: contributor

#6502 [cherry-pick] add '--gpu all' args to enable gpu in container #6499
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
  docs/install/docker/linux-docker.md
  docs/install/docker/linux-docker_en.md
Labels: contributor

#6496 【映射目录】更新映射目录的描述与检查
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#6501 [Docathon][Add Overview Doc No.27-32] add refs of paddle.vision in paddle/vision/Overview_cn.rst
  docs/api/paddle/vision/Overview_cn.rst
Labels: HappyOpenSource

#6497 [Docathon][Add Overview Doc No.18] add nn.utils in nn/Overview_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6447 [Docathon][Add CN Doc No.30、31]
  docs/api/paddle/incubate/nn/functional/fused_rotary_position_embedding_cn.rst
  docs/api/paddle/sparse/Overview_cn.rst
  docs/api/paddle/sparse/nn/functional/subm_conv2d_cn.rst
Labels: contributor, HappyOpenSource

#6488 【Hackathon 5th No.115】为 paddle.linalg.norm 进行功能升级与对齐- 修改norm文档
  docs/api/paddle/linalg/matrix_norm_cn.rst
  docs/api/paddle/linalg/norm_cn.rst
  docs/api/paddle/linalg/vector_norm_cn.rst
Labels: contributor, HappyOpenSource

#6500 【映射文档】新增与维护部分映射文档 part2
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.argmax.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nanmedian.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.Distribution.log_prob.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.Distribution.rsample.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.Distribution.sample.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.log_normal.LogNormal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.AbsTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.AffineTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.ExpTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.IndependentTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.PowerTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.SigmoidTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributions/torch.distributions.transforms.TanhTransform.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/fft/torch.fft.rfft2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.backends.cudnn.version.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.celu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.complex.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.distributed.ReduceOp.MAX.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.distributed.ReduceOp.MIN.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.distributed.ReduceOp.PRODUCT.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.distributed.ReduceOp.SUM.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.dropout.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.eq.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.ge.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.gt.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.max_pool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.max_pool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.max_pool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.mean.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor
