Repository PaddlePaddle/docs, pull requests merged in 2024-01, with the labels that each got.

#6437 update multigammaln_cn doc
  docs/api/paddle/multigammaln_cn.rst
Labels: contributor

#6438 update multigammaln_cn doc
  docs/api/paddle/multigammaln_cn.rst
Labels: contributor

#6443 【complex op】No.19 add complex support for triangular_solve
  docs/api/paddle/linalg/triangular_solve_cn.rst
Labels: contributor, HappyOpenSource

#6361 [Docathon][Add CN Doc No.6-9]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/acos__cn.rst
  docs/api/paddle/atan__cn.rst
  docs/api/paddle/cos__cn.rst
  docs/api/paddle/erf__cn.rst
Labels: contributor, HappyOpenSource

#6367 [Docathon][Add CN Doc No.14]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/abs__cn.rst
Labels: contributor, HappyOpenSource

#6387 [Docathon][Add CN Doc No.27]
  docs/api/paddle/utils/Overview_cn.rst
Labels: contributor, HappyOpenSource

#6365 [Docathon][Add CN Doc No.12]
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/thresholded_relu__cn.rst
Labels: contributor, HappyOpenSource

#6439 【Hackathon 5th No.25】为 Paddle 新增 gammaln API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/gammaln__cn.rst
  docs/api/paddle/gammaln_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6413 【Hackathon 5th No.20】为 Paddle 新增 Exponential 和 Gamma API
  docs/api/paddle/distribution/Exponential_cn.rst
  docs/api/paddle/distribution/Gamma_cn.rst
  docs/api/paddle/distribution/Overview_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6363 [Docathon][Add CN Doc No.10-11]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/get_rng_state_cn.rst
  docs/api/paddle/set_rng_state_cn.rst
Labels: contributor, HappyOpenSource

#6371 [Docathon][Add CN Doc No.20-22]
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/quant/llm_int8_linear_cn.rst
  docs/api/paddle/nn/quant/weight_only_linear_cn.rst
  docs/api/paddle/nn/quant/weight_quantize_cn.rst
Labels: contributor, HappyOpenSource

#6458 [doc] Deprecated py37
  docs/api/paddle/sysconfig/get_lib_cn.rst
  docs/dev_guides/custom_device_docs/custom_device_example_en.md
  docs/guides/hardware_support/ipu_docs/paddle_install_cn.md
  docs/guides/hardware_support/mlu_docs/train_example_cn.md
  docs/guides/hardware_support/rocm_docs/infer_example_cn.md
  docs/guides/hardware_support/rocm_docs/paddle_install_cn.md
  docs/guides/model_convert/convert_from_pytorch/cv_experience_cn.md
  docs/guides/model_convert/convert_from_pytorch/nlp_migration_experiences_cn.md
  docs/guides/model_convert/convert_train_code/cv_experience_cn.md
Labels: contributor, HappyOpenSource

#6399 【Hackathon 5th No.34】为 Paddle 新增 bitwise_right_shift / bitwise_right_shift_ / bitwise_left_shift / bitwise_left_shift_ API 中文文档
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/bitwise_left_shift__cn.rst
  docs/api/paddle/bitwise_left_shift_cn.rst
  docs/api/paddle/bitwise_right_shift__cn.rst
  docs/api/paddle/bitwise_right_shift_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6461 [api] update api_label and ci
  ci_scripts/check_api_label_cn.py
  docs/api/paddle/metric/Accuracy__upper_cn.rst
  docs/api/paddle/metric/Overview_cn.rst
  docs/api/paddle/vision/Overview_cn.rst
  docs/api/paddle/vision/models/AlexNet__upper_cn.rst
  docs/api/paddle/vision/models/GoogLeNet__upper_cn.rst
  docs/api/paddle/vision/models/alexnet_cn.rst
  docs/api/paddle/vision/models/googlenet_cn.rst
  docs/api/paddle/vision/transforms/Normalize__upper_cn.rst
  docs/api/paddle/vision/transforms/Pad__upper_cn.rst
  docs/api/paddle/vision/transforms/Resize__upper_cn.rst
Labels: contributor, HappyOpenSource

#6464 [Fix] dsplit/vsplit 映射文档中书写错误
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.dsplit.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.vsplit.md
Labels: contributor

#6417 【Hackathon 5th No.1】 为 Paddle 新增 copysign API 中文文档
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/copysign__cn.rst
  docs/api/paddle/copysign_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6370 [Docathon][Add CN Doc No.18-19]
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/hardtanh__cn.rst
Labels: contributor, HappyOpenSource

#6366 [Docathon][Add CN Doc No.13]
  docs/api/paddle/geometric/Overview_cn.rst
  docs/api/paddle/geometric/weighted_sample_neighbors_cn.rst
Labels: contributor, HappyOpenSource

#6469 [Fix] fix docker relative doc when build from source
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
  docs/install/docker/linux-docker.md
  docs/install/docker/linux-docker_en.md
Labels: contributor, HappyOpenSource

#6373 [Docathon][Add CN Doc No.41]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/expm1__cn.rst
Labels: contributor, HappyOpenSource

#6378 [Docathon][Add CN Doc No.52]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/square__cn.rst
Labels: contributor, HappyOpenSource

#6471 【Hackathon 5th No.115】为 paddle.linalg.norm 进行功能对齐与功能增强-修改nuclear_norm中文文档
  docs/api/paddle/linalg/norm_cn.rst
Labels: contributor, HappyOpenSource

#6424 [doc] fix name in copy-from
  docs/api/paddle/diag_cn.rst
  docs/api/paddle/diagflat_cn.rst
  docs/api/paddle/scatter_cn.rst
Labels: contributor, HappyOpenSource

#6376 [Docathon][Add CN Doc No.55]
  docs/api/paddle/incubate/xpu/resnet_block/resnet_basic_block_cn.rst
Labels: contributor, HappyOpenSource

#6444 修复Sequential_cn.rst 等 API 的文档
  docs/api/paddle/nn/Sequential_cn.rst
  docs/api/paddle/static/nn/multi_box_head_cn.rst
  docs/guides/06_distributed_training/model_parallel_cn.rst
  docs/guides/advanced/autograd_cn.rst
  docs/guides/infer/inference/inference_cn.md
Labels: contributor, HappyOpenSource

#6468 docs: fix docs issue
  docs/api/paddle/diagonal_cn.rst
  docs/api/paddle/nn/CosineEmbeddingLoss_cn.rst
  docs/api/paddle/nn/functional/cross_entropy_cn.rst
  docs/api/paddle/optimizer/SGD_cn.rst
  docs/api/paddle/static/nn/fc_cn.rst
  docs/dev_guides/api_contributing_guides/api_design_guidelines_standard_cn.md
  docs/guides/beginner/data_load_cn.ipynb
  docs/practices/quick_start/high_level_api.ipynb
Labels: contributor, HappyOpenSource

#6472 Update index_cn.rst
  docs/install/index_cn.rst
Labels: contributor, HappyOpenSource

#6473 [cherry-pick] fix docker relative doc when build from source #6469
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
  docs/install/docker/linux-docker.md
  docs/install/docker/linux-docker_en.md
Labels: contributor, HappyOpenSource

#6382 [Docathon][Add CN Doc No.28-29]
  docs/api/paddle/amp/debugging/check_layer_numerics_cn.rst
  docs/api/paddle/incubate/nn/functional/fused_linear_activation_cn.rst
Labels: contributor, HappyOpenSource

#6369 [Docathon][Add CN Doc No.17]
  docs/api/paddle/incubate/nn/functional/fused_multi_transformer_cn.rst
Labels: contributor, HappyOpenSource

#6431 [Docathon][Add CN Doc No.33、34]
  docs/api/paddle/incubate/nn/FusedDropoutAdd_cn.rst
  docs/api/paddle/incubate/nn/functional/fused_dropout_add_cn.rst
Labels: contributor, HappyOpenSource

#6450 [Docathon] Fix BCEWithLogitsLoss API Docs
  docs/api/paddle/nn/BCEWithLogitsLoss_cn.rst
Labels: contributor, HappyOpenSource

#6463 [Fix] fix pytorch-paddle mapping index generate
  ci_scripts/gendoc.sh
  ci_scripts/hooks/pre-doc-compile.sh
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tensor_split.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.matrix_exp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool1d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveAvgPool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.LogSigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Sigmoid.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Softplus.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Softsign.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Tanh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Tanhshrink.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.TripletMarginWithDistanceLoss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.slice_scatter.md
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/pytorch_api_mapping_cn.md
Labels: contributor, HappyOpenSource

#6477 [Docathon][Add CN Doc No.2] Add sinh_cn
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/sinh__cn.rst
Labels: contributor, HappyOpenSource

#6480 【complex op】No.12、14 add complex support for square & reciprocal-中文文档修改
  docs/api/paddle/reciprocal_cn.rst
  docs/api/paddle/square_cn.rst
Labels: contributor, HappyOpenSource

#6418 【Hackathon 5th No.38】为 Paddle 新增 FractionalMaxPool2d / FractionalMaxPool3d API
  docs/api/paddle/nn/FractionalMaxPool2D_cn.rst
  docs/api/paddle/nn/FractionalMaxPool3D_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/fractional_max_pool2d_cn.rst
  docs/api/paddle/nn/functional/fractional_max_pool3d_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.fractional_max_pool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.fractional_max_pool3d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.FractionalMaxPool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.FractionalMaxPool3d.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6479 [Docathon][Add CN Doc No.3] Add fused_linear
  docs/api/paddle/incubate/nn/functional/fused_linear_cn.rst
Labels: contributor, HappyOpenSource

#6372 [Docathon][Add CN Doc No.23]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/ctr_metric_bundle_cn.rst
Labels: contributor, HappyOpenSource

#6203 修复 static_pylayer 文档
  docs/api/paddle/static/nn/static_pylayer_cn.rst
Labels: contributor

#6457 [Docathon] Fix save API Docs
  docs/api/paddle/jit/save_cn.rst
Labels: contributor, HappyOpenSource

#6486 fix: fix docs issue
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/io/DataLoader_cn.rst
  docs/api/paddle/stack_cn.rst
  docs/api/paddle/static/data_cn.rst
  docs/api/paddle/transpose_cn.rst
  docs/api/paddle/vision/ops/yolo_box_cn.rst
  docs/guides/06_distributed_training/model_parallel_cn.rst
  docs/guides/jit/debugging_cn.md
  docs/practices/quick_start/high_level_api.ipynb
Labels: contributor, HappyOpenSource

#6360 [Docathon][Add CN Doc No.24-25]
  docs/api/paddle/sparse/Overview_cn.rst
  docs/api/paddle/sparse/nn/Conv2d_cn.rst
  docs/api/paddle/sparse/nn/functional/conv2d_cn.rst
Labels: contributor, HappyOpenSource

#6356 [Docathon][Add CN Doc No.58-59]
  docs/api/paddle/incubate/nn/functional/masked_multihead_attention_cn.rst
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/leaky_relu__cn.rst
Labels: contributor, HappyOpenSource

#6484 [Docathon][Add CN Doc No.26]
  docs/api/paddle/nn/Overview_cn.rst
  docs/api/paddle/nn/functional/scaled_dot_product_attention_cn.rst
Labels: contributor, HappyOpenSource

#6430 [Docathon][Add CN Doc No.32 ]
  docs/api/paddle/sparse/Overview_cn.rst
  docs/api/paddle/sparse/nn/SubmConv2D_cn.rst
Labels: contributor, HappyOpenSource

#6476 【映射文档】更新与维护部分 api 的映射文档
  docs/guides/model_convert/convert_from_pytorch/.gitignore
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.addmm_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctan2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.bernoulli.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cholesky_solve.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.coalesce.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cov.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.cuda.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.det.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.diagflat.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.expm1.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor_divide.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.floor_divide_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.get_device.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_add.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_add_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.is_contiguous.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.istft.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.minimum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.multinomial.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.nansum.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.outer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pinverse.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.pow.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.reciprocal.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.reciprocal_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.remainder.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.remainder_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.renorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.rot90.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.slice_scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.squeeze.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.tril.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.triu.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unflatten.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.uniform_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_device_name.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.nvtx.range_pop.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.nvtx.range_push.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.ReduceOp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.conv2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/hub/torch.hub.download_url_to_file.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.slogdet.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.AdaptiveMaxPool2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.SyncBatchNorm.convert_sync_batchnorm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.UpsamplingNearest2d.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.column_stack.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.mm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.movedim.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.msort.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/ops/torch.unflatten.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Optimizer.load_state_dict.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/sparse/torch.sparse.addmm.md
  docs/guides/model_convert/convert_from_pytorch/apply_reference_from_api_difference.py
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
Labels: contributor

#6490 【Hackathon 5th No.11】add gammaincc and gammainc API
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/gammainc__cn.rst
  docs/api/paddle/gammainc_cn.rst
  docs/api/paddle/gammaincc__cn.rst
  docs/api/paddle/gammaincc_cn.rst
Labels: contributor, PaddlePaddle Hackathon

#6217 【Hackathon 5th No.45】映射文档69-70 -part
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor, PaddlePaddle Hackathon

#6412 【Hackathon 5th No.40】为 Paddle 新增 ASGD API 中文文档
  docs/api/paddle/optimizer/ASGD_cn.rst
  docs/api/paddle/optimizer/Overview_cn.rst
  docs/api_guides/low_level/optimizer.rst
  docs/api_guides/low_level/optimizer_en.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.ASGD.md
Labels: contributor, PaddlePaddle Hackathon
