Repository PaddlePaddle/docs, pull requests merged in 2024-08, with the labels that each got.

#6801 paddle.put_along_axis_ add attr `broadcast` 易用性提升
  docs/api/paddle/put_along_axis__cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.scatter_.md
Labels: contributor

#6798 fix the demo of hybrid parallel training
  docs/guides/paddle_v3_features/auto_parallel_cn.md
Labels: contributor

#6793 [Docathon][Add API Legend No.12]
  docs/api/paddle/gather_cn.rst
  docs/images/api_legend/gather.png
Labels: contributor, HappyOpenSource Pro

#6789 [Docathon][Add API Legend No.5 BUAA]
  docs/api/paddle/concat_cn.rst
  docs/images/api_legend/concat.png
Labels: contributor, HappyOpenSource Pro

#6804 【映射文档】update mapping docs, upgrade doc generate tools and add docs for generate tools
  ci_scripts/hooks/pre-doc-compile.sh
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.arctan2.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/fairscale/fairscale.nn.model_parallel.initialize.get_model_parallel_world_size.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/fairscale/fairscale.nn.model_parallel.layers.ColumnParallelLinear.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/fairscale/fairscale.nn.model_parallel.layers.ParallelEmbedding.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/fairscale/fairscale.nn.model_parallel.layers.RowParallelLinear.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.flash_attn_interface.flash_attn_func.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.flash_attn_interface.flash_attn_unpadded_func.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.layers.rotary.apply_rotary_emb_func.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/flash_attn/flash_attn.ops.rms_norm.rms_norm.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.AddedToken.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.PreTrainedModel.generate.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.PreTrainedTokenizer.encode.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.PreTrainedTokenizer.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.StoppingCriteriaList.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.generation.LogitsProcessor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.modeling_outputs.BaseModelOutputWithPast.md
  docs/guides/model_convert/convert_from_pytorch/api_difference_third_party/transformers/transformers.modeling_outputs.CausalLMOutputWithPast.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_format_cn.md
  docs/guides/model_convert/convert_from_pytorch/tools/.gitignore
  docs/guides/model_convert/convert_from_pytorch/tools/README.md
  docs/guides/model_convert/convert_from_pytorch/tools/apply_references.py
  docs/guides/model_convert/convert_from_pytorch/tools/validate_mapping_files.py
  docs/guides/model_convert/convert_from_pytorch/validate_mapping_in_api_difference.py
  docs/guides/model_convert/convert_guide_cn.md
Labels: contributor

#6802 [Docathon][Add API Legend No.30 BUAA]
  docs/api/paddle/squeeze_cn.rst
  docs/images/api_legend/squeeze.png
Labels: contributor, HappyOpenSource Pro

#6817 [Docathon][Add API Legend No.59 vstack]
  docs/api/paddle/vstack_cn.rst
  docs/images/api_legend/vstack.png
Labels: contributor, HappyOpenSource

#6809 [Docathon][Add API Legend No.26~30]添加tensor_split系列API图例
  docs/api/paddle/dsplit_cn.rst
  docs/api/paddle/hsplit_cn.rst
  docs/api/paddle/tensor_split_cn.rst
  docs/api/paddle/vsplit_cn.rst
  docs/images/api_legend/dsplit/dsplit.png
  docs/images/api_legend/hsplit/hsplit-1.png
  docs/images/api_legend/hsplit/hsplit-2.png
  docs/images/api_legend/tensor_split/tensor_split-1.png
  docs/images/api_legend/tensor_split/tensor_split-1_en.png
  docs/images/api_legend/tensor_split/tensor_split-2.png
  docs/images/api_legend/tensor_split/tensor_split-3.png
  docs/images/api_legend/tensor_split/tensor_split-3_en.png
  docs/images/api_legend/tensor_split/tensor_split-4.png
  docs/images/api_legend/tensor_split/tensor_split-5.png
  docs/images/api_legend/tensor_split/tensor_split-6.png
  docs/images/api_legend/vsplit/vsplit-1.png
  docs/images/api_legend/vsplit/vsplit-2.png
Labels: contributor, HappyOpenSource

#6835 Fix mapping url in mapping doc generation
  docs/guides/model_convert/convert_from_pytorch/tools/apply_references.py
Labels: contributor

#6827 [Docathon][Add API Legend No.3] 为cast API添加图例
  docs/api/paddle/cast_cn.rst
  docs/images/api_legend/cast.png
Labels: contributor, HappyOpenSource

#6838 API映射关系文档修改
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.new_tensor.md
Labels: contributor

#6770 [Docathon][Add API Legend No.9]add flatten lenged
  docs/api/paddle/flatten_cn.rst
  docs/images/api_legend/flatten.png
Labels: contributor, HappyOpenSource Pro

#6841 [docs] improve squeeze's doc
  docs/api/paddle/squeeze_cn.rst
Labels: contributor, HappyOpenSource

#6830 [Type Promotion] fix rules table in Tensor-to-Tensor && fix example code as expected
  docs/guides/advanced/auto_type_promotion_cn.md
  docs/guides/advanced/auto_type_promotion_en.md
Labels: contributor

#6810 [Docathon][Add API Legend No.18]为roll API 添加插图
  docs/api/paddle/roll_cn.rst
  docs/images/api_legend/roll.png
Labels: contributor, HappyOpenSource

#6848 易用性提升已修改的58个API核对 - part1
  docs/api/paddle/all_cn.rst
  docs/api/paddle/any_cn.rst
  docs/api/paddle/floor_divide_cn.rst
  docs/api/paddle/round__cn.rst
  docs/api/paddle/round_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.round.md
Labels: contributor
