Repository PaddlePaddle/docs, pull requests merged in 2025-04, with the labels that each got.

#7178 [Docathon][Fix note No.40]
  docs/api/paddle/static/nn/sequence_pool_cn.rst
Labels: contributor, HappyOpenSource

#7154 [Docathon][Fix note No.29-38]
  docs/api/paddle/static/nn/conv2d_transpose_cn.rst
  docs/api/paddle/static/nn/conv3d_transpose_cn.rst
  docs/api/paddle/static/nn/embedding_cn.rst
  docs/api/paddle/static/nn/sequence_concat_cn.rst
  docs/api/paddle/static/nn/sequence_conv_cn.rst
  docs/api/paddle/static/nn/sequence_enumerate_cn.rst
  docs/api/paddle/static/nn/sequence_expand_as_cn.rst
  docs/api/paddle/static/nn/sequence_expand_cn.rst
  docs/api/paddle/static/nn/sequence_first_step_cn.rst
  docs/api/paddle/static/nn/sequence_last_step_cn.rst
Labels: contributor, HappyOpenSource

#7153 [Docathon][Fix note No.39,41-43]
  docs/api/paddle/static/nn/sequence_pad_cn.rst
  docs/api/paddle/static/nn/sequence_reshape_cn.rst
  docs/api/paddle/static/nn/sequence_reverse_cn.rst
  docs/api/paddle/static/nn/sequence_slice_cn.rst
Labels: contributor, HappyOpenSource

#7213 [Docathon][Fix note No.11-13]
  docs/api/paddle/nn/InstanceNorm1D_cn.rst
  docs/api/paddle/nn/InstanceNorm2D_cn.rst
  docs/api/paddle/nn/InstanceNorm3D_cn.rst
Labels: contributor, HappyOpenSource

#7214 [Docathon][Fix note No.8]
  docs/api/paddle/nn/BatchNorm1D_cn.rst
Labels: contributor, HappyOpenSource

#7120 [Docathon][Add Inplace CN Doc No.43]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/transpose__cn.rst
Labels: contributor, HappyOpenSource

#7215 [Docathon][Fix note No.26]
  docs/api/paddle/static/Program_cn.rst
Labels: contributor, HappyOpenSource

#7131 [Docathon][Add Inplace CN Doc No.19-22]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/greater_equal__cn.rst
  docs/api/paddle/greater_than__cn.rst
  docs/api/paddle/i0__cn.rst
  docs/api/paddle/lcm__cn.rst
Labels: contributor, HappyOpenSource

#7222 [Docathon][Fix note No.9、10]
  docs/api/paddle/nn/BatchNorm2D_cn.rst
  docs/api/paddle/nn/BatchNorm3D_cn.rst
Labels: contributor

#7144 [Docathon][Add Inplace CN Doc No.40]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/pow__cn.rst
Labels: contributor, HappyOpenSource

#7133 [Docathon][Add Inplace CN Doc No.41、42]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/renorm__cn.rst
  docs/api/paddle/t__cn.rst
Labels: contributor, HappyOpenSource

#7235 [Docathon][Fix the addmm__cn about alpha and beta]
  docs/api/paddle/addmm__cn.rst
Labels: contributor, HappyOpenSource

#7241 [Docathon][Delete Deprecated API Doc No.1-2]
  docs/api/paddle/NPUPlace_cn.rst
  docs/api/paddle/device/is_compiled_with_mlu_cn.rst
Labels: contributor

#7206 更新torch.unique映射关系sorted参数
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.unique.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.unique.md
Labels: contributor

#7251 [Docathon][Delete Deprecated API Doc No.1-2] Delete the API reference in the Overview
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/device/Overview_cn.rst
Labels: contributor, HappyOpenSource

#7249 解决 安装编译依赖路径不正确的问题
  docs/install/compile/linux-compile-by-make.md
  docs/install/compile/linux-compile-by-make_en.md
  docs/install/compile/linux-compile-by-ninja.md
  docs/install/compile/macos-compile-make.md
  docs/install/compile/macos-compile-make_en.md
  docs/install/compile/macos-compile-ninja.md
  docs/install/compile/windows-compile.md
  docs/install/compile/windows-compile_en.md
Labels: contributor, HappyOpenSource Pro

#7205 在Upsample和interpolate函数中加入recompute_scale_factor参数
  docs/api/paddle/nn/Upsample_cn.rst
  docs/api/paddle/nn/functional/interpolate_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.interpolate.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Upsample.md
Labels: contributor

#7262 Add `full_graph=True` in Dy2St principle docs
  docs/guides/jit/principle_cn.md
Labels: contributor

#7258 [sdaa]:add sdaa docs
  docs/hardware_support/hardware_info_cn.md
  docs/hardware_support/index_cn.rst
  docs/hardware_support/sdaa/index_cn.rst
  docs/hardware_support/sdaa/install_cn.md
  docs/hardware_support/sdaa/paddle_tutorial_cn.md
Labels: contributor

#7255 Del layers
  docs/api/paddle/audio/features/LogMelSpectrogram_cn.rst
  docs/api/paddle/audio/features/MFCC_cn.rst
  docs/api/paddle/audio/features/MelSpectrogram_cn.rst
  docs/api/paddle/audio/features/Spectrogram_cn.rst
Labels: contributor, HappyOpenSource

#7227 [Docathon][Update Doc No.29] fix the LossFunction
  docs/api_guides/low_level/layers/loss_function.rst
  docs/api_guides/low_level/layers/loss_function_en.rst
Labels: contributor, HappyOpenSource

#7267 [Docathon][Delete Deprecated API Doc No.8-9]
  docs/api/paddle/static/mlu_places_cn.rst
  docs/api/paddle/static/npu_places_cn.rst
Labels: contributor, HappyOpenSource

#7230 [Docathon][Add Inplace CN Doc No.9]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/cauchy__cn.rst
Labels: contributor, HappyOpenSource

#7263 [Docathon][Add Inplace CN Doc No.28-31]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/log10__cn.rst
  docs/api/paddle/log2__cn.rst
  docs/api/paddle/log__cn.rst
  docs/api/paddle/logical_and__cn.rst
Labels: contributor, HappyOpenSource

#7264 [Docathon][Add Inplace CN Doc No.33]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/logical_or__cn.rst
Labels: contributor, HappyOpenSource

#7228 [Docathon][Update Doc No.31] update the api path
  docs/api_guides/low_level/layers/pooling.rst
  docs/api_guides/low_level/layers/pooling_en.rst
Labels: contributor, HappyOpenSource

#7270 [Docathon][Delete Deprecated API Doc No.12-13]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/nn/sequence_enumerate_cn.rst
  docs/api/paddle/static/nn/sequence_expand_as_cn.rst
Labels: contributor, HappyOpenSource

#7233 [Docathon][Add Inplace CN Doc No.3-4]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/bitwise_and__cn.rst
  docs/api/paddle/bitwise_invert__cn.rst
Labels: contributor, HappyOpenSource

#7269 [Docathon][Delete Deprecated API Doc No.10-11]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/nn/multi_box_head_cn.rst
  docs/api/paddle/static/nn/sequence_concat_cn.rst
Labels: contributor, HappyOpenSource

#7271 [Docathon][Add Inplace CN Doc No.32]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/logical_not__cn.rst
Labels: contributor, HappyOpenSource

#7273 [Docathon][Delete Deprecated API Doc No.18、19]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/nn/sequence_slice_cn.rst
  docs/api/paddle/static/nn/sequence_unpad_cn.rst
Labels: contributor, HappyOpenSource

#7278 Fix errors.h
  docs/dev_guides/custom_device_docs/custom_kernel_docs/exception_api_cn.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/exception_api_en.md
Labels: contributor, HappyOpenSource

#7275 [Doc][Fix] Fix the issue with the link of 'layout.h'
  docs/dev_guides/custom_device_docs/custom_kernel_docs/kernel_declare_cn.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/kernel_declare_en.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/register_api_cn.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/register_api_en.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/tensor_api_cn.md
  docs/dev_guides/custom_device_docs/custom_kernel_docs/tensor_api_en.md
Labels: contributor, HappyOpenSource

#7274 [Docathon][Delete Deprecated API Doc No.14、17]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/nn/sequence_pad_cn.rst
  docs/api/paddle/static/nn/sequence_scatter_cn.rst
Labels: contributor, HappyOpenSource

#7281 [Docathon][Delete Deprecated API Doc No.15-16]
  docs/api/paddle/static/Overview_cn.rst
  docs/api/paddle/static/nn/sequence_reshape_cn.rst
  docs/api/paddle/static/nn/sequence_reverse_cn.rst
Labels: contributor, HappyOpenSource

#7283 [Docathon][Delete Deprecated API Doc No.3-4]
  docs/api/paddle/device/MLUPlace_cn.rst
  docs/api/paddle/device/Overview_cn.rst
  docs/api/paddle/device/is_compiled_with_npu_cn.rst
Labels: contributor, HappyOpenSource

#7268 [Docathon][Add Inplace CN Doc No.8]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/cast__cn.rst
Labels: contributor, HappyOpenSource

#7284 [Docathon][Delete Deprecated API Doc No.6-7]
  docs/api/paddle/incubate/nn/functional/fused_ec_moe_cn.rst
  docs/api/paddle/nn/functional/flash_attention_with_sparse_mask_cn.rst
Labels: contributor

#7290 [Docathon][Delete Deprecated API Doc No.5]
  docs/api/paddle/incubate/nn/FusedEcMoe_cn.rst
Labels: contributor, HappyOpenSource

#7294 [Docathon][Add Inplace CN Doc No.5、6、12] Add bitwise_or_/bitwise_not_/digamma_ docs
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/bitwise_not__cn.rst
  docs/api/paddle/bitwise_or__cn.rst
  docs/api/paddle/digamma__cn.rst
Labels: contributor
