Repository PaddlePaddle/docs, pull requests merged in 2025-03, with the labels that each got.

#7067 [Docathon][Update Doc No.3] delete compiled_program.rst and the description in index_cn.rst
  docs/api_guides/index_cn.rst
  docs/api_guides/index_en.rst
  docs/api_guides/low_level/compiled_program.rst
  docs/api_guides/low_level/compiled_program_en.rst
Labels: contributor, HappyOpenSource Pro

#7073 [Docathon][Update Doc No.16-17] Remove deprecated model_save_reader_en.rst and nets_en.rst
  docs/api_guides/index_en.rst
  docs/api_guides/low_level/model_save_reader_en.rst
  docs/api_guides/low_level/nets_en.rst
Labels: contributor

#7070 [Docathon][Update Doc No.9] Remove fluid APIs and update APIs in parameter.rst
  docs/api_guides/low_level/parameter.rst
  docs/guides/advanced/gradient_clip_cn.rst
Labels: contributor, HappyOpenSource Pro

#7075 [Docathon][Update Doc No.1] update Executor zh doc
  docs/api_guides/low_level/executor.rst
Labels: contributor, HappyOpenSource Pro

#7071 [Docathon][Update Doc No.19] Remove fluid APIs and update APIs in parameter_en.rst
  docs/api_guides/low_level/parameter.rst
  docs/api_guides/low_level/parameter_en.rst
  docs/guides/advanced/gradient_clip_en.rst
Labels: contributor, HappyOpenSource Pro

#7076 [Docathon][Update Doc No.11] update en Executor api_guides doc
  docs/api_guides/low_level/executor_en.rst
Labels: contributor, HappyOpenSource Pro

#7086 [Docathon][Update Doc No.24、26、30、32、34] remove the related files
  docs/api_guides/low_level/layers/data_feeder.rst
  docs/api_guides/low_level/layers/data_feeder_en.rst
  docs/api_guides/low_level/layers/data_in_out.rst
  docs/api_guides/low_level/layers/data_in_out_en.rst
  docs/api_guides/low_level/layers/detection.rst
  docs/api_guides/low_level/layers/detection_en.rst
  docs/api_guides/low_level/layers/math.rst
  docs/api_guides/low_level/layers/math_en.rst
  docs/api_guides/low_level/layers/sequence.rst
  docs/api_guides/low_level/layers/sequence_en.rst
  docs/api_guides/low_level/layers/tensor.rst
  docs/api_guides/low_level/layers/tensor_en.rst
Labels: contributor

#7087 Update yaml link and format new_cpp_op_cn.md
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
Labels: contributor

#7093 更新飞桨文档「开发 C++ 算子」
  docs/dev_guides/api_contributing_guides/new_cpp_op_cn.md
Labels: contributor

#7081 Update docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.where.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.get_rng_state.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/cuda/torch.cuda.set_per_process_memory_fraction.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.is_available.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.is_nccl_available.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.monitored_barrier.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.modules.module.register_module_forward_hook.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.modules.module.register_module_forward_pre_hook.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/optimizer/torch.optim.Optimizer.zero_grad.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.get_default_device.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.set_default_device.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7052 【Hackathon 8th No.1】add `lu_solve` api for paddle
  docs/api/paddle/Tensor/Overview_en.rst
  docs/api/paddle/linalg/Overview_cn.rst
  docs/api/paddle/linalg/lu_solve_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/linalg/torch.linalg.lu_solve.md
Labels: contributor, PaddlePaddle Hackathon

#7101 更新飞桨文档「开发 API Python 端」
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
Labels: contributor

#7102 更新飞桨文档「开发 API Python 端」-part2
  docs/dev_guides/api_contributing_guides/new_python_api_cn.md
Labels: contributor

#7105 [Docathon][Update Doc No.8] Update optimizer.rst
  docs/api_guides/low_level/optimizer.rst
Labels: contributor, HappyOpenSource Pro

#7106 [Docathon][Update Doc No.18] Update optimizer_en.rst
  docs/api_guides/low_level/optimizer.rst
  docs/api_guides/low_level/optimizer_en.rst
Labels: contributor, HappyOpenSource Pro

#7097 [Docathon][Add Inplace CN Doc No.1]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/addmm__cn.rst
Labels: contributor, HappyOpenSource

#7104 Update docs
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.modules.module.register_module_forward_hook.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.modules.module.register_module_forward_pre_hook.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_abs.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_abs_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_acos.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_acos_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_asin.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_asin_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_atan.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_atan_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_ceil.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_cos.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_cos_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_cosh.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_cosh_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_erf.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_erf_.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7115 Fix description error in broadcast_tensors.
  docs/api/paddle/broadcast_tensors_cn.rst
Labels: contributor

#7114 [Docathon][Add Inplace CN Doc No.10、11]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/cumprod__cn.rst
  docs/api/paddle/cumsum__cn.rst
Labels: contributor, HappyOpenSource

#7129 [Docathon][Add Inplace CN Doc No.35]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/multiply__cn.rst
Labels: contributor, HappyOpenSource

#7132 [Docathon][Fix note No.1-4]
  docs/api/paddle/add_cn.rst
  docs/api/paddle/greater_equal_cn.rst
  docs/api/paddle/linalg/eigvals_cn.rst
  docs/api/paddle/tensordot_cn.rst
Labels: contributor, HappyOpenSource

#7135 [Docathon][Update Doc No.27] Update the index of fluid
  docs/api_guides/low_level/layers/index.rst
  docs/api_guides/low_level/layers/index_en.rst
Labels: contributor, HappyOpenSource

#7149 [Docathon][Add Inplace CN Doc No.2、23-27]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/baddbmm__cn.rst
  docs/api/paddle/ldexp__cn.rst
  docs/api/paddle/less__cn.rst
  docs/api/paddle/less_equal__cn.rst
  docs/api/paddle/less_than__cn.rst
  docs/api/paddle/lgamma__cn.rst
Labels: contributor, HappyOpenSource

#7130 映射文档补充与修改
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.index_copy_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.to_sparse_csr.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.Backend.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.cosine_similarity.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.Module.state_dict.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.jit.ignore.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.jit.save.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/others/torch.jit.script.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_exp.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_expm1.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_expm1_.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch._foreach_floor.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/torch/torch.randint_like.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7138 [Docathon][Fix note No.5-7]
  docs/api/paddle/metric/Auc_cn.rst
  docs/api/paddle/metric/Precision_cn.rst
  docs/api/paddle/metric/Recall_cn.rst
Labels: contributor, HappyOpenSource

#7150 [Docathon][Fix note No.20-24]
  docs/api/paddle/optimizer/NAdam_cn.rst
  docs/api/paddle/optimizer/Optimizer_cn.rst
  docs/api/paddle/optimizer/RAdam_cn.rst
  docs/api/paddle/optimizer/RMSProp_cn.rst
  docs/api/paddle/optimizer/SGD_cn.rst
Labels: contributor, HappyOpenSource

#7155 [Docathon][Fix note No.27-28]
  docs/api/paddle/static/Variable_cn.rst
  docs/api/paddle/static/set_program_state_cn.rst
Labels: contributor, HappyOpenSource

#7145 [Docathon][Fix note No.19]
  docs/api/paddle/optimizer/Momentum_cn.rst
Labels: contributor, HappyOpenSource

#7151 [Docathon][Add Inplace CN Doc No.44、45、46、47]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/tril__cn.rst
  docs/api/paddle/triu__cn.rst
  docs/api/paddle/trunc__cn.rst
  docs/api/paddle/where__cn.rst
Labels: contributor, HappyOpenSource

#7119 [Docathon][Add Inplace CN Doc No.36]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/nan_to_num__cn.rst
Labels: contributor, HappyOpenSource

#7161 [Docathon][Fix note No.17-18]
  docs/api/paddle/optimizer/LBFGS_cn.rst
  docs/api/paddle/optimizer/Lamb_cn.rst
Labels: contributor, HappyOpenSource

#7164 【Docathon】[Fix note No.5-7]
  docs/api/paddle/metric/Auc_cn.rst
Labels: contributor, HappyOpenSource

#7169 [Docathon][Fix note No.14]
  docs/api/paddle/optimizer/Adadelta_cn.rst
Labels: contributor, HappyOpenSource

#7113 [Docathon][Add Inplace CN Doc No.37-38]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/neg__cn.rst
  docs/api/paddle/normal__cn.rst
Labels: contributor, HappyOpenSource

#7126 [Docathon][Add Inplace CN Doc No.18]
  docs/api/paddle/geometric__cn.rst
Labels: contributor, HappyOpenSource

#7139 [Docathon][Add Inplace CN Doc No.34、39]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/logit__cn.rst
  docs/api/paddle/polygamma__cn.rst
Labels: contributor, HappyOpenSource

#7182 [Docathon][Update Doc No.28] add the LRScheduler
  docs/api_guides/low_level/layers/learning_rate_scheduler.rst
  docs/api_guides/low_level/layers/learning_rate_scheduler_en.rst
Labels: contributor

#7143 [Docathon][Add Inplace CN Doc No.7]
  docs/api/paddle/Overview_cn.rst
  docs/api/paddle/bitwise_xor__cn.rst
Labels: contributor, HappyOpenSource

#7162 [Docathon][Fix note No.15-16]
  docs/api/paddle/optimizer/Adam_cn.rst
  docs/api/paddle/optimizer/Adamax_cn.rst
Labels: contributor, HappyOpenSource

#7177 [Docathon][Fix note No.44]
  docs/api/paddle/static/nn/sparse_embedding_cn.rst
Labels: contributor, HappyOpenSource
