Repository PaddlePaddle/docs, pull requests merged in 2025-01, with the labels that each got.

#7031 映射文档对齐
  docs/guides/model_convert/convert_from_pytorch/api_difference/Tensor/torch.Tensor.itemsize.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.rpc_async.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/distributed/torch.distributed.rpc.rpc_sync.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/functional/torch.nn.functional.ctc_loss.md
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.CTCLoss.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7028 Update `F.multi_label_soft_margin_loss/nn.MultiLabelSoftMarginLoss` docs 易用性提升
  docs/api/paddle/nn/MultiLabelSoftMarginLoss_cn.rst
  docs/api/paddle/nn/functional/multi_label_soft_margin_loss_cn.rst
  docs/guides/model_convert/convert_from_pytorch/api_difference/nn/torch.nn.MultiLabelMarginLoss.md
  docs/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.md
Labels: contributor

#7032 Update cn_api_paddle_ParamAttr link
  docs/api/paddle/nn/LayerNorm_cn.rst
Labels: contributor, HappyOpenSource

#6902 [Docathon][Add API Legend No.35]为moveaxis增加图片说明 -part
  docs/api/paddle/moveaxis_cn.rst
  docs/images/api_legend/moveaxis.png
Labels: contributor, HappyOpenSource

#7037 【 Paddle Tensor 规范化第二期 】改正cholesky 文档中对x形状描述的不正确
  docs/api/paddle/linalg/cholesky_cn.rst
Labels: contributor, HappyOpenSource

#6971 [SCU][Docathon][Add API Legend No.36]为tensordot API添加图例
  docs/api/paddle/tensordot_cn.rst
  docs/images/api_legend/tensordot.png
Labels: contributor, HappyOpenSource Pro

#7039 更正svd、svdvals文档中的公式
  docs/api/paddle/linalg/svd_cn.rst
  docs/api/paddle/linalg/svdvals_cn.rst
Labels: contributor, HappyOpenSource
